### ISSUE TITLE
Capture does not process payload of TCP session with no SYN Flag

### ISSUE THREAD

**Issue by aminlatifi** [arkime/arkime#1004]
Hello,
moloch-capture does not process payload of a TCP session, which is in the PCAP file attached. 
I did debug and saw it is because session neither start with nor have a packet with SYN flag. 
I modified packet.c file and I think the problem is solved. You may decide better. Also, I did regression test and just single-packets test failed and it seems the new result is more correct.

**Elasticsearch version**:

**Moloch version**:
1.7
**OS name and version**:
Ubuntu 18.04
**How was Moloch built/installed:** (rpm, deb, easybutton, ...)
easybutton
**Provide logs, stack traces and steps to reproduce**:

[p1-session1.zip](https://github.com/aol/moloch/files/2803047/p1-session1.zip)
[resolve suggest.zip](https://github.com/aol/moloch/files/2803058/resolve.suggest.zip)

**Comment by awick** [comment]
Yes this is how moloch works, it requires either a SYN or SYN-ACK.  I guess we could add an option to make it more loose, but you might end up with wacky results.  Feel free to open a PR with your solution.
