### ISSUE TITLE
Decode and index HTTP multipart headers

### ISSUE THREAD

**Issue by qlb7707** [arkime/arkime#1037]
I use moloch to decode http upload file package, but I nerver see the filename in moloch http decoder. I know the filename in content-disposition field , and I nerver see moloch decode content-disposition field in post method.intersting,I saw content-disposition field in get method ,can you help me?

**Comment by awick** [comment]
You could add the field as one you want to search on.

https://github.com/aol/moloch/wiki/Settings#headershttprequest

```
[headers-http-request]
content-disposition=type:string
```

**Comment by qlb7707** [comment]
it doesn't work, I config it in config.ini,but it doesn't work. and i nerver see content-disposition in elasticsearch

**Comment by awick** [comment]
oh its a response header not request, it works when I try it.

**Comment by qlb7707** [comment]
> You could add the field as one you want to search on.
> 
> https://github.com/aol/moloch/wiki/Settings#headershttprequest
> 
> ```
> [headers-http-request]
> content-disposition=type:string
> ```

it doesn't work, I config it in config.ini,but it doesn't work. and i nerver see content-disposition in elasticsearch

**Comment by qlb7707** [comment]
> oh its a response header not request, it works when I try it.

Are you try it with http post method,not get method. when you upload file ,content-disposition is in request

**Comment by awick** [comment]
Please attach or DM on slack a sample pcap

**Comment by qlb7707** [comment]
> Please attach or DM on slack a sample pcap

[upload_file.zip](https://github.com/aol/moloch/files/3022385/upload_file.zip)

**Comment by qlb7707** [comment]
> Please attach or DM on slack a sample pcap

[upload_file.zip](https://github.com/aol/moloch/files/3022414/upload_file.zip)

you can see it in  http post method

**Comment by awick** [comment]
Thanks.  Currently moloch doesn't look at headers inside of multipart/form-data, so this will be a new feature.  Can I use the sample pcap in the test suite?

**Comment by qlb7707** [comment]
> Thanks. Currently moloch doesn't look at headers inside of multipart/form-data, so this will be a new feature. Can I use the sample pcap in the test suite?

my pleasure,thanks!

**Comment by awick** [comment]
I think this is fixed in 5.0
