### ISSUE TITLE
Viewer does not show session data completely 

### ISSUE THREAD

**Issue by aminlatifi** [arkime/arkime#1043]
**Elasticsearch version**:

**Moloch version**: 1.7

**OS name and version**: Ubuntu

**How was Moloch built/installed**: easybutton

Viewer does not show session content completely for a session. I attached session pcap file.
In this case, HTTP response 

> HTTP/1.1 200 Connection established\r\n

is not shown in the viewer session content.

[190330-cVNagchhqcFAmLgSlewuBcUs.zip](https://github.com/aol/moloch/files/3054028/190330-cVNagchhqcFAmLgSlewuBcUs.zip)

**Comment by awick** [comment]
Thanks, was able to reproduce.  A workaround for now in 1.8.0 is you can select show packets.
