### ISSUE TITLE
dns parse wrong when moloch parse a  bad dns packet

### ISSUE THREAD

**Issue by hongjiangchen** [arkime/arkime#1051]
[dns_packet.zip](https://github.com/aol/moloch/files/3110442/dns_packet.zip)

if a bad dns packet coming, i think moloch not need to parse it , and parse to a wrong domain name

**Comment by awick** [comment]
So it looks like the one query has valid lengths and such for the name.  You don't want moloch to parse it because the packet is lieing about the answers and other things?

**Comment by hongjiangchen** [comment]
> So it looks like the one query has valid lengths and such for the name. You don't want moloch to parse it because the packet is lieing about the answers and other things?

yes, I think moloch not need to parse a bad packet , do you think a bad packet is useful ?

**Comment by awick** [comment]
Depends how you define bad packet.  This one has a good query section.  The query section could have a valid hostname in it.  Is it causing some issue?

**Comment by hongjiangchen** [comment]
> Depends how you define bad packet. This one has a good query section. The query section could have a valid hostname in it. Is it causing some issue?

it is not cause some issue,but i need the domain name,this packet paser a strange domain name.
if i do not want moloch parse it ,how can i do ?
