### ISSUE TITLE
moloch parse http filename to be a unreadable code

### ISSUE THREAD

**Issue by hongjiangchen** [arkime/arkime#1055]
when I use moloch parse http that filename or url contains of chinese, filename or url to be unreadable code

**Comment by awick** [comment]
Can you attach a sample pcap or DM me one on slack.

**Comment by hongjiangchen** [comment]
> Can you attach a sample pcap or DM me one on slack.

here is the pcap and download file that I test, you can see the filename/uri is unreadable.
and from 
https://github.com/aol/moloch/issues/1037#issue-426368376
[package.zip](https://github.com/aol/moloch/files/3133793/package.zip)
I know moloch can not parse filename from content-disposition in multipart header

**Comment by awick** [comment]
Do you have any pcap with a full tcp session (SYN/SYN-ACK)?

**Comment by hongjiangchen** [comment]
> Do you have any pcap with a full tcp session (SYN/SYN-ACK)?

sure, here is the pcap,and the filename is nmap扫描.txt
[downloadFile.zip](https://github.com/aol/moloch/files/3155033/downloadFile.zip)

**Comment by awick** [comment]
So are you talking about the url display?

`10.180.188.19/nmap%E6%89%AB%E6%8F%8F.txt`

We display what is on the wire.  Are you suggesting that we decode this?  I don't think we would change the current display, but maybe we could add a decoded display also?  What is the use case?

**Comment by hongjiangchen** [comment]
> So are you talking about the url display?
> 
> `10.180.188.19/nmap%E6%89%AB%E6%8F%8F.txt`
> 
> We display what is on the wire. Are you suggesting that we decode this? I don't think we would change the current display, but maybe we could add a decoded display also? What is the use case?

For a user, he enters a URL in his browser, and the browser sends it as a URLEncode to the network, and moloch parses it out and of course parses it into the one that the user understands, which is the URL that he enters,  not the URL that the browser does the URLEncode for

**Comment by awick** [comment]
It is not clear to me how to know we should decode the item and display it in the decoded format.  It could also just be random data in the url.

We might be able to do the reverse, where if you say `http.uri.path == nmap扫描.txt` we could encode it.

**Comment by hongjiangchen** [comment]
> It is not clear to me how to know we should decode the item and display it in the decoded format. It could also just be random data in the url.
> 
> We might be able to do the reverse, where if you say `http.uri.path == nmap扫描.txt` we could encode it.

yes,it's also a solution
