### ISSUE TITLE
Feature Request: LDAP/AD role-based access control on viewer

### ISSUE THREAD

**Issue by schenksj** [arkime/arkime#1083]
I'd like to leverage active directory/LDAP groups to provision access moloch viewer.  We offload AD authentication to a web server w/plugin, but would like to use our central user management system as a policy information point for authorizations in moloch rather than managing it within moloch itself.  This would make user management and access audit far easier for us.

**Comment by awick** [comment]
Would need someone to work with us and contribute an implementation

**Comment by schenksj** [comment]
@awick Let me see what I can muster up

**Comment by schenksj** [comment]
@awick Quick sanity check.  Would you agree that the appropriate place to implement this logic is here: https://github.com/aol/moloch/blob/074711b2f6a9dfec1b1859b32e1a00deed70323e/viewer/db.js#L545-L588 ?

Conditionally create compatible objects from an LDAP call instead of ES when configured to do so?

**Comment by awick** [comment]
Depends what you are trying to do.  Probably best if you come over to slack to discuss.  I can see a few different implementations
1) totally replace ES for user storage - this means all set/get/search User apis are replaced, and that ldap lets us store the views, permissions and other things on the user object.  Probably easiest from moloch implementation, but need to make sure ldap can do/store everything ES can
2) ldap is only used for the permissions, so need to merge ldap and es results
3) ldap is only used when user doesn't exist, so one time ldap check and copy

or maybe there is something in between.

Whatever is decided need to come up with some user abstractions.  Need to tell the UI how to deal with user, for example with solution #1, #2 probably shouldn't be able to edit the user's permissions from moloch. 

I would start with writing up more detail on what you want and joining slack

**Comment by 31453** [comment]
Does the implementation of https://github.com/aol/moloch/issues/1095 suffice? Or is this feature request still necessary?

**Comment by ademirleite** [comment]
@schenksj 
Good Morning!
How do you integrate MOLOCH with LDAP, would you have any example I could follow?
Thank you for your attention.

**Comment by 31453** [comment]
Please reopen if this feature is still wanted and necessary.
