### ISSUE TITLE
LADP of SPI  Chinese random code

### ISSUE THREAD

**Issue by xisafe** [arkime/arkime#1099]
**Elasticsearch version**:

**Moloch version**:

**OS name and version**:

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

![image](https://user-images.githubusercontent.com/29724312/60253617-0c2f0000-98ff-11e9-8307-44a198995578.png)
Is there a problem elsewhere? I want to translate it into Chinese. Where is the language package?

**Comment by awick** [comment]
please provide a sample pcap so we can fix

**Comment by 31453** [comment]
Please reopen with sample pcap.
