### ISSUE TITLE
sessionless support

### ISSUE THREAD

**Issue by bf31415** [arkime/arkime#1149]
In the network router control protocol space, the order of BGP and IGP updates define the state of the router at that point in time.  In order to be able to deduce a device's control plane state at any point in time, this packet arrival ordering needs to be maintained.  If we treat BGP like a normal TCP session (in the moloch sense), where multiple updates are grouped and recorded as arriving at the same time disparate aggregation points, down stream analytics loose the ability to accurately deduce the router state at any point in time.

This feature request is to allow the moloch operator to define a sequence of protocols and/or protocol:port combinations which the capture system should treat as "sessionless", meaning each packet is a unique session.  No aggregation occurs for those streams which are to be treated as sessionless and thus both packet arrival sequence and packet arrival timing is maintained.

A new config variable to specify which protocols and/or protocol:ports would be defined to indicate which should be treated a sessionless.   An example of what this might look like is below:

// enumerate which protocols and/or protocol:port tuples should be processed
// as being sessionless (packets have no relationship to each other).
sessionless=1;2;6:179

In the above example protocols 1 (icmp), 2 (igmp) and 6:179 (tcp bgp) would be treated as sessionless.  For all other protocol and/or protocol:port combination, the existing session oriented behavior is maintained.

**Comment by awick** [comment]
Not sure icmp should ever be considered sessionless, at least by default.  I still think there is probably a better way to do this, just need to spend some time on it.

**Comment by bf31415** [comment]
thanks for the input.   it's up to the moloch operator to determine what protocols and/or protocols+ports would be treated as sessionless.  default is normal moloch behavior.  info specified in the "sessionless" config would allow the operator to override default moloch behavior
