### ISSUE TITLE
ethernet support

### ISSUE THREAD

**Issue by bf31415** [arkime/arkime#1150]
ISIS is a commonly used IGP protocol but its not based on IP but instead is rides over ethernet llc frames.  this feature request is to enable moloch to decode, parse, and decorate specific ethernet frames with isis and lldp being the initial target protocols.   ethernet frames which are not known as part of this feature extension will continue to fall through and be recordered (or not) as defined by the config.saveEtherPacket

there is an assumption that any ethernet protocol known to moloch will be treated as sessionless.  unless there are additional use cases requiring different behavior, ethernet protocols will be sessionless and won't require extension to the sessionless config item outlined in 1149.

**Comment by awick** [comment]
I think this is done
