### ISSUE TITLE
[Feature Request] ARP traffic capture

### ISSUE THREAD

**Issue by StammesOpfer** [arkime/arkime#1159]
When collecting traffic deeper within a network, a method to collect and view ARP traffic specifically but other lower level protocols (CDP, STP, iSCSI) may be useful as well. With the current implementation there is no good way to see an ARP attack. It would be nice to have visibility to ALL traffic however ARP would be a good start.

**Comment by awick** [comment]
Can you please provide how you would actually use this and what you want to do with it.
Its just lots of ```23:59:53.910008 ARP, Request who-has 10.130.144.1 tell 10.130.149.173, length 46
23:59:53.912206 ARP, 10 172.130.144.1 is-at 00:00:00:ff:10:01, length 42``` which I think make pretty useless sessions in moloch.

**Comment by StammesOpfer** [comment]
This is more from a forensics and threat hunting perspective. It is useless until an attack and there is no evidence collected about what happened. As the primary tool for full pcap collection in an enterprise environment deployed down to the access layer moloch not collecting this is a significant gap in coverage.

If I had insight into ARP it stands out very quickly if there is an ARP spoofing attack because it generally requires a very high packet rate to sustain the spoofed address rather than reverting to the proper MAC address. This is a single use case example. 

It would probably make sense to make this an optional feature.

**Comment by awick** [comment]
Ya we general talk about Moloch as an IP full packet capture system.  We've also never really deployed at the network segment level where most spoof attacks happen.  I'm still not clear how to capture or display this in moloch.  You really just want to see every arp packet?  That is going to crush your elasticsearch cluster.  Maybe just changes?  Really just need to understand the use cases better or other tools that do what you are looking for.

**Comment by StammesOpfer** [comment]
I would be completely ok with seeing every ARP. From my experience even on a sizable network ARP traffic is not a great percentage of the traffic (unless under attack). I doubt it would have a major impact on the elastic cluster under normal circumstances. 

The use case here is to be able to identify a Man in the Middle attack or Black Holed traffic executed at Layer 2 via ARP spoofing. From a non attack perspective it is also useful to have the data for troubleshooting certain network conditions. 

As far as other solutions raw pcap collected with tcpdump and viewed in wireshark is perfectly functional other than not being able to handle data on any real scale. Zeek/Bro had a plugin prior to 2.0 that may have worked but it has not been ported to 2.0+.

ARP changes are interesting too however that seems like it would fall outside the scope of moloch. The volume of ARP packets plus their content is also a key indicator since there are legitimate reasons changes occur (though usually not at the access layer).

**Comment by bf31415** [comment]
@StammesOpfer.  Fyi I just submitted a PR to add ethernet support for moloch.   My use case isn't arp related but i have a need for certain L2 protocols to be captured to analytic purposes.   That said this is very much a work in progress as it relies on another PR that is still in vetting phase.

Regarding arp ddos and load on elastic, one fearture extension to this could be to define a pps limit.  so to prevent elastic from being overloaded with ddos arp traffic,  this configurable feature might allow only (say) 100 ARP packets per second to get written to elastic.  all other arp packets are dropped by moloch during the ingest phase until the next interval

While it wouldn't give you all arps, the excessive rate would tell you via alerting that a problem is happening and their might be enough bread crumbs in the arps that do get stored into elastic to figure out the issue and mitigate

**Comment by awick** [comment]
So when looking at percentage of traffic remember that moloch and elasticsearch are session based, and not packet based.  Just because something is low traffic wise, doesn't mean it will be low sessionwise if there is 1 or 2 packets per session where something like http might have 20 or 40 packets per session.  @bf31415 and I are having similar discussions for some of the features he wants.  You are right that having it off by default could make it so it doesn't matter, but in general when possible I like to make it so things are turned on by default.

So to get to the actual feature, I'm looking for ways to collapse multiple packets into a session.  For example if you had the same ARP QUERY/REPLY over and over in 30 seconds, couldn't that be collapsed into 1 session?  You could count the number of times, but is it required that each query/reply be a session?

**Comment by StammesOpfer** [comment]
@bf31415 that sounds like exactly what I am looking for. The other layer 2 protocols would be great as well.

**Comment by StammesOpfer** [comment]
For ARP specifically collapsing it and giving a count would work fine. As a search for count greater than X  would surface things very quickly.

**Comment by awick** [comment]
arp parsing has been added, you need to add `disableParsers=` to config file, since right now it defaults to arp.so

**Comment by maxplusx23** [comment]
> arp parsing has been added, you need to add `disableParsers=` to config file, since right now it defaults to arp.so

i 've added the disableParsers= to my config file(/opt/arkime/etc/config.ini),but i still can't see the arp packets,how can i fix this?

**Comment by webking1** [comment]
Version 6. Same here. Nothing happens. There's nothing in the config.ini specifically saying disableParsers=arp.so

I've added "disableParsers=" with nothing after the equal to the config file and restated capture. Nothing. Can someone confirm thing feature is added? Thanks.

**Comment by awick** [comment]
confirmed it works.

If it doesn't work for you please open a NEW issue, include a tcpdump sample and make sure you have `disableParsers=` right after the `[default]` and include the output of `capture --version`
