### ISSUE TITLE
Feature request - scrub elasticsearch credentials from log output

### ISSUE THREAD

**Issue by MattCarothers** [arkime/arkime#1231]
Today capture logs the full elasticsearch URL, including the username and password provided.  It would be better practice if all logged instances of https://user:pass@host:port could be replaced with https://host:port or similar.

**Comment by awick** [comment]
should we just add new esUser/esPass config.ini options?

**Comment by MattCarothers** [comment]
That sounds like an excellent idea.  It would clean up the config quite a bit too.

**Comment by awick** [comment]
3.1 - added elasticsearchBasicAuth/usersElasticsearchBasicAuth
3.0 - added elasticsearchAPIKey/usersElasticsearchAPIKey

Can also set logESRequests=false
