### ISSUE TITLE
Capture does not handle in --copy mixed RAW and ETHERNET pcaps

### ISSUE THREAD

**Issue by pjsg** [arkime/arkime#1293]
**Moloch version**: git master

If you have mixed pcaps of linktype 1 and linktype 101 in the same `capture --copy` then I think that the output file has the same type as the first pcap file. The entries from the other pcap file are just written into it (in the wrong format). The packet traces are decoded correctly.

I think that capture --copy should skip pcap files which differ in linktype from the first pcap file that it opens. 

Also, as a side issue, I noticed that moloch only handles IPv4 in DLT_RAW (101). It ought to check the first byte to see if it is a v4 header or a v6 header.

I'll probably end up doing a couple of PRs for this issue.

**Comment by pjsg** [comment]
Actually, I ended up just moving each link type into its own directory and running the capture tool multiple times.

**Comment by awick** [comment]
#1303 is probably related.  We could either skip or just open new files each time the linktype changes.

**Comment by awick** [comment]
we still don't support mixed pcap files, but hopefully dlt ipv6 is fixed now
