### ISSUE TITLE
Moloch Rule does not work exactly

### ISSUE THREAD

**Issue by pakjack79** [arkime/arkime#1349]
**Elasticsearch version**: 6.8

**Moloch version**: 2.1

**OS name and version**: Ubuntu

**How was Moloch built/installed:** (rpm, deb, easybutton, ...): deb

**Provide logs, stack traces and steps to reproduce**:
Hi, i have configure this rule like below to do not save session relate to teamviewer.com but i still see many sessions contains teamviewer.com:
---
version: 1
rules:
  - name: "dont save teamview.com"
    when: "fieldSet"                                                                                             
               fields: 
                 host.http,contains:
                     - teamviewer.com
                ops:
                 _dontSaveSPI: 1      

Please help me check this!

**Comment by awick** [comment]
Can you provide sample pcap that doesn't match, feel free to DM it to me on slack if you can't post publicly.

**Comment by awick** [comment]
Feel free to reopen with more info
