### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [arkime/arkime#1379]
I would like to point out that identifiers like “[`_DLL_HEADER`](https://github.com/aol/moloch/blob/70189a99998278b50e805480a00955ae592fdda9/capture/dll.h#L14 "Update candidate")” and “[`_MOLOCH_LUA_`](https://github.com/aol/moloch/blob/a4738602279bf6758916e2b80055530a5d33ba75/capture/plugins/lua/molua.h#L1 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by awick** [comment]
Feel free to submit to PRs.
