### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [arkime/arkime#1381]
Would you like to add more error handling for return values from functions like the following?
- [malloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [moloch_trie_init](https://github.com/aol/moloch/blob/f070e9f7992ada01e4e1b6f1757aee0309012f43/capture/trie.c#L27)
- [MOLOCH_LOCK_INIT](https://github.com/aol/moloch/blob/664ffe25810380f12823941c210efad4e9881124/capture/moloch.h#L248 "Initialize a mutex.") ⇒ [moloch_session_init](https://github.com/aol/moloch/blob/493a95b91add87c04986ab7fd4e691d7540c5f9e/capture/session.c#L613)

**Comment by awick** [comment]
i don't understand the question.  Feel free to submit to PRs or come over to slack.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by awick** [comment]
Sure PRs are always welcome.  trie was never used so it probably should be removed.
