### ISSUE TITLE
[feature proposal] Kafka as SPI data output

### ISSUE THREAD

**Issue by killerwhile** [arkime/arkime#1399]
Moloch is sending SPI data directly to Elastic, using the `/_bulk` API. 
While this is proven to do the job and rather well, having Kafka in between might be useful
in some use case, for instance a (near) real-time alerting on SPI pattern. In short,
once the SPI data is in Kafka, it can be re-read multiple time at a rather low effort and cost.

The diagram below show this write once - read many pattern Kafka (or similar technology)
can help implementing:

```
                                                ┌         ┐
                 ┌       ┐  ┌─> _ES indexer_ >──┤ elastic ├──< moloch-viewer
moloch-capture >─┤ kafka ├──┤                   └         ┘
                 └       ┘  ├─> (near) real time alerting on some patterns
                            │
                            └─> ... some other processing ... 
```

In order to have the Moloch setup working the same way than before,
two components would be required:
1. Kafka plugin running in Moloch-capture and sending the SPI to Kafka instead of Elastic
2. An _ES indexer_, consuming from Kafka and indexing to Elastic in the same collections that Moloch 
   itself would do to ensure feature parity.

# Kafka plugin

Moloch has a powerful built-in plugin mechanism which could be leveraged to:
- load the plugin
- initialize the connection to Kafka
- hook into SPI data sending mechanism using `moloch_db_set_send_bulk` setter.

This approach means that instead of calling the default `moloch_db_send_bulk` function
which is post'ing the SPI data to the `/_bulk` endpoint of Elastic,
this exact same payload, when ready, would be send to Kafka instead.
This keeps the design easy and to not add any overhead (or very little)
to Moloch-capture.

The disadvantage of this approach is that the data post'ed to Elastic in a [json lines format](http://jsonlines.org/)
*with* some metadata json in between, mostly the name of the collection to insert into. 
I.e. a consumer of the SPI data might do some (easy, but still) parsing of
the message before decoding a single SPI.

A watch item in this approach part is Kafka limitation in the message payload (1MB by default).

# ES Indexer

The second part in the proposed approach is a component reading from Kafka
and indexing the SPI in Elastic (i.e. what Moloch-capture is doing by default)
This component can be standalone, outside of Moloch. If the messages sent to Kafka
remain untouched as it was proposed, they can be directly post'ed to Elastic.

There are already numerous of tools doing that (reading from Kafka and indexing to Elastic):
- [Kafka Connect for Elastic search](https://github.com/confluentinc/kafka-connect-elasticsearch),
- [Logstash](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-kafka.html)
- [Fluentd](https://github.com/fluent/fluent-plugin-kafka)
- ...

but very few of them are using the `/_bulk` API.
And in the proposed design, the payload pushed to Kafka can literally be post'ed as is to `/_bulk`.

Writing this in [Akka streams](https://doc.akka.io/docs/akka/current/stream/index.html) would fit in less than 20 lines of code:

```scala
  val elasticBulkEndpoint = "http://elastic/_bulk"
  val httpPool =
    Http().superPool[ConsumerRecord[Integer, String]]()

  Consumer
    .plainSource[Integer, String](kafkaConsumerSettings, Subscriptions.topics(topic))
    .map { msg =>
      (HttpRequest(
         method = HttpMethods.POST,
         uri = elasticBulkEndpoint,
         entity = HttpEntity(ContentTypes.`application/json`, msg.value())
       ),
       msg)
    }
    .via(httpPool)
    .run
```

# Pros and cons

This approach does *not* completely remove Moloch interactions with Elastic, since
stats and new file calls are still done directly from Moloch.

But having Kafka in between Moloch and Elastic for the SPI data might be useful
to amortize the pressure on Elastic by providing a buffer,
and allows multiple processing/indexing streams consuming the SPI data

The downside of the approach is the additional complexity of running a Kafka cluster
and a _ES indexer_ component.

**Comment by paulpc** [comment]
I asked for something similar a while back. Makes a lot of sense at large deployments and to further enrich spi data outside of wise.

The added complexity is non-trivia, especially managing threads to and fro kafka. However, biggest benefit is ability to do inline detection logic and analytics on the data in a lambda architecture (fast path = viewer + elastic, slow path = pick_your_fav_spark_engine + binary store).

**Comment by lleiwang** [comment]
@31453 It is significant to accept and implement the proposal.

**Comment by killerwhile** [comment]
I got a bit side tracked, sorry for that, but a PR is coming shortly.

**Comment by killerwhile** [comment]
I pushed my working branch in https://github.com/touilleio/arkime/tree/feature/kafka-v3.0, but I mixed few things in, mostly containerization of Arkime and kafka plugin.
The latter is available directly in https://github.com/touilleio/arkime/tree/feature/kafka-v3.0/capture/plugins/kafka

**Comment by killerwhile** [comment]
you can directly `docker pull touilleio/arkime:v3` if you're adventurous

**Comment by awick** [comment]
Added in #2179 and #2177

Would still like to add msg format to choose from bulk, buik1, doc in the future and provide sample consumers.
