### ISSUE TITLE
support shortcuts across multiple clusters

### ISSUE THREAD

**Issue by awick** [arkime/arkime#1423]
Right now shortcuts have to be created on each cluster because of how ES works.  For people running multiple clusters it would be nice to have a central location to create/edit/view the shortcuts and have the updated in all the different clusters.  It would be nice to have a method to edit once and sync everywhere.  

Possible solutions, not sure the best.
* Make this a parliament feature.  Parliament keeps a db on short cuts and syncs to all clusters it knows about.
* Make this a wise feature.  Requires a wise UI.  Have viewer query wise occasionally and update elasticsearch.  maybe only cron query nodes.
* Make this a viewer feature, which ever viewer you edit on updates all the rest.

**Comment by 31453** [comment]
fixed in #1706
