### ISSUE TITLE
Add support for geoLite2City database

### ISSUE THREAD

**Issue by iiiusky** [arkime/arkime#1446]
GeoLite2City is used to parse the IP, and the following fields should be added in elasticsearch:

```
"geoip": {
           "type": "object",
           "dynamic": true,
           "properties": {
             "location": {
               "type": "geo_point"
             },
             "country_name": {
               "type": "string"
             },
             "city_name": {
               "type": "string"
             },
             "region_name": {
               "type": "string"
             }
           }
         }
```

**Comment by awick** [comment]
Do you really want all those fields per session?

**Comment by iiiusky** [comment]
> Do you really want all those fields per session?

yes

**Comment by awick** [comment]
Can you share use cases for them?

**Comment by iiiusky** [comment]
> 您可以为他们共享用例吗？
I do n’t quite understand what you mean. After the traffic is stored in es, I want to use kibana to show where the traffic comes from and where it is sent, but I found that although there is some geo data, it is not the standard geo data format, which makes me unable to The map module is used in kibana to display it, and the subsequent subdivided analysis data according to countries, provinces and cities.

**Comment by iiiusky** [comment]
> Can you share use cases for them?

I do n’t quite understand what you mean. After the traffic is stored in es, I want to use kibana to show where the traffic comes from and where it is sent, but I found that although there is some geo data, it is not the standard geo data format, which makes me unable to The map module is used in kibana to display it, and the subsequent subdivided analysis data according to countries, provinces and cities.

**Comment by awick** [comment]
My question is for each of the fields how do you plan to use it.  Moloch already has country code which works inside moloch and kibana (or at least used to).  I don't really want to add the location and country name, since location usually isn't very accurate and we already have country code.  That leaves city name and region, how will you use those?

**Comment by iiiusky** [comment]
> My question is for each of the fields how do you plan to use it. Moloch already has country code which works inside moloch and kibana (or at least used to). I don't really want to add the location and country name, since location usually isn't very accurate and we already have country code. That leaves city name and region, how will you use those?

I have a vpn system, access to moloch for traffic viewing and access information. My members are in the same country as me, but they are in different provinces and regions. If I use the current geo data, I can only put it on the map Seeing my country hit, I need to know this information. The ip information is changing in real time, and the location information is relatively accurate at least at the time (it wo n’t be the kind of absolutely accurate data, of course, the geo-charged version may be more accurate. When analyzing the log data, I feel that adding provinces and The region can save most people from having to process the data twice or multiple times because the country code is too general.

**Comment by iiiusky** [comment]
This project is a very good project, and I like it very much. I hope to add the geo data of the provinces, cities and regions, so that it may be accepted and used by more people. It is recommended to use geo data, and field mapping support (geo_point) is given. I really hope to add this support, thank you very much
