### ISSUE TITLE
Add tag/field for TLSv1.3 sessions with ESNI

### ISSUE THREAD

**Issue by renini** [arkime/arkime#1508]
This is a feature request to add support for the identification of TLSv1.3 traffic with ESNI (Encrypted Server Name Indication).

The ESNI extension in de TLSv1.3 Client Hello handshake is based on the [draft-ietf-tls-esni](https://tools.ietf.org/html/draft-ietf-tls-esni-07). Currently the draft is at version 7 and ESNI is changed to ECH (Encrypted Client Hello), ECH will encrypt the complete Client Hello instead of just the Server Name Indication. 

In my opinion although ESNI is specified in an older draft, it is still valuable to be able to differentiate this kind of traffic in Moloch, since this is already deployed with both Firefox and Cloudflare supporting the [ESNI draft (i believe v3)](https://tools.ietf.org/html/draft-ietf-tls-esni-03). In my testing of the Alexa top 1000 domains, 107 currently support this ESNI draft (all hosted/proxied by Cloudflare).

For the newer draft that specifies ECH I haven't seen any client/browser or server support yet, but since the draft is getting finalized this will probably happen in the near future, as all major browsers seem to work on this. While ECH is being finalized it is foreseeable that ESNI might live parallel to that for the time being.

### A way to reproduce this kind of traffic on Firefox
- enable DoH, Network Settings -> Enable DNS over HTTPS -> Use Provider Cloudflare (this is used to get the key material securely)
- enable ESNI, about:config -> network.security.esni.enabled -> true
- visit an ESNI enabled domain, examples are: medium.com, cloudflare.com, discord.com

An easy test url is: https://www.cloudflare.com/cdn-cgi/trace this will return:
```
...
tls=TLSv1.3
sni=encrypted
...
```
whenever your client is successfully using ESNI.

In the current version of Moloch (2.3.2) the following matches this traffic:
`tls.version == TLSv1.3 && host.http != EXISTS!`
But i'm not sure about any false positives, and a dedicated flag to filter on might be nicer.

### Technical details from the draft-ietf-tls-esni-03
  The encrypted SNI is carried in an "encrypted_server_name" extension,
   defined as follows:

      enum {
          encrypted_server_name(0xffce), (65535)
      } ExtensionType;

   For clients (in ClientHello), this extension contains the following
   ClientEncryptedSNI structure:

      struct {
          CipherSuite suite;
          KeyShareEntry key_share;
          opaque record_digest<0..2^16-1>;
          opaque encrypted_sni<0..2^16-1>;
      } ClientEncryptedSNI;
---
### Sample PCAP
I captured the TCP traffic between Firefox 79.0 (client) and https://www.cloudflare.com/cdn-cgi/trace (server) this contains a TLSv1.3 session with ESNI, and can be found here:
[c2s-esni-example.pcap.gz](https://github.com/aol/moloch/files/5089601/c2s-esni-example.pcap.gz)

### Wireshark filter
In Wireshark (tested with v3.2.5) the following filter can be applied to filter on the Client Hello that uses ESNI:
`tls.esni.encrypted_sni`

**Comment by navidpadid** [comment]
Any news on this feature?
