### ISSUE TITLE
Add POST version of expression APIs

### ISSUE THREAD

**Issue by awick** [arkime/arkime#1535]
Add POST versions of any APIs that support expression so that long expressions work better.  Then switch the UI to use them. Would be best if could use something like app.all instead of having app.get and.post that might make things get out of sync, but not sure if possible.

**Comment by 31453** [comment]
What if we just support only POST for all of these endpoints?

**Comment by awick** [comment]
For NEW and maybe not commonly used APIs I could see that, but for sessions* I don't want to break folks.

**Comment by 31453** [comment]
Implemented in #1546
