### ISSUE TITLE
moloch_2.4.2-1_amd64.deb contains an TROJAN

### ISSUE THREAD

**Issue by erdincay** [arkime/arkime#1548]
**Elasticsearch version**: non-applicable

**Moloch version**: 2.4.2-1

**OS name and version**: PopOS! (Debian-derivate through Ubuntu)

**How was Moloch built/installed:** DEB (installation was cancelled due to virus signature)

**Provide logs, stack traces and steps to reproduce**: non-applicable

virus location within the archive: ..../data/data/moloch/viewer/node_modules/re2/tests/test_symbols.js

detected type: JS.DownLoader.1783

**Comment by awick** [comment]
Can you please provide the exact download url you used

**Comment by awick** [comment]
Without more information this looks like a false positive. I downloaded all 3 debs and the file is the same across them and doesn't have any code that looks bad in it. The good news is even if it does have something bad in it, we don't use this file or tests at all.

**Comment by awick** [comment]
Looks like this is probably just a DrWeb false positive, maybe because of the eval or trump strings. https://www.virustotal.com/gui/file/eb4fc71e2ff1cc18834e275928a049acd866d29a7e2964ff8dbd96fe784ddf11/detection

https://arkime.com/security has some better methods for reporting security issues in the future, including the ability to make money

**Comment by erdincay** [comment]
Hello Andy, 

- the file is in the delivered DEB package, which means if it has been already tree-shaken and still is within the production build, **it is used**.
- in the other case, that it hasn't been removed because the production build hasn't been tree-shaken, i would suggest you to do an production build with npm.
- it is possibly not false-positive, because the file is from Google and the detecting engine is from Dr. Web, which means I do not trust Google in this concern. 

Best regards,
Erdinc

**Comment by awick** [comment]
> * the file is in the delivered DEB package, which means if it has been already tree-shaken and still is within the production build, **it is used**.

It is not **used**, the easiest way to check is by trying to run it, you'll see the package "heya-unit" isn't found and isn't included, which means it can't even run. We also don't run "npm run test" in the re2 directory at build or run time as far as I can find.


> * in the other case, that it hasn't been removed because the production build hasn't been tree-shaken, i would suggest you to do an production build with npm.

We do a production build, if we did a dev build then the "heya-unit" module would be installed because it is a devDependencies" in the re2 directory. I tried doing a "npm ci --production" and the file is still there. Or maybe I don't understand what you mean.

> * it is possibly not false-positive, because the file is from Google and the detecting engine is from Dr. Web, which means I do not trust Google in this concern.

Did you look at the code? I see nothing wrong with it. You haven't included the download url you got the package from, so I don't know if I'm look at the same thing.

While re2 is from google, I'm not sure if node-re2 (the wrapper we use) is or not. https://github.com/uhop/node-re2 we are using a older version, but it matches what is in github https://github.com/uhop/node-re2/blob/1.11.0/tests/test_symbols.js

If you don't want to trust google that is your choice

**Comment by amaddalena** [comment]
@erdincay  - I do not see anything wrong with the packaged file within the deb build after forensic review of the noted file. Have you noted anything during file review that is counter this analysis which you could point to for further review? 

Please advise.

**Comment by erdincay** [comment]
> > * the file is in the delivered DEB package, which means if it has been already tree-shaken and still is within the production build, **it is used**.
> 
> **It is not used**, the easiest way to check is by trying to run it, you'll see the package "heya-unit" isn't found and isn't included, which means it can't even run. We also don't run "npm run test" in the re2 directory at build or run time as far as I can find.
> 
> > * in the other case, that it hasn't been removed because the production build hasn't been tree-shaken, i would suggest you to do an production build with npm.
> 
> We do a production build, if we did a dev build then the "heya-unit" module would be installed because it is a "devDependencies" in the re2 directory. I tried doing a "npm ci --production" locally and the file is still there. You can see in the viewer/Makefile we do a "npm ci --production". Or maybe I don't understand what you mean.
> 
> > * it is possibly not false-positive, because the file is from Google and the detecting engine is from Dr. Web, which means I do not trust Google in this concern.
> 
> Did you look at the code? I see nothing wrong with it. You haven't included the download url you got the package from, so I don't know if I'm look at the same thing.
> 
> While re2 is from google, I'm not sure if node-re2 (the wrapper we use) is or not. The code for the package can be found at https://github.com/uhop/node-re2 Yes, we are using a older version, but what is in the deb matches what is in github https://github.com/uhop/node-re2/blob/1.11.0/tests/test_symbols.js
> 
> If you don't want to trust google that is your choice

I checked the Google repository and couldn't find the file anymore, they seem to have removed it in the newer versions or it is maybe only in the wrapper. I didn't want to create you an extra task, I really was thinking it is an genuine issue. 

I looked actually at the mentioned file's code, but I wasn't sure, if it could be harmful, as you know it is Javascript. If it would be an basic arithmetic operation in Javascript, I wouldn't be sure if it is harmless, because it is Javascript.

**Comment by erdincay** [comment]
> @erdincay - I do not see anything wrong with the packaged file within the deb build after forensic review of the noted file. Have you noted anything during file review that is counter this analysis which you could point to for further review?
> 
> Please advise.

I am not able to provide any further support, due to my limits in Javascript in-depth knowledge and resources. If it would be C, C++, Java, or any other SANE programming language, I would debug that to the last CPU operation and last pointer address.

**Comment by awick** [comment]
> I checked the Google repository and couldn't find the file anymore, they seem to have removed it in the newer versions or it is maybe only in the wrapper. I didn't want to create you an extra task, I really was thinking it is an genuine issue.

Yes it is removed in newer versions, but if you go to https://github.com/uhop/node-re2/blob/1.11.0/tests/test_symbols.js you can see it

**Comment by erdincay** [comment]
> > I checked the Google repository and couldn't find the file anymore, they seem to have removed it in the newer versions or it is maybe only in the wrapper. I didn't want to create you an extra task, I really was thinking it is an genuine issue.
> 
> Yes it is removed in newer versions, but if you go to https://github.com/uhop/node-re2/blob/1.11.0/tests/test_symbols.js you can see it

holy moly, that was an fast response

**Comment by awick** [comment]
haha, we have github hooked up to slack, we know almost instantly whenever any comment is made. :)

**Comment by erdincay** [comment]
> haha, we have github hooked up to slack, we know almost instantly whenever any comment is made. :)

:D
