### ISSUE TITLE
Allow for multiple shortcuts to be called via a wildcard (*)

### ISSUE THREAD

**Issue by amaddalena** [arkime/arkime#1554]
Please allow for multiple shortcuts to be called via a wildcard : 

**Example:** 
_ip==$MY_shortcut*_
this would allow for the expansion to include _$MY_shortcut1, $MY_shortcutA, $MY_shortcutFOO, $MY_shortcutBAR._

Additionally, a modifier which would allow this expansion to be either an AND or OR declaration could be useful.

**Potential Example:**
_ip==$MY_shortcut* would map to (ip==$MY_shortcut1 || ip==$MY_shortcutA)
ip==$$MY_shortcut* would map to (ip==$MY_shortcut1 && ip==$MY_shortcutA)_ 

**Alternatively something like the below (depending on preference) :** 
_ip==$|MY_shortcut* would map to (ip==$MY_shortcut1 || ip==$MY_shortcutA)
ip==$&MY_shortcut* would map to (ip==$MY_shortcut1 && ip==$MY_shortcutA)_

Let me know if you would like anything clarified. TIA!

-Art

**Comment by 31453** [comment]
Make sure to document this in the help section (otherwise it would be a hidden feature).

**Comment by 31453** [comment]
Possibly do a comma separated list of shortcuts.

**Comment by 31453** [comment]
implemented here: 8f1883c
