### ISSUE TITLE
Moloch (Arkime) viewer encrypted PCAP cannot decrypt PCAP >32GB

### ISSUE THREAD

**Issue by packley** [arkime/arkime#1555]
The viewer code assumes `aes-256-ctr`-encrypted PCAPs position indexes are not addressable past a signed 32-bit integer.  When a PCAP residing at an unaddressable index is retrieved through the UI, a traceback similar to the following can be encountered:

```

internal/buffer.js:35

    throw new ERR_OUT_OF_RANGE('value', `>= ${min} and <= ${max}`, value);

    ^

RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= -2147483648 and <= 2147483647. Received 2285227154

    at checkInt (internal/buffer.js:35:11)

    at writeU_Int32BE (internal/buffer.js:757:3)

    at Buffer.writeInt32BE (internal/buffer.js:845:10)

    at Pcap.createDecipher (/data/moloch/viewer/pcap.js:140:11)

    at fs.read (/data/moloch/viewer/pcap.js:204:29)

    at FSReqWrap.wrapper [as oncomplete] (fs.js:467:17)

Debug Level 2 

```

The traceback points to this call:

https://github.com/aol/moloch/blob/64a15d8a9ffc02e993d5e7192a8a195bcda45989/viewer/pcap.js#L140

 
We could not find a simple way to reproduce this issue other than taking a large PCAP.  However, there is a simple workaround.  In the config just set `maxFileSizeG` to <32GB.  For a fix we can only suggest two options: either 1) check and enforce smaller PCAP sizes at startup for encrypted configurations or 2) update the viewer code decipher initialization to support addressing beyond signed int ranges.

Thanks!

**Comment by awick** [comment]
Could you try changing this call to writeUInt32BE and see if that fixes the issue?
We already have a 64G limit in writer-simple.c, could change that to 32G if needed.

**Comment by packley** [comment]
Yes, we can try that but we are concerned that it would be difficult to test. 

Can you think of an easier way to trigger this issue?

Thanks.

**Comment by awick** [comment]
Oh I assumed you still had the file and session that was failing and could just retry whatever you did.

**Comment by packley** [comment]
We did replay the pcap with `maxFileSizeG` <32gb set to test the workaround.

**Comment by awick** [comment]
so you dont have a file > 32G anymore to test with?

**Comment by packley** [comment]
Sorry -- correct. We don't have an instance running at the moment with the oversized PCAP configuration.
