### ISSUE TITLE
rare character in SESSIONS (source / destination)

### ISSUE THREAD

**Issue by scdit46** [arkime/arkime#1559]
**Elasticsearch version**: 7.10.0

**Moloch version**: 2.7.1

**OS name and version**: Centos 8

**How was Moloch built/installed:** (rpm, deb, easybutton, ...) rpm

**Provide logs, stack traces and steps to reproduce**:

When I open a session, I see rare character in the last section Source - Destination 
The exception is when the protocol is HTTP.
The others functions work sucessfull.
I tried with firefox and chrome.

**Comment by scdit46** [comment]
for example for protocol snmp (the comunitty is public):

**Source**
2020/12/08 03:25:01 CET44 bytes
0* public� ~�� 0 0 + �e

**Comment by awick** [comment]
Can you provide a screenshot or more details?

**Comment by scdit46** [comment]
![moloch](https://user-images.githubusercontent.com/63736962/101431883-13d24100-3908-11eb-931f-93f3ad39819f.png)

**Comment by scdit46** [comment]
with protocol http I see OK the source and destination

With the others protocols (HTTPS, SNMP, DNS, ....) I see rare characters

**Comment by awick** [comment]
It is normal for binary protocols to have "strange looking" characters in ascii/natural view, try changing to hex. We use github only for feature requests and bugs, please use slack for questions in the future.
