### ISSUE TITLE
Getting support at arkime

### ISSUE THREAD

**Issue by joroMaser** [arkime/arkime#1573]
How can I ask support questions with arkime?

I tried to login for https://arkime.slack.com/ with my Gmail account but I got error

Xxxx@gmail.com doesn’t have an account on this workspace.

Is there another way? Support forum?

**Comment by awick** [comment]
We use slack, try creating an account at slackinvite.arkime.com

**Comment by joroMaser** [comment]
@awick 
http://www.slackinvite.arkime.com/
Broken link

**Comment by awick** [comment]
no leading www or go to arkime.com and click any of the slack links.
