### ISSUE TITLE
Can't use readTruncatedPackets

### ISSUE THREAD

**Issue by joroMaser** [arkime/arkime#1575]
Ubuntu 18 ,arkime release 2020-12-01

I tried to add pcap file 
./moloch_capture -r PATH_TO_PCAP
And I got error
Moloch requires full packets captures lens .if using tcpdump use the -s0 option or set readTruncatedPackets in ini file.

I set in /etc/comfig.ini readTruncatedPackets=true and restart moloch services but still I got that error.

**Comment by awick** [comment]
please use slack for questions.
