### ISSUE TITLE
drop check interfaces while import pcap file

### ISSUE THREAD

**Issue by joroMaser** [arkime/arkime#1576]
Arkime/Moloch Hybrid 2.7.1
2020-12-01
I don't want to sniffint with arkime so I put ; in installtion into interfaces
Into config.ini I see
Semicolon ';' seperated list of interfaces to listen on for traffic
interface=;

now When I want to import pcap into arkime I go error

root@ubuntu:/data/moloch/bin# ./moloch-capture -r /home/lab/temp.pcap 
Dec 24 11:10:14 main.c:202 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps, use the --host option - ubuntu
interface set in config file, but it is empty

I think you need to drop this check , why does it metter if I don't have interfaces to monitor if I only want to import pcap file?

**Comment by awick** [comment]
we use github for bug reports and feature requests, please use slack for questions.
