### ISSUE TITLE
display startup timestamp on wise stats page

### ISSUE THREAD

**Issue by awick** [arkime/arkime#1580]
Display the startup on the stats page. Maybe on the same line as Sources/Types but on the far right. The /stats endpoint returns it as startupTime element. For now display as localtime, although I'm slowly adding user support so maybe eventually it could use the same setting as viewer.

![image](https://user-images.githubusercontent.com/427321/104027596-9a8f6d80-5195-11eb-9433-7ab4b1872a58.png)

**Comment by 31453** [comment]
@awick want this on only the Stats page? Or on all pages? If on all pages, can I put it in the navbar?

**Comment by awick** [comment]
I was thinking just the stats page, but I don't really care and easier you can put in nav bar

**Comment by 31453** [comment]
It's easier to put it on the Stats page. I'm going to do that if that was your initial thought
