### ISSUE TITLE
We have a problem.

### ISSUE THREAD

**Issue by wengcwf** [arkime/arkime#1584]
We use this command to import the Pcap file, we import successfully, but when we select "+", the CyberChef field is loading, any ideas? other field (source ip , dest ip ) is work. use normal capture , no this issue , CyberChef field normal display
${arkime_dir}/bin/moloch-capture -c [config_file] -r [pcap_file]

**Comment by awick** [comment]
we use github for bugs and feature requests, we use slack for questions. If you decide to repost on slack please always include a version number with questions, and in this case a screen shot because I'm not sure what you are asking.

**Comment by wengcwf** [comment]
hello ..
when we use this command import the Pcap file  "${arkime_dir}/bin/moloch-capture -c [config_file] -r [pcap_file]"
import Pcap status is successfully , but when i click below icon 
![image](https://user-images.githubusercontent.com/56724879/104095367-57d2b000-52d1-11eb-8c5c-2617c1cbbaa3.png)
the loading session packets does not show . how can fix it , thank  
version 2.4.2 or other . 
![image](https://user-images.githubusercontent.com/56724879/104095400-8f415c80-52d1-11eb-8fc6-27c6ff0eac13.png)
