### ISSUE TITLE
cant download the GEO files?

### ISSUE THREAD

**Issue by So1o** [arkime/arkime#1585]
i cant download the GEO files with the HTTP CODE 401,it may means the shell has wrong account ID?

**Elasticsearch version**:7.10.1

**Moloch version**:2.7.1

**OS name and version**:centos7

**How was Moloch built/installed:** (rpm, deb, easybutton, ...)rpm

**Provide logs, stack traces and steps to reproduce**:
[root@server1 bin]# ./Configure 
Found interfaces: eth0;lo
Semicolon ';' seperated list of interfaces to monitor [eth1] eth0
Install Elasticsearch server locally for demo, must have at least 3G of memory, NOT recommended for production use (yes or no) [no] no
Elasticsearch server URL [http://localhost:9200] http://127.0.0.1:9200
Password to encrypt S2S and other things [no-default] 111111
Moloch - Creating configuration files
Installing systemd start files, use systemctl
Download GEO files? (yes or no) [yes] yes
Moloch - Downloading GEO files
2021-01-10 15:12:48 URL:https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv [23322/23322] -> "/tmp/tmp.HFQkiov0dh" [1]
Received an unexpected HTTP status code of 401 from https://updates.maxmind.com/app/update_secure?db_md5=00000000000000000000000000000000&challenge_md5=58d974187385075fd96cbb244a742619&user_id=0&edition_id=GeoLite2-Country:
Invalid account ID

**Comment by awick** [comment]
We use github for bugs and feature requests, please use slack for questions. The FAQ is always a great place to start too.
