### ISSUE TITLE
ARKIME FILE NAME COLLISION (PCAP TRAMPLING/LOCKING)

### ISSUE THREAD

**Issue by ccosuwah** [arkime/arkime#1586]
**Elasticsearch version**: 7.8.0

**Moloch version**:2.3.2

**OS name and version**: Linux Debian V10

**Provide logs, stack traces and steps to reproduce**:

Arkime’s file tracking in Elastic (files_v6 index) takes the form shown below. Because the _id uses only the node and serial counter (001), we have observed namespace collisions (with subsequent deletion/overwriting/locking issues) when Arkime is restarted.
 
```
{
  "_index": "files_v6",
  "_type": "file",
  "_id": "NODE-001",
  "_score": 1,
  "_source": {
    "num": 001,
    "name": "/path/to/pcap/NODE-YYMMDD-00000001.pcap",
    "first": ...,
    "node": "NODE",
     ...
    "filesize": ...
  }
}
```

**Probable solution**:
Arkime may need to include an additional modifier with the _id, perhaps date, so the namespace for files increases sizably and there is less chance for issues after a restart. As a current workaround, we use db.pl add-missing prior to starting Arkime to add any PCAP that may not have gotten added to the files index.

**Comment by awick** [comment]
Sorry I'm not following the bug report, can you provide more information? 

What number to use next isn't actually controlled by the files index, it is controlled by the sequence index, and using add-missing would NOT actually increment the next number, so you would still have over writes if there was a sequence issue.

Are you saying that there items missing from the files index? Is your ES cluster overloaded? That would happen, and add-missing would fix.

**Comment by awick** [comment]
Feel free to reopen if you have more info
