### ISSUE TITLE
map not showing countries and counts

### ISSUE THREAD

**Issue by nocomp** [arkime/arkime#1588]
hi folks,
this for this great tool, new user here.
i ve installed and set the maxmind geoip
nocomp@sandBox:~/Téléchargements/systemback-install_pack-1.9.4$ sudo geoipupdate 
[sudo] Mot de passe de nocomp : 
nocomp@sandBox:~/Téléchargements/systemback-install_pack-1.9.4$
no error
when i open capture file with wireshark, countries show up in endpoints, but in moloch, when i search the ip, no counts anywhere on the map even the ip is found
in fact map is blank, no counts anywhere , just blank continents

any idea what can be wrong?
thx for your time

**Comment by awick** [comment]
We use github for bugs and feature requests, please use slack for questions. The FAQ is always a great place to start too.
