### ISSUE TITLE
moloch-capture -s (--skip) not working

### ISSUE THREAD

**Issue by Master-13** [arkime/arkime#1600]
**Describe the bug**
When running moloch-capture with -s or --skip, file had already processed will process again.
There's a dir named TEST.  `./moloch-capture -R TEST -s` will always processes all files, when I thought moloch would do nothing except the first try.

**Elasticsearch version**:
7.4

**Arkime/Moloch version**:
2.0.2

**OS name and version**:
CentOS7

**Comment by awick** [comment]
Looks like that was fixed in 2.2.1.
