### ISSUE TITLE
Upload button not working

### ISSUE THREAD

**Issue by dforce** [arkime/arkime#1608]
**Describe the bug**

**Elasticsearch version**: 7.11

**Arkime/Moloch version**: 3.0.0

**OS name and version**: Ubuntu 20.04

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

Hi,

I activated the upload button within the GUI. When I upload a pcap file is states that the upload was successful but I don't see anything within the files tab.

Running it with the command line 
`./capture -R /home/user/pcap/`
it works. But this command line is looking within a directory and is not uploading an individual file.

**Comment by awick** [comment]
Make sure you look at the viewer.log for errors and you have the right time range selected.

**Comment by dforce** [comment]
There is nothing in the logfile and I don't see any file that have been uploaded in the tab "Files".

**Comment by awick** [comment]
You should be seeing a line like "upload command ...." if you don't then you might be looking at the wrong file

**Comment by dforce** [comment]
I see and upload but it is saying "- bytes" and my pcap file has a length of 920 bytes.
It says that is upload was successful but no bytes were uploaded.

**Comment by dforce** [comment]
I have been using the older version of moloch and this was not a problem.
Now I did a fresh new install of arkime, so no upgrade because on a new PC.

**Comment by awick** [comment]
nope there should be a "upload command" line, you'll need to find that, and you can try it manually

**Comment by dforce** [comment]
This is my viewer.log file
[viewer.log](https://github.com/arkime/arkime/files/6003579/viewer.log)

**Comment by 31453** [comment]
Fixed in this commit 7bb4b85

Thanks for bringing it to our attention.
