### ISSUE TITLE
packetLen is not accurate

### ISSUE THREAD

**Issue by ericliuk** [arkime/arkime#1611]
I'm learning the master branch code. I found that there are only 5 packages in the session, but there are 6 values in the packetLen array, and the first one is 0. I checked the code, and I think it is the initialization in Figure 1, I don't quite understand why this initialization is added here, and the next line is added again immediately after. I tried to mask out the first initialization, and then the output came out fine.

**Elasticsearch version**: 7.11.1

**Arkime/Moloch version**: master, 3.0

**OS name and version**:

![image](https://user-images.githubusercontent.com/67360695/108967527-9c1be300-76ba-11eb-932b-4adabaea0a5e.png)

**Comment by awick** [comment]
We use github for bugs and feature requests, please use slack for questions. The FAQ is always a great place to start too.
