### ISSUE TITLE
Service molochviewer.service may fail to start if Elastic Search is not up yet

### ISSUE THREAD

**Issue by copeland3300** [arkime/arkime#1624]
**Describe the bug**

On a system where ES and Moloch/Arkime are on the same machine, molochviewer.service can fail to start if the elasticsearch.service has not finished starting. 

**Elasticsearch version**:
7.11

**Arkime/Moloch version**:
2.7.1

**OS name and version**:
Ubuntu 18.04

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb

**Provide logs, stack traces and steps to reproduce**:
systemctl status molochviewer.service

**Comment by awick** [comment]
Yes, we recommend they don't run on the same machine. Not sure how to fix other than increase the number of times viewer/capture tries to restart?

**Comment by copeland3300** [comment]
I've added ExecStartPre=/bin/sleep 15 in the [Service] section of the systemd service, which fixed it.

**Comment by awick** [comment]
* sleep is never the answer, the folks using dedicated clusters don't want to be dropping packets.
* if you really want to use sleep then instead you should look at RestartSec, which will at least try once before sleeping
* a better solution is probably fooling with StartLimitInterval, StartLimitBurst and other retry rate limiting and/or counts settings
