### ISSUE TITLE
"Network Error" accessing "Connections" and "Sessions" in Browser

### ISSUE THREAD

**Issue by kmoellenhoff** [arkime/arkime#1627]
Clean Ubuntu Installation in Virtual Server
Used Package installation of latest Moloch/Arkime

Capture works fine. Accessing SPIView displays recorded packages.
Accessing Sessions or Connections is not possible. "Network Error" is displayed.

A curl from commandline 

`curl -vvv -i --anyauth 'http://admin:XXX@IP:8005/sessions.json'`

works fine and displays the json at the commandline as expected.

Trying to access "Connections" via Chrome or Firefox will result in the following entries /data/moloch/logs/viewer.log

`Mon, 15 Mar 2021 09:09:29 GMT admin GET /connections 200 - bytes 6.980 ms Mon, 15 Mar 2021 09:09:29 GMT admin GET /static/css/app.2e18480a8756a04cb7ad.css 304 - bytes 2.705 ms Mon, 15 Mar 2021 09:09:29 GMT admin GET /static/css/vendor.2e18480a8756a04cb7ad.css 304 - bytes 1.234 ms Mon, 15 Mar 2021 09:09:29 GMT admin GET /static/js/runtime.e6f3d3bc53c92efd1f1b.js 304 - bytes 1.715 ms Mon, 15 Mar 2021 09:09:29 GMT admin GET /static/js/2.5a241e770a5fdca4fea5.js 304 - bytes 1.649 ms Mon, 15 Mar 2021 09:09:29 GMT admin GET /static/js/0.6a2fedf71b4f483e3e11.js 304 - bytes 1.574 ms Mon, 15 Mar 2021 09:09:30 GMT admin GET /user/current 200 589 bytes 0.566 ms Mon, 15 Mar 2021 09:09:30 GMT - GET /eshealth.json 200 456 bytes 5.012 ms Mon, 15 Mar 2021 09:09:30 GMT admin GET /molochclusters 304 - bytes 1.817 ms Mon, 15 Mar 2021 09:09:30 GMT admin GET /state/fieldHistory 200 2 bytes
0.860 ms
Mon, 15 Mar 2021 09:09:30 GMT admin GET /fields 304 - bytes 1.188 ms Mon, 15 Mar 2021 09:09:30 GMT admin GET /user/views 200 2 bytes 5.096 ms
`

- Views where not touched at all and everything is left as it was after fresh install. 
- Firewall is turned off
- ssh and all other access to the virtual machine work fine
- http and no https is used...
Any idea whats going wrong?!!

**Comment by awick** [comment]
We use slack for bug reports and feature requests, please ask questions on Slack.
