### ISSUE TITLE
Dark theme fix in SessionDetail

### ISSUE THREAD

**Issue by rnbwdsh** [arkime/arkime#1662]
SessionDetail uses a select that isn't themed yet, so in dark mode, there is an oddly bright select control left.
Screenshot:
![darktheme_fix](https://user-images.githubusercontent.com/9084941/112570588-97943880-8de6-11eb-8ed3-c0138256fac7.png)

The fix colors it like the buttons next to it. However, the dropdown-button can't easily be themed, as it's part of a native control, so it's black on dark, so further css magic could improve the results.

Fix in #1656

**Comment by 31453** [comment]
fixed in #1656
