### ISSUE TITLE
Duplicated select code and unneccesary long select code

### ISSUE THREAD

**Issue by rnbwdsh** [arkime/arkime#1665]
Many selects in the code can use the options-parameter to list literal options instead of way more HTML code.

Also the select in the 4 export-views to select a segment were copy-pasted and the component can simply be extracted to a segment-selection component. The code should be written vue3 proof (no v-model binding, that will change its behaviour in 2 -> 3, but .sync binding)

Fixed in #1655

**Comment by 31453** [comment]
fixed in #1655
