### ISSUE TITLE
Unable to perform make config file not found

### ISSUE THREAD

**Issue by 13716667943** [arkime/arkime#1666]
**Describe the bug**

**Elasticsearch version**:

**Arkime/Moloch version**:
2.3.2
**OS name and version**:
centos 7
**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
The source code
**Provide logs, stack traces and steps to reproduce**:

[root@localhost arkime]# make config
make: *** No rule to make target `config'. Stop.

**Comment by awick** [comment]
We use github for bugs and feature requests. Please ask questions on slack.
