### ISSUE TITLE
GRE tunnel endpoint IP-s should be visible in session details

### ISSUE THREAD

**Issue by TNogisto** [arkime/arkime#1676]
I think that GRE tunnel endpoint IP-s should be visible in session details. Currently they are not and this can lead to confusion, as the only way how to "identify gre" from Arkime viewer is to check if it has protocol "gre". This is not ideal.

Splitting "gre ip" to "gre src" and "gre dst" could also be a good idea.

**Elasticsearch version**: 7.9.1

**Arkime/Moloch version**:2.7.1

**OS name and version**: Ubuntu 18

**How was Arkime/Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**: open a gre tunnel session, would expect to see "gre tunnel" fields there, but they are not there.

**Comment by scilicet64** [comment]
it seems the gre ip is indeed not visible as "GRE IP" like it should. it's listed in the IP db, but only when gre is the latest endpoint ip.

when a vxlan frame follows the gre ip is not visible like the screenshot. ERSPAN ip is 100.96.1.3* but the inner vxlan ip is shown: (not erspan ip: 10.0.0.*)

![erspan-failure](https://user-images.githubusercontent.com/46298739/169098463-33593178-237e-445e-bca4-2ff05bb743cd.png)

**Comment by awick** [comment]
please provide a sample pcap, that really is the best way we can fix these types of issues

**Comment by scilicet64** [comment]
this one is fixed in https://github.com/arkime/arkime/pull/1891
can I please add the Vxlan ip in the same style of gre ip under this PR/ticket ?

**Comment by awick** [comment]
Let us know if this isn't what you were looking for
