### ISSUE TITLE
Hunt Improvements

### ISSUE THREAD

**Issue by 31453** [arkime/arkime#1686]
- [x] show rerun/replay even if not finished
- [x] cancel the hunt - move it to the history section - disallow playing
- [x] add button to remove hunt id and hunt name from matches sessions (if you have remove data priv and you're an admin or created the hunt)

**Comment by kmcgerald** [comment]
I would also add a button to stop/cancel the hunt.  More than just pausing it.  

"That hunt was a bad idea! I should cancel it."
