### ISSUE TITLE
db.pl does not support basic HTTP auth for Elasticsearch connection

### ISSUE THREAD

**Issue by mosajjal** [arkime/arkime#1687]
**Describe the bug**
db.pl does not support basic HTTP auth for Elasticsearch connection

**Elasticsearch version**:
7.5.1

**Arkime/Moloch version**:
2.7.1

**OS name and version**:
CentOS 7 latest patch

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm

**Comment by awick** [comment]
We use github for bugs and feature requests, please use Slack for questions.
