### ISSUE TITLE
Add contextual enrichment / deep linking support

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#1703]
I'm looking for Arkime functionality beyond currently available right click link support that consistently gathers and enriches context around any given indicator whether domain name, IP, email address, hashes, phone numbers or arbitrary text, and presents additional user configurable deep links to other resources.

A very early phase attempt at creating this support in a standalone project is at:
https://github.com/TobySalusky/Cont3xt

**Comment by 31453** [comment]
Being implemented in #1780

Maybe we should add links to cont3xt from arkime value actions.
