### ISSUE TITLE
Allow for value actions (previously right click actions) to be selectable for view per user

### ISSUE THREAD

**Issue by amaddalena** [arkime/arkime#1707]
Allow for individuals to be allowed to select which value actions are displayed for their session. Perhaps a checkbox based ENABLED type of list within the user settings page would work? 

Example - User A only wants the "Send to VT" value actions to be displayed. User A would check the box only for this value action in their settings page. 

A "Select All" and DeSelect All" checkbox would also be useful.

Thank you!

**Comment by 31453** [comment]
This feature exists by using the `notUsers` field for each value action in the WISE UI (https://arkime.com/wiseapi#wisesourceapivalueaction-type). Please reopen if this is not a suitable solution and you need this in the viewer settings.
