### ISSUE TITLE
Optimize initial load calls and periodic reloads

### ISSUE THREAD

**Issue by awick** [arkime/arkime#1737]
Currently when you load the sessions page there are around 20 xhr requests, would it be possible to combine some of these? Might require vueapp rearch for the services to listen to emits of the few state pulls or something.

So for example instead of clusters, remoteclusters, fields, views, user, etc just have one call with each of those as a sub objects. Then on periodic refresh it could refresh all of those too.

Also looks like there is a /api/stats call on the sessions page, and I'm not sure if that is still needed.

**Comment by 31453** [comment]
Interesting thoughts. It will definitely require a lot of vueapp changes. But it might be worth it.

What about if a page needs only a few of those items? Like, the settings page needs user, views, and fields, but not clusters. Maybe send a query with what objects to request? Or just return everything for every page?

I also think that we should have an option to send back both a fields array and a fields map from the api/fields endpoint. Right now if a page requires both, it makes 2 separate calls.

I think the stats call is a bug with destroying the stats page. I created a separate issue to deal with that one: #1739

**Comment by awick** [comment]
Since Arkime is usually a SPA I think it would be fine to have everything returned always.
I'm not sure why the server is returning both a map and an array anymore, it seems like one of them could just be created in the vueapp from the data the server returns.

**Comment by 31453** [comment]
Fixed in these PRs: #1745 & #1746
