### ISSUE TITLE
api/stats request interval doesn't get removed

### ISSUE THREAD

**Issue by 31453** [arkime/arkime#1739]
If you navigate to the Stats page, the recurring api/stats call never gets destroyed and will continue as long as the user is using the app.

**Comment by awick** [comment]
I see the stats call even when i never go to stats, just go to sessions on a reload

**Comment by 31453** [comment]
Never mind, this is required for the capture start times for the timeline graph visualization. An optimization that could be made is that if it is toggled off, we should not make this request.
