### ISSUE TITLE
There is something wrong with moloch 2.7.7

### ISSUE THREAD

**Issue by Linn1** [arkime/arkime#1744]
I cat the capture.log,and it says:
http.c:699 moloch_http_curl_close_callback(): Close 0/0 - http://localhost:9200 36738->[::1]:9200 fd:28 removed:true
What is the log means?
The capture can't cap the data and when I run curl http://localhost:8005 ,the result is : Unauthorizedroot

**Comment by Linn1** [comment]
I run curl http://localhost:9200 ，and the results is ok.
The elasticsearch is work but the moloch is not work

**Comment by Linn1** [comment]
sory, the moloch's version is 2.2.3-1
The elasticsearch's version is 7.7.0

**Comment by awick** [comment]
https://arkime.com/questions
