### ISSUE TITLE
esproxy documentation is missing

### ISSUE THREAD

**Issue by rht-jbittner** [arkime/arkime#1752]
Elasticsearch proxy documentation page is missing. 

In [CHANGELOG](https://raw.githubusercontent.com/arkime/arkime/main/CHANGELOG) for version 3.0.0 2021/08/18 esproxy documentation [link](https://arkime.com/esproxy) is provided, but link returns 404.

**Comment by awick** [comment]
Ok first version is up, probably needs some editing by @31453
