### ISSUE TITLE
RangeError [ERR_INVALID_OPT_VALUE] when retrieving some pcaps

### ISSUE THREAD

**Issue by matoro** [arkime/arkime#1756]
**Describe the bug**
We're seeing occasional instances where viewer pcap retrieval will throw a RangeError when trying to read a pcap file into the buffer.  This only occurs when the pcap is large enough that it does not fit into a single buffer.

**Elasticsearch version**:  7.10.2

**Arkime/Moloch version**:  3.0.0

**OS name and version**:  CentOS 7, kernel 3.10.0-1160.11.1.el7.x86_64

**How was Arkime/Moloch built/installed:**  RPM

**Provide logs, stack traces and steps to reproduce**:

```
Sep 10 14:25:34 node[14645]: Error  RangeError [ERR_INVALID_OPT_VALUE]: The value "-1" is invalid for option "size"
Sep 10 14:25:34 node[14645]: at Function.alloc (buffer.js:370:3)
Sep 10 14:25:34 node[14645]: at /opt/arkime/viewer/pcap.js:229:32
Sep 10 14:25:34 node[14645]: at FSReqCallback.wrapper [as oncomplete] (fs.js:561:5) {
Sep 10 14:25:34 node[14645]: code: 'ERR_INVALID_OPT_VALUE'
Sep 10 14:25:34 node[14645]: } for file [REDACTED].pcap
Sep 10 14:25:34 node[14645]: ERROR - processSessionIdDisk - 210910-3UK8GN25hi9Pr6MobR77qcuv in file [REDACTED].pcap couldn't read packet at 7299742684 packet # 4 of 13
Sep 10 14:25:34 node[14645]: Fri, 10 Sep 2021 18:25:34 GMT 162558 GET /[REDACTED]/session/3@210910-3UK8GN25hi9Pr6MobR77qcuv/packets?base=hex&line=false&image=false&gzip=false&ts=true&decode=%7B%7D&packets=50&showFrames=false&showSrc=true&showDst=true&cluster=[REDACTED] 200 - bytes 16.877 ms
```

Environmental info is replaced with `[REDACTED]`.  The offending line in `viewer/pcap.js` is:

```
const buffer2 = Buffer.alloc((16 + len) - bytesRead - posoffset);
```

So I added a debugging line, and got the following info:

```
DEBUG -> the values are: len = 1787, bytesRead = 1792, posoffset = 12 for a total buffer size of -1
```

**Comment by awick** [comment]
thanks for the info and debugging!
