### ISSUE TITLE
wise.js plugin not checking for wiseURL setting

### ISSUE THREAD

**Issue by HunterMorrell** [arkime/arkime#1758]
**Describe the bug**
Setup is dedicated hosts for viewer+wise each. In the `wise.js` plugin (line 23, running on viewer node, repo location: `arkime/capture/plugins/wise.js`), it never checks for a wiseURL setting in the config, only wisePort+wiseHost. 
![image](https://user-images.githubusercontent.com/50470626/133836753-a599f1f9-a762-4f1e-a220-0288c360c83c.png)

The wise docs ( https://arkime.com/wise#wiseso-settings ) state that wiseURL is the recommended setting since 1.5.0 and that it will fall back on wisePort+wiseHost only if that is not set. 

This leads to the (minor) issue of our logs being filled with redundant errors:
![image](https://user-images.githubusercontent.com/50470626/133837154-eaee780c-3a3d-46bc-a2d7-9916b494c642.png)

Beyond that, I'm unsure if the lack of connection to the actual remote wiseService server is affecting the performance and usefulness of the wiseService as a whole. 

**Elasticsearch version**: 7.10.2

**Arkime/Moloch version**: 3.0.0

**OS name and version**:  CentOS 7, kernel 3.10.0-1160.11.1.el7.x86_64

**How was Arkime/Moloch built/installed:** RPM

**Provide logs, stack traces and steps to reproduce**: See above

**Comment by awick** [comment]
thanks
