### ISSUE TITLE
interfaceOps causes crash

### ISSUE THREAD

**Issue by divinehawk** [arkime/arkime#1763]
Setting interfaceOps as described causes capture to crash on startup. For comparison, I installed 1.5 on an older instance and it has the same issue - I'm not sure this feature/syntax has ever worked.

> interface=ens38;ens39
> interfaceOps=tags=ens38;tags=ens39
> 

My suspicion is that moloch_field_by_exp is called from moloch_readers_init() before  moloch_field_init(), and fieldsByExp hash hasn't been initialized.

**Elasticsearch version**:  7.10.2

**Arkime/Moloch version**: 3.0.0 / main

**OS name and version**: Ubuntu 20.04

**How was Arkime/Moloch built/installed:** deb  and easybutton

**Provide logs, stack traces and steps to reproduce**:

#0  0x0000000000000000 in ?? ()
#1  0x00005555555e4f3e in moloch_field_by_exp (exp=0x555556c98970 "tags") at field.c:463
#2  0x00005555555eca2a in moloch_readers_init () at readers.c:96
#3  0x00005555555c5d47 in main (argc=<optimized out>, argv=0x7fffffffe5d8) at main.c:841

**Comment by awick** [comment]
thanks

**Comment by divinehawk** [comment]
Works beautifully now. Thanks for the quick fix!
