### ISSUE TITLE
Problem with Multiviewer and old session2 index in Arkime v3.1.1

### ISSUE THREAD

**Issue by ansv46** [arkime/arkime#1773]
**Describe the bug**
Multiviewer can't show session details in Arkime v3.1.1 for old sessions stored in the session2 index. This happens on nodes without a set prefix for Elasticsearch and old pcap stored in session2. The prefix used by multiviewer is set to "MULTIPREFIX_" in this case. The problem seems to be on line 1779 in _viewer/db.js_. Changing that line from

`    if (ver === '2@' && internals.prefix === 'arkime_') {`

to apply the same logic for MULTIPREFIX_ as for arkime_

`    if (ver === '2@' && (internals.prefix === 'arkime_' || internals.prefix === 'MULTIPREFIX_')) {`

solves the problem.

New pcaps work with and without the fix.

**Elasticsearch version**:
7.10.2

**Arkime/Moloch version**:
Arkime v3.1.1 (upgraded from previous 2.x installations)

**OS name and version**:
Ubuntu 18.04 LTS x86_64

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
Installed with deb.

**Provide logs, stack traces and steps to reproduce**:
Session details will fail when no session can be found for "2@:<session>" when clicking the green "+" to expand and view session details. There should be something like "20w39 between the "@" and ":" in that string.

**Comment by awick** [comment]
are you still having issues?
