### ISSUE TITLE
Issues with npm during install script

### ISSUE THREAD

**Issue by TB05** [arkime/arkime#1785]
**Describe the bug**
install appears to be failing, due to an issue with npm, below is a snippet, log is also attached
npm run viewer:build 
exit status 1

**Elasticsearch version**:
n/a

**Arkime/Moloch version**:
Arkime 3.1.1

**OS name and version**:
centos 7

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
easy button

**Provide logs, stack traces and steps to reproduce**:
centos 7 install updated to most recent packages, git cloned project
[2021-11-19T16_30_57_425Z-debug.log]
(https://github.com/arkime/arkime/files/7571721/2021-11-19T16_30_57_425Z-debug.log)

**Comment by awick** [comment]
The log says to report to npm?
