### ISSUE TITLE
MODBUS protocol support

### ISSUE THREAD

**Issue by mrmeszaros** [arkime/arkime#1806]
**Is your feature request related to a problem? Please describe.**
Currently MODBUS messages are shown raw.

**Describe the solution you'd like**
I would like to see the dissected fields of MODBUS messages.

**Describe alternatives you've considered**
I can download the pcap files, and dissect them with wireshark e.g.

**Additional context**
https://en.wikipedia.org/wiki/Modbus

This will be fixed by #1750

**Comment by awick** [comment]
merged
