### ISSUE TITLE
Arkime Email Notifier via 25 port

### ISSUE THREAD

**Issue by A0123456789B** [arkime/arkime#1816]
**Describe the bug**
I use Arkime in local network withowt internet connection, On my server i have SMPT server. And we have self-signed certificate on it. When we try to create Notifier in Arkime via 25 port, when we try to TEst our notify-rule we have alert "Error alert: Self signed certificate".  We tried to add it to caTrustedCert, try to start in insecire role, nothing can't helped. Can you fix certoficate checking via 25 port.

**Elasticsearch version**:
7.16
**Arkime/Moloch version**:
3.2.1
**OS name and version**:
ubuntu 18.04 console
**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb
**Provide logs, stack traces and steps to reproduce**:
1. Click Settings
2. Go to Notifiers
3. Click Email Notifier
4. Add info about smtp server and enter 25 port. SMTP server must have self-signet cert
5. Enter added info user, password, from, to, subject
6. Click Save
7. Click Test
8. Check alert in upper right corner "Error test alert: Self-signed certificate"

**Comment by awick** [comment]
The package we are using doesn't support it. You'll need to add to whatever node uses for their keystore. https://arkime.com/faq#self-signed-ssl-tls-certificates
