### ISSUE TITLE
Capturing HTTP traffic packets using BPF rules cannot capture segment packets associated with a session

### ISSUE THREAD

**Issue by vdministrator** [arkime/arkime#1831]
I installed the latest version of **Arkime v3 3.1** due to my limited storage space, I need to filter out some traffic and only store traffic packets related to HTTP protocol, such as Get/Post.
**The BPF rules I use are as follows:**
`bpf = (tcp[20:2]=0x4745 or tcp[20:2]=0x4854 or tcp[20:2]=0x504F)`
After restarting the application, I found that Arkime caught incomplete packages, as shown in the following figure:
**- The payload submitted by the post method is missing**
![image](https://user-images.githubusercontent.com/12219743/154446052-cab2fe1b-d0a7-4dc3-9dde-796acfafbcc3.png)
**- The complete HTTP session package can be caught without setting BPF rules. The results are as follows:**
![image](https://user-images.githubusercontent.com/12219743/154449499-5f1bee0a-f50c-4201-ab3f-d05332bf45ed.png)
**- Through Wireshark packet capture analysis, it is found that the post of this session is transmitted through two segments. My rule only matches the segment with post mark, and I can't recognize the other segment**
![image](https://user-images.githubusercontent.com/12219743/154448606-4661abdc-1e50-4e5a-a9e5-79cde3b27d1b.png)
![image](https://user-images.githubusercontent.com/12219743/154447513-dea6e6ee-2212-417f-846e-b29fa0e21b6f.png)
If I don't write BPF, I can correctly catch the full traffic. After writing according to the above rules, I can't catch the full segmented traffic. The following is the result of not writing BPF rules.
**Therefore, I want to know how to use the correct BPF rules or configuration to capture all HTTP traffic. A general rule is not for a specific IP or port, but only for the HTTP protocol, including segmented traffic thank you!**

**Comment by awick** [comment]
https://arkime.com/questions

**Comment by awick** [comment]
Maybe look at arkime rules or bpf port 80

**Comment by vdministrator** [comment]
- [ ] **Solve the problem in this way**

`[root@arkime]# cat /opt/arkime/etc/arkime.rules
version: 1
rules:
  - name: "http"
    when: "fieldSet"
    fields:
      protocols:
      - http
    ops:
      _maxPacketsToSave: 20
  - name: "mail_src"
    when: "fieldSet"
    fields:
      ip.src:
      - 10.x.x.x
    ops:
      _maxPacketsToSave: 20
  - name: "mail_dst"
    when: "fieldSet"
    fields:
      ip.dst:
      - 10.x.x.x
    ops:
      _maxPacketsToSave: 20
  - name: "dns"
    when: "fieldSet"
    fields:
      protocols:
      - dns
    ops:
      _maxPacketsToSave: 5
  - name: "tcp"
    when: "fieldSet"
    fields:
      protocols:
      - tcp
    ops:
      _maxPacketsToSave: 3
  - name: "udp"
    when: "fieldSet"
    fields:
      protocols:
      - udp
    ops:
      _maxPacketsToSave: 2`

**Comment by awick** [comment]
Incase other folks read this, this solution doesn't store just HTTP. I would suggest using bpf to limit to just tcp as a first level filter if you really just want HTTP.

**Comment by vdministrator** [comment]
I use this to do network security analysis, focusing on Web application security analysis, so my focus is to capture all HTTP traffic. I also need to be compatible with other traffic, but I only need a simple session record for auxiliary analysis, so I adopt such a rule.

**Comment by vdministrator** [comment]
My hard disk space is only 1t, so I temporarily store 20 packets in the HTTP session, and then adjust them according to my own needs.
