### ISSUE TITLE
Format date fields in CSV/JSON Exports

### ISSUE THREAD

**Issue by guebe85** [arkime/arkime#1844]
Hi,
the time format in csv export (unix seconds epoch) is not easy readable for humans. Is it possible to change the time format of start and end time, so that in csv file human readable format is present? Or did i forget a chance to change the time format in export?
Thanks a lot for your help!

Greetings

**Comment by guebe85** [comment]
Okay, this is clear to me. But in viewer application time and are given in human format. Where in code this transformation takes place?

**Comment by awick** [comment]
the browser

**Comment by guebe85** [comment]
Thanks a lot!
