### ISSUE TITLE
arkimeviewer fail to start

### ISSUE THREAD

**Issue by liqingjia** [arkime/arkime#1874]
Elasticsearch is ok ,arkimecapture is ok,but arkimeviewer fail to start so port8005 is not listened.anyone can help me.Thank you.

yellow@yellow-virtual-machine:~$ sudo systemctl status arkimecapture.service
● arkimecapture.service - Arkime Capture
   Loaded: loaded (/etc/systemd/system/arkimecapture.service; disabled; vendor preset: enabled)
   Active: active (running) since Wed 2022-04-20 09:23:59 CST; 24s ago
  Process: 3935 ExecStartPre=/opt/arkime/bin/arkime_config_interfaces.sh -c /opt/arkime/etc/config.ini -n default (code=exited, status=0/SUCCESS)
 Main PID: 3956 (sh)
    Tasks: 7 (limit: 4630)
   CGroup: /system.slice/arkimecapture.service
           ├─3956 /bin/sh -c /opt/arkime/bin/capture -c /opt/arkime/etc/config.ini  >> /opt/arkime/logs/capture.log 2>&1
           └─3957 /opt/arkime/bin/capture -c /opt/arkime/etc/config.ini

4月 20 09:23:59 yellow-virtual-machine systemd[1]: Starting Arkime Capture...
4月 20 09:23:59 yellow-virtual-machine systemd[1]: Started Arkime Capture.
yellow@yellow-virtual-machine:~$ sudo systemctl status arkimeviewer.service
● arkimeviewer.service - Arkime Viewer
   Loaded: loaded (/etc/systemd/system/arkimeviewer.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

4月 20 09:24:10 yellow-virtual-machine systemd[1]: Started Arkime Viewer.
yellow@yellow-virtual-machine:~$ curl http://192.168.115.134:9200
{
  "name" : "es-node",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "jDa_MZOjRKOkopgexco8Wg",
  "version" : {
    "number" : "8.1.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "31df9689e80bad366ac20176aa7f2371ea5eb4c1",
    "build_date" : "2022-03-29T21:18:59.991429448Z",
    "build_snapshot" : false,
    "lucene_version" : "9.0.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
yellow@yellow-virtual-machine:~$

**Comment by awick** [comment]
https://arkime.com/questions

**Comment by liqingjia** [comment]
no solution

**Comment by liqingjia** [comment]
ES 8.x is NOT supported before 3.4.1, and we recommend you wait for Arkime 4.0 to be released.
