### ISSUE TITLE
Debian Bullseye

### ISSUE THREAD

**Issue by aimdev** [arkime/arkime#1881]
I installed unbuntu 20.04 (with all its restrictions, sudo everywhere) on a fresh machine, followed the instructions, however when trying to start the capture service it failed as it could not find the libssl library. Installed the library, still an issue.

Started again, this time with Debian Bullseye (no sudo, used root) , followed the instructions
Worked with no issues.

I used the 20.04 arkime deb.

**Comment by awick** [comment]
Sorry, not sure what bug you are actually reporting.

**Comment by aimdev** [comment]
That installing Unbuntu and arkime the capture service failed to start due to an issue with libssl.
This did not occur when arkime was installed on debian bullseye.
This suggest there is an issue with installing on unbunu  (supported), which is not apparent when installing on debian.
I cannot think of anyway of stating the issue other than unbuntu failed, debian didnt.

**Comment by awick** [comment]
So what would be super helpful when reporting bugs is to actually use the template provided andcut/paste the actual error.

So you are saying is on ubuntu 20.04 the arkime 20.04 deb doesn't work? Can you provide the exact error?

**Comment by aimdev** [comment]
Well the unbuntu installation was trashed, so the log no longer exists, however I did a search for

atrkime error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

And this is the issue

**Comment by awick** [comment]
Searched where? I'm confused. Arkime isn't even spelled right in that error

**Comment by aimdev** [comment]
That was the search I used to see if there was an issue with arkime, the error would have been

 error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

when starting the capture process.

**Comment by awick** [comment]
Where did you search?
What version of arkime?

**Comment by aimdev** [comment]
See above

 used the 20.04 arkime deb.

**Comment by awick** [comment]
No where above do I see the version of Arkime. Anyway, without more detailed information there really isn't more I can do since it works for me

<pre>
❯ docker run -ti ubuntu:20.04 bash
root@5eef28621789:/# uname -r
5.10.104-linuxkit
root@5eef28621789:/# apt-get update > /dev/null
root@5eef28621789:/# apt-get install -y file wget > /dev/null
debconf: delaying package configuration, since apt-utils is not installed
root@5eef28621789:/# wget https://s3.amazonaws.com/files.molo.ch/builds/ubuntu-20.04/moloch_3.4.2-1_amd64.deb > /dev/null
root@5eef28621789:/# apt-get install -y ./moloch_3.4.2-1_amd64.deb
/data/moloch/bin/moloch-capture
May  1 17:40:52 main.c:202 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps, use the --host option - 5eef28621789
FATAL CONFIG ERROR - Couldn't load config file (/data/moloch/etc/config.ini) No such file or directory
</pre>

So it works fine. Maybe you are using Ubuntu 22.04?
(I also didn't understand all your sudo vs root comments)

**Comment by aimdev** [comment]
See above

**used the 20.04 arkime deb. (for ubuntu)**

**Comment by awick** [comment]
That is the platform, that is not the arkime version. The version of arkime will look like 3.7.1, we are not up to 20 yet :)

**Comment by aimdev** [comment]
> No where above do I see the version of Arkime. Anyway, without more detailed information there really isn't more I can do since it works for me
> 
> ❯ docker run -ti ubuntu:20.04 bash
> root@5eef28621789:/# uname -r
> 5.10.104-linuxkit
> root@5eef28621789:/# apt-get update > /dev/null
> root@5eef28621789:/# apt-get install -y file wget > /dev/null
> debconf: delaying package configuration, since apt-utils is not installed
> root@5eef28621789:/# wget https://s3.amazonaws.com/files.molo.ch/builds/ubuntu-20.04/moloch_3.4.2-1_amd64.deb > /dev/null
> root@5eef28621789:/# apt-get install -y ./moloch_3.4.2-1_amd64.deb
> /data/moloch/bin/moloch-capture
> May  1 17:40:52 main.c:202 parse_args(): WARNING: gethostname doesn't return a fully qualified name and getdomainname failed, this may cause issues when viewing pcaps, use the --host option - 5eef28621789
> FATAL CONFIG ERROR - Couldn't load config file (/data/moloch/etc/config.ini) No such file or directory
> So it works fine. Maybe you are using Ubuntu 22.04? (I also didn't understand all your sudo vs root comments)

Ubuntu does not allow root access as a default, it requires you to use sudo. Debian does not apply that restriction.

**Comment by awick** [comment]
Ok I can reproduce the error on Ubuntu **22.04** using the ubuntu 20 build of Arkime. Ubuntu 22 isn't supported it.

**Comment by awick** [comment]
Opened #1882

**Comment by aimdev** [comment]
Ok, perhaps support for Debian would be advisable? (cos it does work with the latest version of debian)

**Comment by awick** [comment]
> Yes I did use Ubuntu 22.04 version and I did download the correct version of Arkime, and no it did not work on ubuntu 20.04

Huh? There is NO version for 22.04. And it DOES work on Ubuntu 20.04. I'm still confused if you
* Used the 20 download on 22 and it didn't work - that is to be expected
* Used the 20 download on 20 and it didn't work - that would be a bug, please provide the error


> Which I will point out is out of date, Download an Arkime build for 64bit Ubuntu 14.04, Ubuntu 16.04, Centos 6, or Centos 7 from which does not adhere to the available downloads here

thanks! will update that, unless you want to do a PR?

**Comment by awick** [comment]
> Ok, perhaps support for Debian would be advisable? (cos it does work with the latest version of debian)

We have no plans to offer Debian builds at this time.

**Comment by aimdev** [comment]
And we have no plans to use Ubuntu (but it works on Debian)

**Comment by awick** [comment]
> And we have no plans to use Ubuntu (but it works on Debian)

Then why did you try it and even open this bug? So confused
