### ISSUE TITLE
add inner mac address to the session for encapsulated protocols like: GRE, Geneve, VxLAN

### ISSUE THREAD

**Issue by scilicet64** [arkime/arkime#1887]
**Is your feature request related to a problem? Please describe.**
While capturing ERSPAN encapsulated traffic from a virtual environment we needed to filter on encapsulated mac-address to label traffic, this was not possible with the latest version. 

**Describe the solution you'd like**
We would like to discuss our solution before doing a pull-request. 
My working solution can be found in https://github.com/scilicet64/arkime/tree/multimac.
All tests pass and lint gives no error. Expected tests results for GRE, Geneve and VxLAN where modified because it now outputs the multiple mac addresses. 
For showing and debugging purpose it's currently using a debug with LOG function "moloch_field_macoui_add_debug" that needs to be removed when this solution is checked and discussed for performance.
My code is storing the offset to the first found mac address in the ethernet callback (moloch_packet_ether).
I picked a maximum of 10 encapsulated mac's to be stored (MOLOCH_ETHER_MAX_STORE 10), when it would arrive at encapsulated mac 11, it would overwrite the latest most inner mac. Three encapsulated addresses is what I have seen in practice, I would suggest ten is safe. 

**Describe alternatives you've considered**
First we just added the mac and ouifields for only the most inner mac, however we encoutered multilayer GRE/VxLAN and also needed to track those mac-addresses. Also we experimented with a new field name "encapsulated_mac", but the usability of this was not so great. We found adding it to the existing "mac" field feels more natural, just like in Wireshark for example.

**related issue**
issue: https://github.com/arkime/arkime/issues/1676 can possibly be solved with the same method for multiple encapsulated ip's. The issue how it's described is already implemented, it already shows the most inner encapsulated GRE-ip. However it can be improved for multiple ip's

**Comment by awick** [comment]
Can you do a PR maybe in just your own repo so its easy to see the diff if you don't want to do one here.

**Comment by awick** [comment]
My initial reaction is adding 60 bytes to an important 88 byte data structure isn't the right approach. I would think about using offsets instead to the mac addresses and/or double parsing if this feature is turned on.

**Comment by scilicet64** [comment]
> Can you do a PR maybe in just your own repo so its easy to see the diff if you don't want to do one here.

here you are: https://github.com/arkime/arkime/pull/1888

**Comment by scilicet64** [comment]
> 



> My initial reaction is adding 60 bytes to an important 88 byte data structure isn't the right approach. I would think about using offsets instead to the mac addresses and/or double parsing if this feature is turned on.

I did use offsets in the molochpacket_t datastructure inspired by the style of the used ipOffset. Or do you mean something else?

**Comment by scilicet64** [comment]
sorry for the extra PR, i meant to do the first on my personal repo and needed a new one for the correct information template
