### ISSUE TITLE
How to get packets every 10 minutes in Arkime API?

### ISSUE THREAD

**Issue by sleepyBear92** [arkime/arkime#1909]
To get a packet, I request the server where Arkime is installed.
I am trying to get JSON by referring to the manual, but having trouble.
(manual: https://arkime.com/api#sessionsjson)

**Can't I get JSON in 10 minutes instead of every 1 hour?**
In "/sessions.json", Parameter "date" means seems to be searching for data from 1 hour to the present.
To get data in 10-minute increments, I changed the "date" value from 1 to 0.1, but it seems to work differently.

![image](https://user-images.githubusercontent.com/45308254/171814267-d92cec31-6756-4590-b889-e43038b1cc6c.png)

I tried the method below but failed.
1. Calling the API every 10 minutes (setting 1 hour)
- The maximum number of items is smaller than the amount of data generated per hour. 
- So, I can't get the data without omissions. 
- Furthermore, It is not sorted by date. (I do not know what rule is used to select the data.)

2. Increasing the maximum 
- 20,000 is the maximum number due to lack of computing power.

**Comment by awick** [comment]
https://arkime.com/questions

You might want to look at startTime/stopTime

**Comment by sleepyBear92** [comment]
> https://arkime.com/questions
> 
> You might want to look at startTime/stopTime

I solved it! Thanks to you.
I will use Slack.
