### ISSUE TITLE
Include Threatstream indicator field

### ISSUE THREAD

**Issue by asovern** [arkime/arkime#1918]
Currently it is difficult to determine what specific indicator caused the Threatstream module to appear for an event. Including the indicator field from the Threatstream platform would provide the additional context needed to tie the event back to a malicious IOC.

**Comment by asovern** [comment]
The actual value would be useful to see in the UI.

**Comment by awick** [comment]
This should be fixable with 5.0 custom-fields-remap, i need to provide an example
