### ISSUE TITLE
Session Databytes displays 0 questions

### ISSUE THREAD

**Issue by lzy192251** [arkime/arkime#1932]
Describe the bug
There is PSH data for the actual TCP connection in the session, but databytes is 0 in the session.
![image](https://user-images.githubusercontent.com/9943697/178707874-3045164e-b170-4c87-ac2a-bf51de6bcf85.png)

Elasticsearch version:
7.10.2
Arkime/Moloch version:
v3.4.2
OS name and version:
CentOS 7.9-2009
How was Arkime/Moloch built/installed: (rpm, deb, easybutton, ...)
RPM

**Comment by awick** [comment]
For TCP arkime only counts bytes that were part of the session towards databytes. Since there was on SYN it has no clue what the session is.

**Comment by lzy192251** [comment]
已经收到您的邮件，我会尽快处理。

**Comment by lzy192251** [comment]
> For TCP arkime only counts bytes that were part of the session towards databytes. Since there was no SYN it has no clue what the session is.

Thx.
