### ISSUE TITLE
 Failed to start Arkime Viewer & Capture Service

### ISSUE THREAD

**Issue by CyberReverend** [arkime/arkime#1950]
Good Morning,

I am unable to run both the arkime viewer and capture service. Below is the insert for arkimeviewer:

moloch@ubuntu:/opt/arkime/etc$ sudo systemctl status arkimeviewer.service 
● arkimeviewer.service - Arkime Viewer
     Loaded: loaded (/etc/systemd/system/arkimeviewer.service; disabled; vendor>
     Active: failed (Result: exit-code) since Tue 2022-07-26 12:28:22 PDT; 8s a>
    Process: 3060 ExecStart=/bin/sh -c /opt/arkime/bin/node viewer.js -c /opt/a>
   Main PID: 3060 (code=exited, status=1/FAILURE)

Jul 26 12:28:22 ubuntu systemd[1]: arkimeviewer.service: Scheduled restart job,>
Jul 26 12:28:22 ubuntu systemd[1]: Stopped Arkime Viewer.
Jul 26 12:28:22 ubuntu systemd[1]: arkimeviewer.service: Start request repeated>
Jul 26 12:28:22 ubuntu systemd[1]: arkimeviewer.service: Failed with result 'ex>
Jul 26 12:28:22 ubuntu systemd[1]: Failed to start Arkime Viewer.
lines 1-11/11 (END)

Please advise what do I need to change in order for this to work.

**Comment by awick** [comment]
https://arkime.com/questions
