### ISSUE TITLE
SRC and DST fields are flipped on V.3.4.2 with out-of-order TCP SYN-ACK -packet when the destination host doesn't respond to the connection attempt

### ISSUE THREAD

**Issue by cilehz** [arkime/arkime#1956]
Arkime displays the SRC and DST fields incorrectly (SRC is shown as DST and vice versa) when there's a out-of-order TCP SYN-ACK -packet that doesn't get a response from the destination host. 

 
**Elasticsearch version**:
7.17.5

**Arkime/Moloch version**:
Arkime 3.4.2

**OS name and version**:
Ubuntu 20.04 LTS

**How was Arkime installed:** (rpm, deb, easybutton, ...)
arkime_3.4.2-1_amd64.deb

**Steps to reproduce**:
Configure the destination host to DROP packets to the destination port. Send a TCP SYN-ACK packet to the destination host and capture the traffic. Import the pcap to Arkime and Arkime will display the SRC and DST field incorrectly. 

Arkime:
![arkime_dst_src](https://user-images.githubusercontent.com/110565808/182879279-c20fbea8-810b-4e2e-ad9b-bb20f9a3b98f.PNG)

-------------------------------------------------------------------------------

Wireshark:
![wireshark_src_dst](https://user-images.githubusercontent.com/110565808/182879425-7f9fee40-89fb-4c8f-bec3-e860656a16da.PNG)

**Comment by awick** [comment]
please provide a sample pcap, thanks

**Comment by cilehz** [comment]
[example.zip](https://github.com/arkime/arkime/files/9261337/example.zip)

**Comment by awick** [comment]
This seems to be working correctly to me, when we see a SYN-ACK we assume we missed the SYN.  So in the above example the TCP handshake would be

80 -> 3333 SYN - missing
3333 -> 80 SYN-ACK - present
80 -> 3333 ACK - missing

So that means the TCP conversation would be 80 -> 3333

If you don't like this feature you can set antiSynDrop=false but that doesn't care if there is 1 or more packets, it will never swap them.

Feel free to reopen with more details if I'm missing something

**Comment by cilehz** [comment]
Yeah, I understand the logic behind the assumption. In normal circumstances that probably would be the right call. In retrospect I should have given more (or at least some) context to the issue :)

I noticed this when a network that I had visibility to through Arkime received TCP SYN-ACK -packets for a wide range of (valid) ip addresses and none of the hosts were responding to the out-of-state packets. Either the host or a firewall was configured to DROP the packets so the only packets that were ever seen on those TCP-connections were the out-of-state SYN-ACK -packets. 

Initially when looking at the traffic in Arkime it seemed that the hosts in my network were sending packets to the internet to seemingly random addresses which was kind of alarming. After looking at some of the pcaps in Wireshark I realized that that's not true.

I would argue that we should have more information when making educated guesses on the direction of the traffic. In this case it would be enough require either the 80 -> 3333 SYN or 80 -> 3333 ACK to be present in addition to the 3333 -> 80 SYN-ACK -packet. That would make sure that the traffic is bidirectional and we actually know the flow of the packets.

**Comment by awick** [comment]
So you are suggesting that if you are being ACK scanned you want the UI to show the reverse in the UI? I think that could be just as confusing.

In the Arkime UI for TCP we show the TCP directionality, when we can determine it. In this case we can determine it, it isn't an educated guess.

In theory we could potentially maybe show some extra info that it looks like an ACK SCAN. (either a 1 packet syn-ack or syn-ack followed by rst)
