### ISSUE TITLE
Arkime Disk Storage Optimization

### ISSUE THREAD

**Issue by lzy192251** [arkime/arkime#1960]
Hello, guys

I want to know how Arkime optimizes the storage pressure of data resources on disks.

At present, I know that the optimization of PCAP files can be deleted by Arkime, but I don't know how to set the automatic deletion of Arkime log files and Elasticsearch index deletion.

Arkime v3.4.2
ES Version 7.10.2

**Comment by awick** [comment]
https://arkime.com/questions

**Comment by lzy192251** [comment]
已经收到您的邮件，我会尽快处理。
