### ISSUE TITLE
Standard Metrics Support

### ISSUE THREAD

**Issue by mosajjal** [arkime/arkime#1998]
**Is your feature request related to a problem? Please describe.**
Currently, there's no easy way to gather capture metrics from `arkime` 

**Describe the solution you'd like**
A standard solution to either pull the metrics using an API endpoint (`prometheus` way) or push metrics to a remote server (`statsd` way). Or better yet, use something like [OpenMetrics](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md)

**Describe alternatives you've considered**
Kibana dashboards could be an option but I haven't looked into how those data are stored in internal Arkime indices

**Comment by 31453** [comment]
There is currently an endpoint to retrieve stats [here](https://arkime.com/apiv3#stats-api)
