### ISSUE TITLE
pcaps with link type 276 fails to ingest with the capture utility

### ISSUE THREAD

**Issue by StammesOpfer** [arkime/arkime#2002]
When running the capture utility either directly from the cli or using upload in the webui against a pcap I get:
`packet.c:1312 moloch_packet_batch(): Error - Unsupported pcap link type 276`

Occurs on 3.4.2 and the 2022-08-26 08:38:06 "Latest Commit"

On Ubuntu from the provided .deb

**Comment by awick** [comment]
upload just use capture, so that isn't a surprised that they are the same.

please provide a sample pcap

**Comment by StammesOpfer** [comment]
I am unable to duplicate outside of my live environment so I can not share actual pcap. I had the same error in wireshark 3.2.3 (from Ubuntu repo) but it was corrected by 3.6.5 (Wireshark ppa). If there is something I can do to help narrow it down without providing the actual pcap please let me know.

**Comment by awick** [comment]
It only needs to be a single packet pcap. You could try looking at other pcap repositories and try to find a matching one.

**Comment by StammesOpfer** [comment]
The attached pcap duplicates the error.
[test-pcap.zip](https://github.com/arkime/arkime/files/9454630/test-pcap.zip)
