### ISSUE TITLE
Periodic Queries not work

### ISSUE THREAD

**Issue by rndvip** [arkime/arkime#2011]
**Describe the bug**
"Periodic Queries" not work

**Elasticsearch version**:v 7.17.1

**Arkime/Moloch version**:v3.4.2

**OS name and version**:Ubuntu 20.04.4 LTS

**How was Arkime/Moloch built/installed:** deb

**Provide logs, stack traces and steps to reproduce**:no errors, no exception
I found session with special query (for example "ip=8.8.8.8)", copy it and paste in new "Periodic Queries". But it said Matches 0 and never satrt again, just set "Last run at" and newer chenge it.

**Comment by awick** [comment]
Would probably be easier to talk about this on slack.

Did you set cronQueries=true on 1 and only 1 viewer node?
When you created the query did you select a time frame in the past that included the previous matches or you know there are future matches?

**Comment by rndvip** [comment]
> Would probably be easier to talk about this on slack.
> 
> Did you set cronQueries=true on 1 and only 1 viewer node? When you created the query did you select a time frame in the past that included the previous matches or you know there are future matches?

>
cronQueries set to true
I have try set "Now" and "1 hour ago"

**Comment by awick** [comment]
You restarted viewer after changing cronQueries to true? You sure you have it in the right section? You can set debug=1 to check the settings after restarting viewer and to get more debugging information.

You could try upgrading to the last commit build and see if that fixes your issues. It works for me.

**Comment by rndvip** [comment]
> You restarted viewer after changing cronQueries to true? You sure you have it in the right section? You can set debug=1 to check the settings after restarting viewer and to get more debugging information.
> 
> You could try upgrading to the last commit build and see if that fixes your issues. It works for me.

Yes. I have changed cronQueries to true and restart arkimeviewer service.
I'll try to upgrade and if it not help - try debug mode.

**Comment by rndvip** [comment]
> You restarted viewer after changing cronQueries to true? You sure you have it in the right section? You can set debug=1 to check the settings after restarting viewer and to get more debugging information.
> 
> You could try upgrading to the last commit build and see if that fixes your issues. It works for me.

I have move cronQueries=true from just befor section

_# Uncomment if this node should process the cron queries and packet search jobs, only ONE node should process cron queries a>
cronQueries = true_

Directly ander [default] - and it works!

One more question: email notifery send mesage with not working url 
_periodic query match alert: *1 new* matches *8 total* matches http://webapp/sessions?expression=tags%20%3D%3D%20malware:ip_
How can i replace "webapp" with "arkime.local"

**Comment by awick** [comment]
Great
