### ISSUE TITLE
How to analyze offline pcap file suricata plugin?

### ISSUE THREAD

**Issue by ksh98** [arkime/arkime#2015]
I am using suricata as a plug-in.

Real-time traffic is well analyzed by arkime and suricata.

However, the offline pcap file is not analyzed by suricata.

I wonder how to analyze offline pacp files with suricat.

**Comment by reuteras** [comment]
You have to change suricataExpireMinutes to include the date for when the pcap is from. See https://arkime.com/settings for more information.

**Comment by ksh98** [comment]
> You have to change suricataExpireMinutes to include the date for when the pcap is from. See https://arkime.com/settings for more information.

Reuteras,

Thanks for the speedy and helpful reply.
