### ISSUE TITLE
Configure --cont3xt is not working

### ISSUE THREAD

**Issue by p4fg** [arkime/arkime#2020]
**Describe the bug**
/opt/arkime/bin/Configure --help says:

```
$ /opt/arkime/bin/Configure --help

Configure (--wise|--parliament|--cont3xt|)  = Only 1 option can be used
--cont3xt      = install and start cont3xt
--wise         = install and start wise
--parliament   = install and start parliament
               = install arkime capture and viewer
--help         = this help

```

However, running `/opt/arkime/bin/Configure --cont3xt` gives the error:

```
/opt/arkime/bin/Configure: line 75: /opt/arkime/etc/arkimecont3xt.systemd.service: No such file or directory
Failed to enable unit: Unit file arkimecont3xt.service does not exist.
Failed to start arkimecont3xt.service: Unit arkimecont3xt.service not found.
```

**Arkime/Moloch version**:
arkime (4.0.0-GIT-823012)

**OS name and version**:
Ubuntu 20.04 LTS

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb

**Comment by awick** [comment]
thanks, this was already fixed in 836327c2d09f10eca90beb11ea288ec021936d4c 

 looks like some of the builds failed last night for some reason, restarting.
