### ISSUE TITLE
ES 8.4.3 not supported

### ISSUE THREAD

**Issue by sszgr** [arkime/arkime#2027]
**Describe the bug**
ERROR - ES 8.4.3 not supported, ES 7.10.0 or later required.

**Elasticsearch version**:
8.4.3

**Arkime/Moloch version**:
3.4.2

**OS name and version**:
CentOS 7.4.1708

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm

**Provide logs, stack traces and steps to reproduce**:
https://github.com/arkime/arkime/blob/main/viewer/db.js#L219
https://github.com/arkime/arkime/blob/main/viewer/multies.js#L1065

**Comment by awick** [comment]
See https://arkime.com/faq#upgrading-arkime or https://raw.githubusercontent.com/arkime/arkime/main/CHANGELOG
