### ISSUE TITLE
Change the version of glib to fix bug!

### ISSUE THREAD

**Issue by davidguhao** [arkime/arkime#2040]
Need
![Screenshot from 2022-10-24 19-00-47](https://user-images.githubusercontent.com/34062017/197511667-57ea6ae8-a9a4-418c-b86c-0de728b0a53f.png)

to fix the problem caused by 

https://gitlab.gnome.org/GNOME/glib/-/commit/b71117d89434db83d34bc1b981ca03d4be299576

**Comment by awick** [comment]
What issue are you having?
