### ISSUE TITLE
Issues installing arkime

### ISSUE THREAD

**Issue by inky9329** [arkime/arkime#2046]
**Describe the bug**

Unable to install or start arkime.

**Elasticsearch version**:
Provided in install, latest stable.

**Arkime/Moloch version**:
latest

**OS name and version**:
Kubuntu 22.10

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

I've gotten the furthest with installing through deb. As of now, I am unable to get Arkime to start up, despite Elasticsearch being running correctly. Current error message is below:

systemctl start arkimecapture.service

Failed to start arkimecapture.service: Unit arkimecapture.service is masked.

**Comment by pluszerodadada** [comment]
Have you solved the problem yet ？how do you solve this problem

**Comment by pluszerodadada** [comment]
Why does this cause this problem
