### ISSUE TITLE
I can't start arkimecapture.service

### ISSUE THREAD

**Issue by Mrchengzhenhua** [arkime/arkime#2059]
error like this:
my system is ubuntu2004, I follow all the instructions to install the arkime4.0.2, but i can't start the arkimecapture and arkimeview servieces 

systemctl start arkimecapture.service
Failed to start arkimecapture.service: Unit arkimecapture.service is masked.

systemctl start arkimeviewer.service
Failed to start arkimeviewer.service: Unit arkimeviewer.service is masked.

is anybody know what's wrong??

**Comment by awick** [comment]
I think you might have installed 4.0.1, please try installing 4.0.2 again which will fix the empty files.

You may need to do a 'systemctl daemon-reload'
