### ISSUE TITLE
VNI extraction for VXLAN packets

### ISSUE THREAD

**Issue by Obsecurus** [arkime/arkime#2062]
**Is your feature request related to a problem? Please describe.**
Many packet-forwarding technologies use VXLAN for forwarding packets to a collection point. It would be extremely useful to be able to query by the VNI as this could provide insight as to the origin of the packets. Arkime supports the --op flags and -t to add custom fields at the point of capture. However, it may be unsustainable to create N copies of Arkime from a resource perspective. If the VNI number was available in Arkime, this would provide a 24bit key space (16.7 million) to uniquely identify the origin. 

**Describe the solution you'd like**
VNI extraction from vxlan protocol and storage in the session index w/ query support in the UI. Additionally, it would be awesome if WISE could enrich off of VNI as it currently only supports IP, Domain, email, and MD5. I suppose you could generate an MD5 of the VNI as a hack but not sure if you can generate MD5 on an arbitrary field in WISE.  

**Describe alternatives you've considered**
I considered using N copies of Arkime per each VXLAN however, this would result in 1,000's of Arkime capture engines running and a significant waste of resources. 

**Additional context**

**Comment by Obsecurus** [comment]
Apologies if there is something else that enables this. At a very high level, the core problem is that packet mirroring and packet capture could be performed in two different places. It would be nice to somehow inject an identifier into the packets that could be used and extracted for grouping. VXLAN just seemed like the natural choice for this but I suppose there are several others.

**Comment by Obsecurus** [comment]
Actually, it looks like someone pointed this out here as well. https://github.com/arkime/arkime/issues/1676 I may look into a GRE approach instead for now.

**Comment by Obsecurus** [comment]
Also given that GRE's unique ID would be an IP in this case, I also think this would work out of the box with WISE for a metadata enrichment source. It still may be useful to have vxlan VNI for others. However, I'm going to investigate using a GRE-based strategy now.

**Comment by Obsecurus** [comment]
Digging further again I see that encapsulated MACs are merged for all the forwarding protocols. I think this should also work for my needs and like others: https://github.com/arkime/arkime/pull/1889

**Comment by awick** [comment]
You can add any field to wise these days, so should already work.

Are you saying you are happy with one vni kind of like vlan, or do we have to worry about inside/outside ones?

**Comment by Obsecurus** [comment]
Yeah I think the single VNI like with vlan would be perfect, although I could see how some might want the inside/outside. The existing vxlan.pcap should be fine.

**Comment by Obsecurus** [comment]
Per that PCAP I would expect to see VNI: 123 in the index somewhere. 

![Screen Shot 2022-12-12 at 3 37 40 PM](https://user-images.githubusercontent.com/30487781/207149396-d28f2037-4d8a-4159-b9f5-4eac67bd11b2.png)
