### ISSUE TITLE
Arkime dependency problem: libyara8

### ISSUE THREAD

**Issue by m1ketheone** [arkime/arkime#2072]
**Describe the bug**
while installing arkime, I got the following problem:
```
dpkg: dependency problems prevent configuration of arkime:
arkime depends on libyara8; however:
Package libyara8 is not installed.
```
The only libyaraI can install is libyara9

**Comment by awick** [comment]
It would be really helpful if you fill out the bug template which asked for OS and Arkime version and what you installed

**Comment by m1ketheone** [comment]
**Arkime/Moloch version**:
arkime_4.0.2-1_amd64.deb 
**OS name and version**:
NAME="Kali GNU/Linux"
VERSION="2022.4"

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb
**Provide logs, stack traces and steps to reproduce**:
```
# dpkg -i arkime_4.0.2-1_amd64.deb
(Reading database ... 382616 files and directories currently installed.)
Preparing to unpack arkime_4.0.2-1_amd64.deb ...
Unpacking arkime (4.0.2-1)...
dpkg: dependency problems prevent configuration of arkime:
 arkime depends on libyara8; however:
  Package libyara8 is not installed.

**Comment by awick** [comment]
Sorry I don't know anything about Kali and their compatibility with Ubuntu. Looks like Ubuntu 22.04 still has libyara8
