### ISSUE TITLE
arkimecapture.service and arkimeviewer.service failing, neither run at the same time

### ISSUE THREAD

**Issue by asparagus0810** [arkime/arkime#2093]
**Describe the bug**

When I run the Configure script, I install elasticsearch locally for demo. It runs without issue. However, when using systemctl start arkimecapture.service or arkimeviewer.service, neither will run at the same time. Both are loaded, but one fails. Restarting one service causes the other to fail. They flip flop back and forth. I can access the web gui, but the capture service won't run, and I can't ingest any data. I'm running this in an Ubuntu VM on ESXI. 

**Elasticsearch version**:
Install from elasticsearch-oss-7.10.2-amd64.deb

**Arkime/Moloch version**:

arkime 4.0.3

**OS name and version**:

Ubuntu 22.0.4

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

Using deb package from arkime downloads for ubuntu 22.0.4

**Provide logs, stack traces and steps to reproduce**:

root@arkime-virtual-machine:/opt/arkime/bin# systemctl | grep arkime
  session-2.scope                                                                                  loaded active running   Session 2 of User arkime
● arkimecapture.service                                                                            loaded failed failed    Arkime Capture
  arkimeviewer.service                                                                             loaded active running   Arkime Viewer
root@arkime-virtual-machine:/opt/arkime/bin# systemctl restart arkimecapture.service
root@arkime-virtual-machine:/opt/arkime/bin# systemctl | grep arkime
  session-2.scope                                                                                  loaded active     running         Session 2 of User arkime
  arkimecapture.service                                                                            loaded activating start-pre start Arkime Capture
  arkimeviewer.service                                                                             loaded active     running         Arkime Viewer
root@arkime-virtual-machine:/opt/arkime/bin# systemctl | grep arkime
  session-2.scope                                                                                  loaded active running   Session 2 of User arkime
● arkimecapture.service                                                                            loaded failed failed    Arkime Capture
  arkimeviewer.service                                                                             loaded active running   Arkime Viewer
root@arkime-virtual-machine:/opt/arkime/bin#

**Comment by awick** [comment]
I would guess you have a config error, please check the log files (https://arkime.com/faq#arkime-is-not-working) if not the case please reopen with more information.
