### ISSUE TITLE
Bulk Cont3xt Search

### ISSUE THREAD

**Issue by 31453** [arkime/arkime#2121]
Bulk search for multiple indicators. Indicators can be of different types.

- [x] Display multiple cards/tabs that are collapsible. 
- [x] Links get displayed based on the "active" indicator currently selected by the user.
- [x] There may be MANY indicators, so there should be a way to push items to the top/bottom by determining relevance/severity.
- [x] Put them into logical OR arrays and assign to variables like {arrayIps}, ${arrayEmail} for use in Cont3xt link groups for queries to Splunk or Arkime, etc.. #2380
- [x] Include information on the indicator results that there is something bad or that it has been whitelisted

**Comment by 31453** [comment]
Possible limit to the number of indicators (100)?
Search for all at once, progressive loading is already implemented but we may need to improve queuing.
Maybe some warning/flag to have the user check their enabled integrations.
Allow comma or newline separated list of indicators.
New endpoint or change endpoint that can separate the indicators.

**UI notes**:
Condensed/summary view that turns into the normal view when clicking on a specific indicator result.
You can navigate back to summary view, then to another indicator result.
Ability to scroll through all indicators.
Some top level tidbits for indicators.

**Comment by 31453** [comment]
@WilliamSalusky Question for the logical OR arrays: Would you want these to be only the indicators that you searched or any results expanded and returned? 

For example: If you searched for `10.0.0.1, example.com, 10.0.0.2` and example.com expanded  to include an IP of 10.0.0.3. Would you want the `${arrayIp}` to be `10.0.0.1, 10.0.0.2` or `10.0.0.1, 10.0.0.2, 10.0.0.3`?

**Comment by 31453** [comment]
Here's a possible solution that implements the latter option described above ☝️ #2380

**Comment by WilliamSalusky** [comment]
I initially submitted this thinking that only the top level indicators as queried would be used to construct the per iType arrays, but if you are saying that an all inclusive list that includes children is easier, I'm happy to see child indicators included. I call that a bonus! 

And if that is the case, a future option already discussed that would disable generating child indicators would resolve that if it caused an issue for any user.


Taking this a bit further, the logical OR array for splunk could be extended to benefit other queryable destinations [i.e. Elastic/OpenSearch, Greylog, etc] through the support of multiple array formats.

```
${double_quoted_OR_arrayIp} = "10.0.0.1" OR "10.0.0.2" OR "10.0.0.3" ;# literal 'OR' separators
${double_quoted_csv_arrayIp} = "10.0.0.1", "10.0.0.2", "10.0.0.3"
${single_quoted_csv_arrayIp} = '10.0.0.1', '10.0.0.2', '10.0.0.3'
${csv_arrayIp} = 10.0.0.1, 10.0.0.2, 10.0.0.3
```

**Comment by WilliamSalusky** [comment]
I just realized there is one other fairly common format I would use

```
${pipe_sep_arrayIp} = 10.0.0.1|10.0.02|10.0.0.3
```

**Comment by 31453** [comment]
@WilliamSalusky I went with a totally different paradigm. Now you can define the array using JSON! Like this: 
- `${array,{iType:"ip"}}` = 10.0.0.1,10.0.0.2,10.0.0.3
- `${array,{iType:"ip",include:"top",sep:" OR ",quote:"\""}}` = "10.0.0.1" OR "10.0.0.2"
- `${array,{iType:"domain",include:"all",sep:"|",quote:"'"}}` = 'example.com'|'test.org'|'arkime.com'

Options include:
- `iType`* Which iType values to include in the array. REQUIRED (ip, domain, url, email, hash, phone, text)
- `include` "all" or "top". "all" = all values of the specified iType. "top" = top level values of the specified iType. Defaults to "all"
- `sep` Separator between values. Defaults to comma (",")
- `quote` Quote character to wrap values. Defaults to none ("")

Caveats:
- Do not include spaces in your array options.
- Escape double quotes with a backslash \"
- Escape backslashes with a backslash \\
- If the JSON cannot be parsed, the placeholder is removed from the link

Let me know what you think!
