### ISSUE TITLE
API Usage Stats

### ISSUE THREAD

**Issue by 31453** [arkime/arkime#2135]
Add a stats page tab that provides a current snapshot of API usage from sources that have defined limits. (i.e. Spur, VirusTotal, urlscan, PassiveTotal, etc...). Or add columns to the indicator stats tab.

**Comment by 31453** [comment]
Where would we get these defined limits? User input?

**Comment by WilliamSalusky** [comment]
An administrative user [like myself] should be able to define them in settings. Using "Censys" as an example, each subscription tier will have different high water mark limits for total number of monthly API queries, in addition to a rate limit for queries per second.

**Comment by awick** [comment]
Since each user brings their own account for each service wouldn't it be on each user to set their limit?
Or is the thought that even though they have their own accounts they would all be at the same subscription level?

**Comment by WilliamSalusky** [comment]
Good point. Some user accounts can have different rate limits if they are not authorized from a single enterprise/corp/pro tier subscription service. For now, I think we start with a single administratively configured rate limit that will cover most cases. I'll start grabbing the endpoints per service that return service utilization statistics.
