### ISSUE TITLE
Http Proxy option for downloading dependencies in the installer script

### ISSUE THREAD

**Issue by ali-foroughi** [arkime/arkime#2145]
**Is your feature request related to a problem? Please describe.**

Installing dependencies with the  [easybutton-build.sh](https://github.com/arkime/arkime/blob/main/easybutton-build.sh) requires  internet connection. 

**Describe the solution you'd like**

The script should ask or check for a http_proxy environment variable  before starting download so the dependencies can be installed on air-gapped system. 

**Describe alternatives you've considered**
None

**Additional context**

**Comment by awick** [comment]
I think all the commands there should already support the http_proxy and https_proxy vars, so if you set both it should already work. Can you share what doesn't?

Since this is for building, and not installing, and we already provide prebuilt packages I'm probably going to close this issue.

**Comment by awick** [comment]
Closing. Feel free to open if you have new details.
