### ISSUE TITLE
Molochcapture fails to start in Cape Sandbox

### ISSUE THREAD

**Issue by MU-03** [arkime/arkime#2152]
**Describe the bug**
I am using molochcapture and molochviewer in cape sandbox , whenever I enable these both services and check the status after a while I get "Failed to start molochcapture" Although my cape sandbox analysis is working adequately.

**Elasticsearch version**:
7.17.5
**Arkime/Moloch version**:
2.7.1
**OS name and version**:
Ubuntu 20.04.4 LTS MATE 1.24.0

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton,
![01](https://user-images.githubusercontent.com/118333194/213627483-ce7213c1-a3b9-4c22-9412-dbeff6c01134.PNG)
 ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
https://arkime.com/questions
