### ISSUE TITLE
Cont3xt - Identify punycode encoded international domain names in search input

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#2155]
At indicator extraction time check for punycode encoded domain names that start with plain ascii `xn--`, and classify the iType as DOMAIN for API integration processing. Please display the utf-8 decoded result in parens next to the punycode domain in the indicator result tree.

example:
```
DOMAIN: xn--yho-ela6g.com  (yáhoó.com)
```

Integrations should be processed with the original punycode encoded domain name when gathering results.

**Comment by WilliamSalusky** [comment]
https://github.com/gchq/CyberChef/blob/a3b873fd96111fe2dbcb62a1e037987669290a13/src/core/operations/FromPunycode.mjs

**Comment by awick** [comment]
There is a standard punycode.js module that we will use, just need to work with Elyse sometime
