### ISSUE TITLE
Add ES tabs to cont3xt -> stats panel 

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#2174]
Add at least a subset of ElasticSearch/OpenSearch admin related tabs to cont3xt -> stats panel similar to what is accessible by admins of Arkime -> stats. This will help those of us running a standalone cont3xt instance.

```
ES Nodes
ES Indices
ES Tasks
ES Shards
ES Recovery
ES Admin
```

**Comment by awick** [comment]
If you are running cont3xt standalone you don't really need these since cont3xt uses so few ES resources. I'm not even sure ES would be the right thing to use in a standalone deployment, but need to think about it. I would use the lmdb database option.
