### ISSUE TITLE
CSV-Export do not contain Start or Stop Times

### ISSUE THREAD

**Issue by Avedena** [arkime/arkime#2183]
**Describe the bug**
If you select "Export to CSV" and change the fields to ```source.as.organization.name,source.ip,source.port,starttime,stoptime``` the output in the generated csv-file is empty. The field headers are also missing:
```csv
Src ASN Name, Src IP, Src Port
Google,8.8.8.8,53,,
```
**Elasticsearch version**:
8.6.1
**Arkime/Moloch version**:
4.1.0
**OS name and version**:
ElasticSearch Server: Linux elasticsearch 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux
Arkime: Linux arkime 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb
**Provide logs, stack traces and steps to reproduce**:
1. Filter for some Sessions ```ip.protocol != icmp && ip.protocol != icmp6 && ip == 8.8.8.8```
2. click on the upper right action menu  ```class="btn dropdown-toggle btn-theme-primary btn-sm"```
3. click on "Export CSV" ```role="menuitem" class="fa fa-fw fa-file-excel-o```
4. click on "Change Fields" ``` class="btn btn-sm btn-theme-secondary"```
5. Paste the following string: ```source.as.organization.name,source.ip,source.port,starttime,stoptime```
6. Press Enter
7. Open the CSV

**Comment by awick** [comment]
Must use the db fields, see the default values or help page. Please use slack for questions in the future.
