### ISSUE TITLE
Can't use OIDC auth on WISE's config page

### ISSUE THREAD

**Issue by Didr** [arkime/arkime#2196]
**Describe the bug**
It seems that OIDC authentication (using webconfig) is a little bit tricky with WISE after fixing #2195. If you're not logged in, you are supposed to be redirected to the login portal for your OIDC provider. 
Currently visiting the `/config` page reports a CSP error and the redirect is blocked. 
I'm using Keycloak, and the same setup works fine on cont3xt and viewer.

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://keycloak.test.lan:8443/realms/master/protocol/openid-connect/auth?client_id=arkimewise&scope=openid&response_type=code&redirect_uri=https%3A%2F%2Farkime-tap-01.test.lan%3A8081%2Farkime%2Fauth%2Flogin%2Fcallback&state=-y-JnE5Te30RLzjs4IdaMbONWeHf0zUmgX5C6n4c6jY&session=true&successRedirect=%2F&failureRedirect=%2Ffail&code_challenge=pN95KPrMMPG_mfNArJ8MrqqDhKWRuzKHK706jg9BrIk&code_challenge_method=S256 (“default-src”).
```

As far as I can tell this happens because `/config` in itself does not require authentication, but loads some JSON from the `/config/get` API which does. If you're not authenticated the request to `/config/get` gets redirected to your OIDC provider. 
My guess is that since it's only redirecting the JSON request and not the "primary page" you're visiting this error happens, but I'm not sure.

**Comment by Didr** [comment]
Browsing directly to `/config/get` makes you authenticate successfully, and `/config` works after that.

**Comment by awick** [comment]
Ok will need to get @31453 help updating the CSP, since WISE is a SPA clicking on config doesn't actually launch another page
