### ISSUE TITLE
Arkime log timing does not match OS timezone

### ISSUE THREAD

**Issue by Mechaniquake** [arkime/arkime#2204]
**Is your feature request related to a problem? Please describe.**
It seems like the logged time for events are ahead by an hour, does Arkime calculate daylight savings?

**Describe the solution you'd like**
A manual way to adjust the current time.

**Comment by awick** [comment]
Depends what you mean
* for session time in ES it uses epoc time
* for viewer.log/capture.log it uses the timezone of the computer its running on, so make sure TZ is set
* for the UI it uses the timezone of your browser

We won't be adding a way to adjust the current time. Feel free to come to slack to discuss more.
