### ISSUE TITLE
Add easybutton support for Kali Purple

### ISSUE THREAD

**Issue by IdrisBouar** [arkime/arkime#2234]
**Describe the bug**
An error accured during the installation of arkime (Logs bellow)

**Elasticsearch version**:

**Arkime/Moloch version**:
Arkime latest commit from Github

**OS name and version**:
Kali Purple 2023-03-22 Linux 6.1.0-kali7-amd64

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
Build Error
Logs below

**Provide logs, stack traces and steps to reproduce**:
```
In the file included !
```
[ArkimeLog.txt](https://github.com/arkime/arkime/files/11190738/ArkimeLog.txt)

**Comment by awick** [comment]
I thought Kali Purple already includes Arkime?

If you want to build Arkime on an unsupported platform, you'll have to use configure directly.

**Comment by IdrisBouar** [comment]
@awick, it must be installed from the package manager.
But, i don't seem to find any documentations on how to run or how it works when installed through it !

**Comment by awick** [comment]
Ya I haven't tried out Kali Purple yet, so not sure how they have Arkime configured. On my list of things to do.

**Comment by IdrisBouar** [comment]
@awick I have found the commands for arkime in Kali Purple:

arkime-first-setup
arkime-start
arkime-stop

Thank you !
