### ISSUE TITLE
Cont3xt - Long individual tag length causes integration icons to render off screen/panel

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#2237]
When an individual tag returned from ThreatStream is long (>100 chars), the indicator result icons render off screen with no easy way to access the results and view card detail in UI. In this specific case, the tag is 238 characters long.

I can provide specific example indicators via DM due to sensitivity.

Suggestion: Limit individual tag entries to 100 characters, maybe even making this limit a per user configurable option.

Full tag detail will remain visible from the raw / card detail display.

**Comment by 31453** [comment]
This is mostly fixed. We just need to add the tag details on the Threatstream card.
