### ISSUE TITLE
Cont3xt - Integrations/Views - add option to prevent processing remote integrations against IP sub iTypes after DNS resolution of Domain iType

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#2244]
* Problem:
An analyst [like myself] may often want to process domains that will include full DNS resolution results but may NOT want to process every remote API integration against A or AAAA records returned in DNS results. Local processing of maxmind for ASN detail, or cache checking for recent historic results should always be acceptable.

* Solution?
An interim workable solution can be accomplished through an integration / view checkbox of 'no IP children' that is paired under the `DNS` option that will prevent remote API integrations from being processed on child IP iTypes after Domain iType DNS resolution.

* Future:
I understand that this will complicate integration and view management, but I plan to write additional requirements around a more advanced View management interface that will allow integration selections to be made specific to iType processing.

**Comment by awick** [comment]
I think we should add a [Skip Children] menu option like we have [Skip Cache]
