### ISSUE TITLE
Cannot configure `trust proxy` for secure cookies with OIDC authentication when using a proxy

### ISSUE THREAD

**Issue by bburky** [arkime/arkime#2245]
**Describe the bug**
Arkime's new OIDC authentication (https://github.com/arkime/arkime/pull/2157) uses "secure" HTTPS cookies:
https://github.com/arkime/arkime/blob/main/common/auth.js#L183

request-session requires the connection to be secure (HTTPS) or it will not actually set secure cookies: https://github.com/expressjs/session#cookiesecure
> However, it requires an https-enabled website, i.e., HTTPS is necessary for secure cookies. If `secure` is set, and you access your site over HTTP, the cookie will not be set. If you have your node.js behind a proxy and are using `secure: true`, you need to set "trust proxy" in express

Arkime does not currently provide a way to configure Express's `trust proxy` setting. If Arkime is behind proxy it may incorrectly misdetect connections as HTTP and skip setting cookies during the redirect to IdP. This causes sessions to not work and login with OIDC is not possible.

If Arkime is modified to `app.set("trust proxy", true)` and the proxy passes `x-forwarded-proto: https`, secure cookies will work and the session will be created.

**Elasticsearch version**:
8.6.0

**Arkime/Moloch version**:
v4.2.0

**OS name and version**:
Ubuntu 22.04.2 LTS

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
https://s3.amazonaws.com/files.molo.ch/builds/ubuntu-20.04/arkime_4.2.0-1_amd64.deb

**Provide logs, stack traces and steps to reproduce**:
If you set the `DEBUG=express-session` environment variable you will see the error `express-session not secured`:
```
Thu, 20 Apr 2023 19:16:12 GMT express-session no SID sent, generating session
Thu, 20 Apr 2023 19:16:15 GMT express-session saving 80xopvO2sqLc3ooJKpjPu6ry6RAsnNUS
Thu, 20 Apr 2023 19:16:15 GMT express-session not secured
Thu, 20 Apr 2023 19:16:15 GMT - GET / 302 0 bytes 5192.945 ms
```

After the redirect back from the IdP to Arkime, the user will get [the following error message](https://github.com/arkime/arkime/blob/main/common/auth.js#L567):
```js
{"success":false,"text":{}}
```

(An unrelated bug is that Arkime is attempting to `JSON.stringify()` an `Error` object here which is not possible, `{}` is returned.)

After some debugging, the exact error is:
```
Error: did not find expected authorization request details in session, req.session["oidc:keycloak.example.com"] is undefined
```

**Solution**
Can an option to configure the Express's `trust proxy` setting be added to Arkime? I manually tested `app.set("trust proxy", true)` and the issue was resolved for me. The proxy must also set `x-forwarded-proto: https`.

There's a minor issue that this setting can be any of: `false`, `true` (trust left most proxy) , a number (count of proxy hops), a string array (of ip addresses/subnets), or a JS function. Maybe a JSON configuration option is appropriate, which would support anything but a custom JS function?
https://expressjs.com/en/guide/behind-proxies.html

**Comment by bburky** [comment]
I could try a PR to fix this if you think this proposed fix is good (one PR unless you want these split):
* Add an JSON-formatted Arkime configuration setting to configure Express `trust proxy`
* Fix [this error message](https://github.com/arkime/arkime/blob/main/common/auth.js#L567) to call `err.toString()`.

**Comment by awick** [comment]
So the issue is you do https to proxy but http from proxy to arkime? Is another solution just to use https both places?

Anyway having trust proxy always true is a security issue for those not using a proxy, so it would need to be an option.

**Comment by bburky** [comment]
Yes, HTTP on the last hop to Arkime. HTTPS terminates at a reverse proxy, I would like to avoid putting certificates on the Arkime server.

**Comment by awick** [comment]
So we are trying to move away from supporting http, especially for auth, in a production setting. We consider if you are using oidc to be a production setting. Can you share why you don't want to use https to the viewer app?

Another easier solution might be to just do oidc in your reverse proxy.

**Comment by bburky** [comment]
The actual situation is that we're trying to run inside Kubernetes with an Istio service mesh. HTTPS terminates at a gateway somewhere (likely different machine) and mTLS from there to a "sidecar" reverse proxy local to the container running Arkime, finally the sidecar has an HTTP reverse proxy to the container. It's actually HTTP only on localhost, not over the network.

OIDC at the sidecar is quite doable, I've done it before for similar use cases. I could extract the username and pass it to Arkime via a header. It gets difficult if the OIDC proxy needs to know too much about how users work in the application (Arkime) though. For example, performing OIDC inside Arkime allows the full JWT's data to be accessible and used with `userAutoCreateTmpl` without passing in tons of separate headers.

**Comment by awick** [comment]
Ok thanks, ya the solution of a new variable might make the most sense in this case.
