### ISSUE TITLE
unable to install Akime on RHEL 7.9

### ISSUE THREAD

**Issue by TBCPNUMNAGS777** [arkime/arkime#2246]
**Describe the bug**
I am unable to install Arkime on my RHEL 7.9 VM. I was having issues with installing the libyans-devel but I eventually got past this issue. I then checked rpm -Kv arkime-4.2.0-1.x86_64.rpm command and saw that the MD5 was NOT OK. I downloaded a new file directly from the site and replaced it on my VM and when I ran the same rpm -Kv command an error message displayed saying that it was not an rpm file. I tried multiple times and same result. I am not sure what to do at this point. I must add that my RHEL 7.9 VM is FIPS enabled. I was thinking about converting the file to an .iso file and adding it to my VM to install but I couldn't find any instructions on how to complete the install using an iso file and wasn't sure if this is possible. But I'm running into so many dead ends.
 
**Elasticsearch version**:

**Arkime/Moloch version**: 4.2.0-1.x86_64

**OS name and version**:RHEL 7.9

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...) Built/Installed using rpm, but due to the recent hiccups I am looking to try to convert to an .iso file and install using .iso but I am unsure if this will work.

**Provide logs, stack traces and steps to reproduce**:

**Comment by awick** [comment]
please provide the FULL:
* version of RHEL (many versions of 7.9)
* URL of download (also you can just type yum install <url>)
* output of commands

**Comment by TBCPNUMNAGS777** [comment]
- version:  Red Hat Enterprise Linux Server release 7.9 (Maipo)
-
https://s3.amazonaws.com/files.molo.ch/builds/centos-7/arkime-4.0.3-1.x86_64.rpm
- sudo curl --insecure -L -o arkime-4.2.0-1.x86_64.rpm '
https://drive.google.com/uc?export=download&id=1L5t7nystjjqAgSqMu7oLStB-i0KgSDnh
'
- sudo curl --insecure -L -o arkime-4.0.3-1.x86_64.rpm '
https://drive.google.com/uc?export=download&id=18ejwwAMVrqrORUeOsSg_1GVJhTohv-80
'

I initially tried with Arkime version 4.2.0 and now I am trying with Arkime
4.0.3 and I'm getting the same error when trying to verify rpm contents via
command rpm -Kv ~/arkime_rpm/arkime-4.2.0-1.x86_64.rpm, I get the
following error message saying:
/home/aadmin/arkime_rpm/arkime-4.2.0-1.x86_64.rpm: not an rpm package

Please keep in mind I downloaded it directly from the Arkime site

4.0.3:
https://s3.amazonaws.com/files.molo.ch/builds/centos-7/arkime-4.0.3-1.x86_64.rpm
4.2.0:
https://s3.amazonaws.com/files.molo.ch/builds/centos-7/arkime-4.2.0-1.x86_64.rpm


I also attached an error message screenshot for your perusal.

Very Respectfully,

Peter C. Nwaozor

**Comment by awick** [comment]
`uname -r` will print out the version of the OS you are using.

Did you try `yum install https://s3.amazonaws.com/files.molo.ch/builds/centos-7/arkime-4.2.0-1.x86_64.rpm`

**Comment by TBCPNUMNAGS777** [comment]
So i tried the command you suggested and received an erro message saying:
Cannot open:
https://s3.amazonaws.com/files.molo.ch/builds/centos-7/arkime-4.2.0-1.x86_64.rpm
 Skipping
Error: Nothing to do.


Very Respectfully,

Peter C. Nwaozor

**Comment by TBCPNUMNAGS777** [comment]
Not sure if I should mention that "This system is not registered with an
entitlement server. You can use subscription-manager to register"

This message was displayed in conjunction with the previous message I sent
to you.

Very Respectfully,

Peter C. Nwaozor

**Comment by awick** [comment]
Could you come to slack, this would be much easier.

When you provide errors and output it would be useful if you provide the full command that is used.

Please provide the output of `cat /etc/redhat-release`

The command you need to run is `yum install https://s3.amazonaws.com/files.molo.ch/builds/centos-7/arkime-4.2.0-1.x86_64.rpm` it looks like you might have run a command with a return in it or something.

**Comment by TBCPNUMNAGS777** [comment]
The response I got was: Red Hat Enterprise Linux Server release 7.9 (Maipo)

**Comment by TBCPNUMNAGS777** [comment]
I am unable to provide attachments or copy and paste due to our group policy. Please standby

**Comment by awick** [comment]
Ok, well I'm not really able to help you without the output of commands. The rpm is not corrupt, I installed with no issues. I suggest either using yum install or wget instead of curl.

**Comment by TBCPNUMNAGS777** [comment]
So i tried the command and got the response:

This system is not registered with an entitlement server. You can use subscription-manager to register.
Cannot Open: (https://s3.amazonaws.com/files.molo.ch/builds/centos-7/arkime-4.2.0-1.x86_64.rpm) Skipping.
Error: Nothing to do

**Comment by awick** [comment]
so if you wget the url and then do `yum install arkime-4.2.0-1.x86_64.rpm` what is the error?
Is there anyway you can use slack?

**Comment by TBCPNUMNAGS777** [comment]
I can get into slack here, yes.. I am logged in..

**Comment by TBCPNUMNAGS777** [comment]
when I use the wget command, the error I am getting:

This system is not registered with an entitlement server. You can use subscription-manager to register.
Cannot Open: arkime-4.2.0-1.x86_64.rpm) Skipping.
Error: Nothing to do

**Comment by awick** [comment]
Send a message on #questions

**Comment by awick** [comment]
after doing wget what happens if you do a `ls -l arkime-4.2.0-1.x86_64.rpm`

**Comment by awick** [comment]
Incase I was unclear, you need to join OUR slack :) https://slackinvite.arkime.com/

**Comment by TBCPNUMNAGS777** [comment]
Please standby. So many group ploicy restrictions..

**Comment by TBCPNUMNAGS777** [comment]
less arkime4.1.0-1.x86_64.rpm

See attached.

Very Respectfully,

Peter C. Nwaozor

**Comment by awick** [comment]
There is no file attached. At this point I think the issue is you can't get a clean download of arkime.
