### ISSUE TITLE
/opt/arkime/bin/Configure not compatible with Arch Linux

### ISSUE THREAD

**Issue by D3vil0p3r** [arkime/arkime#2247]
**Describe the bug**
I downloaded Arkime Arch Linux package by the [official website](https://s3.amazonaws.com/files.molo.ch/builds/arch/arkime-4.2.0-1_arch.x86_64.pkg.tar.zst).

After the install by pacman, when I run `/opt/arkime/bin/Configure`, and it needs to install ElasticSearch, it will download `.deb` file that is not compatible with Arch Linux environment, instead of retrieving ElasticSearch package from [AUR](https://aur.archlinux.org/packages/elasticsearch).

Furthermore, when it asks for downloading GEO files, I get the following error:
```
Download GEO files? You'll need a MaxMind account https://arkime.com/faq#maxmind (yes or no) [yes] 
Arkime - Downloading GEO files
2023-04-22 23:06:15 URL:https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv [23331/23331] -> "/tmp/tmp.SP67DOUqWu" [1]
2023-04-22 23:06:15 URL:https://raw.githubusercontent.com/wireshark/wireshark/master/manuf [2120911/2120911] -> "/tmp/tmp.oePQ93VrMS" [1]
error loading configuration file /etc/GeoIP.conf: invalid account ID format: strconv.Atoi: parsing "YOUR_ACCOUNT_ID_HERE": invalid syntax
chmod: cannot access '/usr/share/GeoIP/*.mmdb': No such file or directory
chmod: cannot access '/var/lib/GeoIP/*.mmdb': No such file or directory
```
but I guess that here I need to register an account.

I would like also to ask if the PKGBUILD file used for creating the `.zst` package is available to be read.

Thank you

**Comment by awick** [comment]
> **Describe the bug** I downloaded Arkime Arch Linux package by the [official website](https://s3.amazonaws.com/files.molo.ch/builds/arch/arkime-4.2.0-1_arch.x86_64.pkg.tar.zst).
> 
> After the install by pacman, when I run `/opt/arkime/bin/Configure`, and it needs to install ElasticSearch, it will download `.deb` file that is not compatible with Arch Linux environment, instead of retrieving ElasticSearch package from [AUR](https://aur.archlinux.org/packages/elasticsearch).

You'll need to just install yourself, I'll change Configure to not ask on arch

> 
> Furthermore, when it asks for downloading GEO files, I get the following error:
> 
> ```
> Download GEO files? You'll need a MaxMind account https://arkime.com/faq#maxmind (yes or no) [yes] 
> Arkime - Downloading GEO files
> 2023-04-22 23:06:15 URL:https://www.iana.org/assignments/ipv4-address-space/ipv4-address-space.csv [23331/23331] -> "/tmp/tmp.SP67DOUqWu" [1]
> 2023-04-22 23:06:15 URL:https://raw.githubusercontent.com/wireshark/wireshark/master/manuf [2120911/2120911] -> "/tmp/tmp.oePQ93VrMS" [1]
> error loading configuration file /etc/GeoIP.conf: invalid account ID format: strconv.Atoi: parsing "YOUR_ACCOUNT_ID_HERE": invalid syntax
> chmod: cannot access '/usr/share/GeoIP/*.mmdb': No such file or directory
> chmod: cannot access '/var/lib/GeoIP/*.mmdb': No such file or directory
> ```
> 
> but I guess that here I need to register an account.

Yep see the message it prints out.

> 
> I would like also to ask if the PKGBUILD file used for creating the `.zst` package is available to be read.

Not sure what you are asking for, you can see the build in screwdriver.yaml file and the build container in release/buildArch/Dockerfile

**Comment by D3vil0p3r** [comment]
> Not sure what you are asking for, you can see the build in screwdriver.yaml file and the build container in release/buildArch/Dockerfile

Usually Arch Linux packages are created by using [PKGBUILD](https://wiki.archlinux.org/title/PKGBUILD) but I see that `screwdriver.yaml` has the following content that seems to generate the Arch package for Arkine:
```
 export ARKIME_VERSION=`sed 's/.*"\(.*\)\".*$/\1/' /opt/arkime/common/version.js | head -n 1`
 /root/.local/share/gem/ruby/3.0.0/bin/fpm -s dir -t pacman -n arkime -x opt/arkime/logs -x opt/arkime/raw -v $ARKIME_VERSION --iteration $SD_BUILD_ID --template-scripts --after-install "release/afterinstall.sh" --url "https://arkime.com" --description "Arkime Full Packet System" -d libmaxminddb -d libpcap -d yara -d perl-http-message -d perl-lwp-protocol-https -d perl-json -d libnet -d lua -d zstd -d openssl-1.1 -d pcre /opt/arkime
```

> You'll need to just install yourself, I'll change Configure to not ask on arch

Why "to not ask on arch"? Could not be better that Configure detects the OS and based on that run the correct command for installing ElasticSearch? If not, a message during the configuration could be good too.

**Comment by awick** [comment]
> Why "to not ask on arch"? Could not be better that Configure detects the OS and based on that run the correct command for installing ElasticSearch? If not, a message during the configuration could be good too.

No because in general we don't want folks to run elastic on the same machine, plus the Configure script is probably going away, there isn't much reason to use it anymore.
