### ISSUE TITLE
Unable to index same headers in HTTP response and request

### ISSUE THREAD

**Issue by mcgillowen** [arkime/arkime#2259]
**Describe the bug**

In the sample config.ini file the 2 sections `[headers-http-request]` and `[headers-http-response]` both have the header `content-type` listed but only the request header is indexed since they both would have the same `_id` field (`expression` in the source code) in the `fields` index document, `http.content-type`. They have different aliases but since ES uses `_id` field as unique key, only the first request to create a document will be accepted.

A possible solution could possibly be to switch the `expBase` and `aliasBase` values around on the lines 1041-1042 in the file `capture/parsers/http.c`

**Elasticsearch version**:

7.17.1

**Arkime/Moloch version**:

v4.2.0

**OS name and version**:

Ubuntu 20.04

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

easybutton script

**Provide logs, stack traces and steps to reproduce**:

Use the `config.ini.sample` configuration file in the releases folder and then check the `fields` index in ES

**Comment by mcgillowen** [comment]
Ok, so if I understand you correctly, you are planning a fix and in the meantime there isn't anything we can do.

Once the fix is available we would need to run db.pl to delete the documents and have them be reindexed by the capture process?

**Comment by awick** [comment]
Luckily its only the fields index that would need to be fixed, all the sessions data already has 2 fields. You might be able to hack a new field entry for the one that is missing, just make sure you don't have 2 entries that have the same dbField2.

**Comment by mcgillowen** [comment]
Sorry I meant to write "delete the documents in the `fields` index".

Ok, we might go with the hack for the moment, thanks.

**Comment by awick** [comment]
This should be fixed in 5.0.0-rc1, can you give it a try?

**Comment by mcgillowen** [comment]
Sure, I'll try to test it tomorrow otherwise Monday, thanks for letting me know

**Comment by mcgillowen** [comment]
It seems to work in my test environment, but will confirm definitely with our production environment once we upgrade to 5.0.0 once released. Thanks

I'll close this issue.
