### ISSUE TITLE
Parliament - Monitor nodes in a cluster

### ISSUE THREAD

**Issue by problematiq** [arkime/arkime#2264]
It would be nice to either have a drill-down section for an existing cluster in Parliament for nodes, or an ability to add nodes as cluster with ES monitoring turned off.

The idea would be to use notifiers and monitoring for the health of a cluster's nodes, not just the Elasticsearch and primary node.

**Comment by 31453** [comment]
@problematiq We already monitor nodes within the cluster, that's how we notify of issues. Are you saying that you want to be able to ignore specific nodes within a cluster so you don't get notifications/issues?
