### ISSUE TITLE
FR: Allow for export of the User's table as CSV from the Users page

### ISSUE THREAD

**Issue by amaddalena** [arkime/arkime#2281]
Please setup an icon/button to all an export of the Users page to CSV (same table as displayed on the Users page) 
- It would be useful when going through to remove old accounts, get a list of disabled accounts, audit stuffs, etc. TIA!

🦉 🦉 🦉 🦉 🦉 🦉 🦉 🦉

**Comment by awick** [comment]
Will be part of 5.0
