### ISSUE TITLE
建议应当支持Sflow采集模块

### ISSUE THREAD

**Issue by gerfried0** [arkime/arkime#2285]
建议应当支持Sflow采集模块，目前正计划采集HUAWEI 的网络设备，但是并不支持NETFLOW......Sflow能够适配更多的设备。

**Comment by awick** [comment]
Are you asking for a plugin that generates SFLOW or a reader that receives SFLOW? We have no plans to support receiving SFLOW since we are a **FULL** packet capture system and my understanding is SFLOW doesn't support that.

**Comment by gerfried0** [comment]
I am very happy to receive your reply, in fact, I aim to perform traffic analysis on a certain interface of the HUAWEI network device. However, in a production network, multiple interfaces may be monitored to analyze traffic. Therefore, port mirroring is not applicable.
 Sflow: The network device only samples packets, and the statistical analysis of network flows is completed by the remote sFlow collector. Is there another way to meet my needs? Apply it to the arkime system. Currently my arkime version is 4.3.1. Thank!

**Comment by awick** [comment]
Currently not with Arkime since Arkime requires the packets. We have talked about maybe creating a netflow/sflow collector but I'm not sure when we would get to it.

**Comment by gerfried0** [comment]
Ok, got it
