### ISSUE TITLE
packet order is wrong when  tpacketv3NumThreads>1

### ISSUE THREAD

**Issue by peasfarmer** [arkime/arkime#2288]
**Describe the bug**
When using pcapReadMethod=tpacketv3 and tpacketv3NumThreads>1, the order of packets will be out of order, specifically:
1. The order of downloaded pcap packages is disordered
2. The source and target on arkime's view will recognize errors

I changed the tpacketv3NumThreads option to 1 or 2 and tried many times. Every time when tpacketv3NumThreads=2, the packet order is wrong, and tpacketv3NumThreads=1 is normal.

**Arkime/Moloch version**:
arkime-capture 4.2.1-GIT/v4.2.0-52-g4fd4909f

**OS name and version**:
Ubuntu 20.04.3 LTS

**Provide logs, stack traces and steps to reproduce**:
[](url)
![screenshot-20230613-165300](https://github.com/arkime/arkime/assets/9895798/4cb58345-566f-4881-b2c3-114c9772e256)

![screenshot-20230613-165426](https://github.com/arkime/arkime/assets/9895798/dc09f9aa-120b-4f45-802d-3034c359000a)

[pcap.zip](https://github.com/arkime/arkime/files/11732811/pcap.zip)

**Comment by awick** [comment]
Ok, so sounds like a bug in how you forward traffic thru ebpf and not arkime? 
Like I said we depend on the afpacket hash feature for ordering.

**Comment by awick** [comment]
Closing since this doesn't seem like an Arkime issue
