### ISSUE TITLE
email.src - permission denied

### ISSUE THREAD

**Issue by liqingjia** [arkime/arkime#2289]
**Describe the bug**

**Elasticsearch version**:

**Arkime/Moloch version**:

**OS name and version**:

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by liqingjia** [comment]
when i search && email.src == apache@gagmail.gagsnetwork.com,the result is permission denied

**Comment by liqingjia** [comment]
![image](https://github.com/arkime/arkime/assets/12861709/3fba3ec1-4462-4da3-9cc8-67371b62450f)

**Comment by awick** [comment]
https://arkime.com/questions
