### ISSUE TITLE
GLib-ERROR **: 18:20:50.683: ../../../glib/gmem.c:134: failed to allocate 20000 bytes

### ISSUE THREAD

**Issue by Logan-lxw** [arkime/arkime#2304]
**Describe the bug**
Under high traffic conditions, physical memory grows rapidly and ultimately cannot allocate memory space

**Elasticsearch version**:
8.6.2
**Arkime/Moloch version**:
4.2.1
**OS name and version**:
Ubuntu 20.04
**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb
**Provide logs, stack traces and steps to reproduce**:
` GLib-ERROR **: 18:20:50.683: ../../../glib/gmem.c:134: failed to allocate 20000 bytes`
At the beginning of the program, I use the "top" command to detect changes in captrue memory, especially changes in VIRT and RES. I found that at the beginning of the program, the memory gradually increases, but when it reaches a certain level, it remains unchanged or floats slightly. For example, when the network card traffic reaches 1M/s, the memory (RES) may remain at 1GB and no longer grow. Afterwards, when the network card traffic is<=1M, the memory will not decrease. However, when the traffic suddenly increases, such as reaching 20M/s, it can be observed that RES rapidly increases and ultimately reports an error. May I ask how to solve this situation?I'm really confused about this.

**Comment by awick** [comment]
Already talking about on slack.
