### ISSUE TITLE
arkimecapture.service fails to start on Rocky Linux 8 due to a dependency on elasticsearch instead of elasticsearch.service

### ISSUE THREAD

**Issue by alfonsojon** [arkime/arkime#2306]
**Describe the bug**
arkimecapture.service has been failing to start on our Rocky Linux 8 instance after a reboot. I checked logs and found the following error:
`Failed to add dependency on elasticsearch, ignoring: Invalid argument`. I was able to manually start `arkimecapture.service` once elasticsearch was running, but it would fail on reboot or a clean boot. This error combined with the behavior lead me to believe that arkimecapture was trying to start before elasticsearch. Going based off the error provided, it told me that elasticsearch was not a valid dependency so I checked & found it should actually be `elasticsearch.service`. I edited the file `/etc/systemd/system/arkimecapture.service` to rely on `elasticsearch.service` instead of `elasticsearch` and this fixed the issue for me. I would like to see if this can be corrected in the source code. Thank you!

**Elasticsearch version**:
8

**Arkime/Moloch version**:
4.1.0

**OS name and version**:
Rocky Linux 8.8

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
installed using instructions for RHEL 8

**Provide logs, stack traces and steps to reproduce**:
details listed above

**Comment by awick** [comment]
merged
