### ISSUE TITLE
allow customizing footer content

### ISSUE THREAD

**Issue by mmguero** [arkime/arkime#2371]
It would be nice to be able to customize the contents of the footer at the bottom of Arkime's views (with the Arkime v4.4.0 text, the arkime.com link, the operation elapsed time etc.) found in Footer.vue. Preferably with some sort of markup support (HTML or MarkDown). This way end users could customize the links found in the footer.

**Comment by awick** [comment]
We should either do this as a config.ini setting or wait for when we do localization
