### ISSUE TITLE
add hideUpload permission to hide the Upload page from the user

### ISSUE THREAD

**Issue by mmguero** [arkime/arkime#2372]
Similar to the `hideFiles` and `hideStats` permission, this would be a `hideUpload` permission that would hide the Upload page from the user.

**Comment by mmguero** [comment]
Generally, yes. In my particular case, I would set `hideUpload` for *all* users as don't want any users to be able to upload PCAP, but I thought if it worked like `hideFiles` and `hideStats` it would satisfy my case as well.

**Comment by awick** [comment]
If you don't enable upload it is already hidden for all users.

**Comment by mmguero** [comment]
Well how about that. I guess somebody should RTFM. If you don't think this ability (some users being able to upload but not others) is useful outside of my use case, then feel free to close this. Thanks.

**Comment by awick** [comment]
https://arkime.com/settings#uploadRoles added to 5.0
