### ISSUE TITLE
Cisco talosintelligence 

### ISSUE THREAD

**Issue by mbaki** [arkime/arkime#2444]
Hello,

For the coming future, can we add talos intelligence https://www.talosintelligence.com/ to cont3xt integrations. It's a free servie.

Thanks

**Comment by awick** [comment]
doing a quick look i don’t see an api for talos. You could already just add it as a link to a link group since it has nice URLS like https://talosintelligence.com/reputation_center/lookup?search=1.2.3.4

If you wanted something else please reopen with details
