### ISSUE TITLE
[Protocol] Change well-known port

### ISSUE THREAD

**Issue by Popvlvs** [arkime/arkime#2490]
Hello,

Is it possible to modify the related port of a given protocol? As you know, it's a common practice to modify well-known ports for different reasons.

In my specific instance, I'm executing HTTP/2 on TCP/7777 and, obviously, it's not recognized.

Thanks,
Pop

**Comment by awick** [comment]
Arkime doesn't use ports to find most protocols, including http/2. If it isn't working please provide a pcap either here or DM me on slack.

**Comment by Popvlvs** [comment]
Here we go
[sessions.zip](https://github.com/arkime/arkime/files/13206890/sessions.zip)

**Comment by Popvlvs** [comment]
Ok, I get it :) Just starting with Arkime and discovering how it works.

You can close this issue, thanks for the support!

Regards.
