### ISSUE TITLE
Industrial Protocol Parsing

### ISSUE THREAD

**Issue by Popvlvs** [arkime/arkime#2491]
Arkime currently parses Modbus/TCP, but it'd great if it could parse other widely used protocols, such as:

- DNP3
- S7comm
- Profinet[-DCP]
- Ethernet/IP
- ICCP

How are you managing these requests? Is there any guide explaining how to implement a new parser?

Thanks in advance.

**Comment by awick** [comment]
So create an issue for each protocol. Providing a link to the protocol specification and sample pcaps will make it more likely to get implemented. Not sure what you mean by "Ethernet/IP", we already support that :)

It would also be really useful to come over to slack for discussions.

Currently there isn't much documentation about writing new parsers, other than some stuff in the capture directory and looking at other ones.
