### ISSUE TITLE
CyberChef UI is not working on a new Arkime installation

### ISSUE THREAD

**Issue by x4rxes** [arkime/arkime#2498]
**Describe the bug**
After installing Arkime viewer and opening the web UI, we expect `https://arkime-url/CyberChef` to present an operational CyberChef UI we can use. Instead, the CSS files for CyberChef are missing and we are presented with a broken page (see screenshot below).

**Elasticsearch version**:
7.17.14

**Arkime/Moloch version**:
4.6.0

**OS name and version**:
Red Hat Enterprise Linux 8

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
Standard RPM from Centos8 repository

**Provide logs, stack traces and steps to reproduce**:
Install Arkime RPM, start service, open `https://arkime-url/CyberChef`

![Screenshot 2023-11-07 at 10 46 07](https://github.com/arkime/arkime/assets/25826529/802fa95c-6988-4620-b25e-1c71bd1121f8)

**Comment by awick** [comment]
Try `https://arkime-url/cyberchef.html`, although we really only support pivoting from a capture into cyberchef.
