### ISSUE TITLE
WISE support setting separate fields

### ISSUE THREAD

**Issue by awick** [arkime/arkime#2515]
Currently wise design choices favor the ability to cache results which has lead to some big limitations, especially around IPs. For example with the current design it is not possible to set a different fields based on if an ip is src or dst.
 
For example if 1.2.3.4 is foo, 5.6.7.8 is bar, 9.8.7.6 is proxy with http traffic of 1.2.3.4 -> 5.6.7.8 and XFF=9.8.7.6 wise might set the asset=foo,bar,proxy where really you might want asset.src=foo, asset.dst=bar,http.asset=proxy.

Two general approaches
1) Continue to send wise the ip lookups and capture remaps the fields.
1.2.3.4, wise returns asset=foo, capture remaps to asset.src=foo
5.6.7.8, wise returns asset=bar, capture remaps to asset.dst=bar
9.8.7.6, wise returns asset=proxy, capture remaps to http.asset=proxy

2) query wise with both the ip AND the field the ip was from
1.2.3.4;ip.src, wise returns asset.src=foo
5.6.7.8;ip.dst, wise returns asset.dst=bar
9.8.7.6;http.xffip wise returns http.asset=proxy

Pros:
1 - no change to wise
1 - fixes current wise sources
2 - super flexible and clear what is happening

Cons:
1 - can't have wise sources that only do ip lookups for some of the fields
1 - setting the results is a little slower/complex
2 - at least 2x queries to wise for ips since ip.src and ip.dst lookups are now different
2 - wise ip cache is 2x because 2x the queries/results
2 - all the sources have to be updated

I'm leaning towards solution (1) and fixing the limitations by allowing [wise-types] to support other ip queries AND passing the wise-type into the getIp callback (if full query is turned on)
[wise-types]
outersrc=kind:ip;outputip.src
outerdst=kind:ip;outputip.dst

**Comment by Obsecurus** [comment]
I agree I think 1 is a good compromise that increases flexibility without the performance hit. 

Also 1 is only really a problem if you have enrichment sources that have data for both ip.src and ip.dst or outerip.src and outerip.dst for example which duplicates the lookup if you're only having capture care about ip.dst for example. So as long as wise has a snappy return for null results this makes perfect sense to me.

**Comment by awick** [comment]
This was completed in #2517 https://arkime.com/settings#custom-fields-remap
