### ISSUE TITLE
Hunt returns 404 - Old API

### ISSUE THREAD

**Issue by Obsecurus** [arkime/arkime#2531]
**Describe the bug**
When logged into Viewer with Google SSO, if I perform a shift refresh in Chrome I get a 404 and an empty page with the string `Old API`

However, if I go back to /sessions and then just click the Hunt tab it works fine.  

**Elasticsearch version**:
8.9.1

**Arkime/Moloch version**:
4f6fb35f8443d561988a78c1edd9459e141d5b78

**OS name and version**:
Ubuntu 22.04.3 LTS

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
easybutton

**Provide logs, stack traces and steps to reproduce**:
Mon, 04 Dec 2023 17:07:09 GMT 110421085561898851742 GET /hunt 404 - bytes 5.447 ms

**Comment by awick** [comment]
fixed in #2533
