### ISSUE TITLE
capture: reading pcap files directly from S3

### ISSUE THREAD

**Issue by ronchler** [arkime/arkime#2538]
**Is your feature request related to a problem? Please describe.**

We have historical pcap files in our S3 storage and would like to parse them directly from S3.

**Describe the solution you'd like**

Support something like this:

```bash
arkime-capture -c config.ini -r s3://bucket/remote/file.pcap
```

**Describe alternatives you've considered**

1. Copying the file from S3 to local
2. Use `arkime-capture --copy` to parse and copy local pcap file to S3

We now have the same PCAP stored twice, but in different directories and different names.

**Additional context**

none

**Comment by awick** [comment]
Would reusing how auth works for the writer be ok, or do you expect something different?

**Comment by ronchler** [comment]
You mean using the same S3 credentials? Yes!

I would expect the same behavior as importing a local pcap file.

If I use `arkime-capture -r /some/path/to/file.pcap`, I have seen that arkime uses the same filepath (= `/some/path/to/file.pcap`) in OpenSearch in the `arkime-files` index.

So I would expect that using `arkime-capture -r s3://some/path/to/file.pcap`, stores the same filepath (= `s3://some/path/to/file.pcap`) to s3 in `arkime-files`.

**Comment by awick** [comment]
Ok, have the first version of this implemented, could you try out the latest commit build https://github.com/arkime/arkime/releases/tag/last-commit

you'll want to do either
capture -r s3://bucket/key.pcap 
or
capture -r s3https://host:port/bucket/key.pcap

**Comment by ronchler** [comment]
Hi @awick! Awesome!

I will try it out and will give feedback!

Can you point me to the commit which contains the change? I can't find it.

Thank you again!

**Comment by awick** [comment]
I would suggest just using main

**Comment by ronchler** [comment]
I meant, that https://github.com/arkime/arkime/pull/2571 implemented the feature.

**Comment by awick** [comment]
ok, but there are updates since then, so I want to make sure you don't just use that
