### ISSUE TITLE
ILM Rotate Index

### ISSUE THREAD

**Issue by pleasantencounter** [arkime/arkime#2555]
**Is your feature request related to a problem? Please describe.**
Are there any plans to allow Elasticsearch to manage it's own ILM (Index Lifecycle Management) in the near future? The current rotate index capability using time is not ideal for all deployments.

**Describe the solution you'd like**
Adding a capability to allow Elasticsearch to use ILM to rotate indices would be the best solution. However, if Arkime INI settings could also provide a configuration for size instead of just time that could work as well. I would rather prefer allowing Elastic handling the ILM.

**Comment by awick** [comment]
No current plans, although there is a PR for data streams (#2547) but not sure when/if that will be merged. There are two general problems with ILM size based rotation, data streams, and other non date based index name schemes.

1) Performance

When doing searches there is no easy way to narrow down which indices to search, so you have to search all of them. With testing we found this could add 250ms to 1s per query with you have large scale clusters. I'm guessing we could just use min/max aggregations per index and cache the result and select based on that. This is already testable with the https://arkime.com/settings#queryAllIndices setting

2) Read-only

Some of these methods require the indices to become read only. This will break hunts, add/remove tags, and session scrubbing. For hunts and tags we could add parallel data stores and do joins (with a performance cost) but scrubbing would be impossible.
