### ISSUE TITLE
Problem building Arkime on RPI4

### ISSUE THREAD

**Issue by michalisk13** [arkime/arkime#2559]
Hi,

I am quite new on Arkime and I am trying to figure out how I can build Arkime on one of my RPI4 for 64bit ARM.

When I try to run ./easybutton-build.sh
I get the following error 
`
make[1]: Entering directory '/home/user/Documents/arkime/capture'
gcc  -rdynamic -ggdb -pthread main.o db.o yara.o http.o config.o parsers.o plugins.o field.o writers.o writer-inplace.o writer-null.o writer-simple.o readers.o reader-libpcap-file.o reader-libpcap.o reader-tpacketv3.o reader-null.o reader-pcapoverip.o reader-tzsp.o packet.o session.o rules.o drophash.o pq.o dedup.o -o capture \
            -u g_checksum_update -u g_hmac_update -u g_uri_unescape_segment -u nghttp2_hd_inflate_hd2 \
    /home/user/Documents/arkime/thirdparty/libpcap-1.10.4/libpcap.a   \
    /home/user/Documents/arkime/thirdparty/glib-2.72.4/_build/glib/libglib-2.0.a /home/user/Documents/arkime/thirdparty/glib-2.72.4/_build/gio/libgio-2.0.a /home/user/Documents/arkime/thirdparty/glib-2.72.4/_build/gobject/libgobject-2.0.a /home/user/Documents/arkime/thirdparty/glib-2.72.4/_build/gthread/libgthread-2.0.a /home/user/Documents/arkime/thirdparty/glib-2.72.4/_build/gmodule/libgmodule-2.0.a /home/user/Documents/arkime/thirdparty/glib-2.72.4/_build/glib/libglib-2.0.a /home/user/Documents/arkime/thirdparty/yara/yara-4.2.3/libyara/.libs/libyara.a /home/user/Documents/arkime/thirdparty/libmaxminddb-1.7.1/src/.libs/libmaxminddb.a /home/user/Documents/arkime/thirdparty/curl-8.4.0/lib/.libs/libcurl.a /home/user/Documents/arkime/thirdparty/nghttp2-1.57.0/lib/.libs/libnghttp2.a /home/user/Documents/arkime/thirdparty/zstd-1.5.5/lib/libzstd.a -lrt -luuid -lpcre thirdparty/http_parser.o thirdparty/js0n.o thirdparty/patricia.o -ldl -lssl -lcrypto -lyaml \
    -lm -lresolv -lmagic -lffi -lz
/usr/bin/ld: /home/user/Documents/arkime/thirdparty/curl-8.4.0/lib/.libs/libcurl.a(libcurl_la-version.o): in function `curl_version':
version.c:(.text+0x80): undefined reference to `BrotliDecoderVersion'
/usr/bin/ld: /home/user/Documents/arkime/thirdparty/curl-8.4.0/lib/.libs/libcurl.a(libcurl_la-version.o): in function `curl_version_info':
version.c:(.text+0x170): undefined reference to `BrotliDecoderVersion'
/usr/bin/ld: version.c:(.text+0x178): undefined reference to `BrotliDecoderVersion'
/usr/bin/ld: /home/user/Documents/arkime/thirdparty/curl-8.4.0/lib/.libs/libcurl.a(libcurl_la-content_encoding.o): in function `brotli_close_writer':
content_encoding.c:(.text+0x4c): undefined reference to `BrotliDecoderDestroyInstance'
/usr/bin/ld: /home/user/Documents/arkime/thirdparty/curl-8.4.0/lib/.libs/libcurl.a(libcurl_la-content_encoding.o): in function `brotli_init_writer':
content_encoding.c:(.text+0x70): undefined reference to `BrotliDecoderCreateInstance'
/usr/bin/ld: /home/user/Documents/arkime/thirdparty/curl-8.4.0/lib/.libs/libcurl.a(libcurl_la-content_encoding.o): in function `brotli_unencode_write':
content_encoding.c:(.text+0x208): undefined reference to `BrotliDecoderDecompressStream'
/usr/bin/ld: content_encoding.c:(.text+0x254): undefined reference to `BrotliDecoderDestroyInstance'
/usr/bin/ld: content_encoding.c:(.text+0x290): undefined reference to `BrotliDecoderGetErrorCode'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:53: all] Error 1
make[1]: Leaving directory '/home/user/Documents/arkime/capture'
make: *** [Makefile:444: all-recursive] Error 1
ARKIME: make failed
`

I have previously run ../configure and I have installed all required dependencies.
I also tried to build curl from sources and the error still persists

Hope someone can help me with this!

Thanks,
Mik

**Comment by awick** [comment]
First of all, do the latest commit arm builds we provide not work?

Looks like it needs the brotli library to link
* either unstall brotli, remove thirdparty/curl and try again
* change easybutton to build curl without it (probably --without-brotli)
* change makefile of capture to have something like -lbrotli

**Comment by michalisk13** [comment]
Hi @awick,

Thanks for the reply!
So in the easybutton file should I remove the following?

 ```
 if [ ! -z "$WITHCURL" ]; then
    echo "ARKIME: withcurl $WITHCURL"
  else
    WITHCURL="--with-curl=thirdparty/curl-$CURL"
    if [ ! -f "curl-$CURL.tar.gz" ]; then
      wget https://curl.haxx.se/download/curl-$CURL.tar.gz
    fi

    if [ ! -f "curl-$CURL/lib/.libs/libcurl.a" ]; then
      tar zxf curl-$CURL.tar.gz
      ( cd curl-$CURL; ./configure --disable-ldap --disable-ldaps --without-libidn2 --without-librtmp --without-libpsl --without-nghttp2 --without-nghttp2 --without-nss --with-openssl --without-zstd; $MAKE)
      if [ $? -ne 0 ]; then
        echo "ARKIME: $MAKE failed"
        exit 1
      fi
    else
      echo "ARKIME: Not rebuilding curl"
    fi
  fi
```

also in the makefile of capture should I remove this line?
`-I/home/user/Documents/arkime/thirdparty/curl-8.4.0/include
`

Regarding the last point `change makefile of capture to have something like -lbrotli` I have no clue how to do it :)

Also I want to be able to access server running Arkime on another machine on the same subnet! 
Will it be possible after I manage to install it?

Thanks,
Mik

**Comment by awick** [comment]
Those were 3 choices of how to fix, just choose one.  One of those choices was to modify the ./configure line you have above and add the --without

If you have general questions please come over to slack. https://arkime.com/questions

**Comment by michalisk13** [comment]
Thanks @awick 

I managed to build using easybutton 

When I try to configure before run I get the following:

```
ARKIME: Now type 'sudo make install' and 'sudo make config'
user@user:~/Documents/arkime $ sudo make config
/opt/arkime/bin/Configure
/bin/bash: line 1: /opt/arkime/bin/Configure: No such file or directory
make: *** [Makefile:878: config] Error 127
```

However the install works with some warnings.. is should be ok now?

```
user@user:~/Documents/arkime $ sudo make install
sudo: unable to resolve host sentinelmobile: Name or service not known
Making install in .
make[1]: Entering directory '/home/user/Documents/arkime'
make[2]: Entering directory '/home/user/Documents/arkime'
npm ci
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: undefined,
npm WARN EBADENGINE   required: { node: '>= 16.0.0 < 19', npm: '>= 3.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@aws-sdk/client-s3@3.425.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@aws-sdk/client-sso@3.425.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@aws-sdk/client-sts@3.425.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@aws-sdk/credential-provider-env@3.425.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@aws-sdk/credential-provider-ini@3.425.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@aws-sdk/credential-provider-node@3.425.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@aws-sdk/credential-provider-process@3.425.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }

```

**Comment by awick** [comment]
ya you get those first errors if you didn't tell it to install.

No it won't work, it is telling you the version of node you are using is too old.

**Comment by michalisk13** [comment]
Thanks, I' ve managed to solve it by removing the dependencies as per your suggestions!
