### ISSUE TITLE
Split DNS requests from CNAME responses

### ISSUE THREAD

**Issue by problematiq** [arkime/arkime#2560]
Please separate queries and responses for DNS into their own fields.
This is useful when looking for beacons via DNS without having to sift through the CNAME responses.

```
Is there a way to separate out a dns query from a DNS response?
so, I ask for blank[.]com and it returns cdn.blank[.]com CNAME, 7.7.7.7 A, bob[.]blanl[.]com CNAME
The host.dns field now has the query and the cnames.
```

**Comment by 31453** [comment]
Looking at redoing DNS Parser.

**Comment by awick** [comment]
Let me know if #2694 doesn't address
