### ISSUE TITLE
 Packet export

### ISSUE THREAD

**Issue by HOPEAMOR** [arkime/arkime#2567]
During use, I found that arkime can only export the PCAP of individual data packets, and cannot batch export this part of the data packets into a PCAP file after conditional filtering.

**Comment by awick** [comment]
In the future please fill out the issue template, otherwise just have to ask the same questions here.

**Elasticsearch version**:

**Arkime/Moloch version**:

**OS name and version**:

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)

**Provide logs, stack traces and steps to reproduce**:

**Comment by HOPEAMOR** [comment]
Elastic search version: elastic-7.x

Arkime/Moloch version: arkime_4.2.0-1_amd64.deb

Operating system name and version: Ubuntu 20.04

How Arkime/Moloch is built/installed: deb

Provide logs, stack traces and reproduction steps: Click on a single flow information on the visual interface and export it through Download PCAP. This way only one flow information can be exported and cannot be filtered by IP. Export all traffic of this IP to a pcap file.
![AkSUjXnV3d7hb63yr-mGlBtuf_qGygpr568RhbSqIVo](https://github.com/arkime/arkime/assets/32115459/3098e795-4456-423e-9be0-51aa0c3ae278)

**Comment by awick** [comment]
Please try 4.6.0 and check viewer.log for errors

**Comment by awick** [comment]
If you are asking how to export all sessions with a given IP, use the Export PCAP in the actions menu next to the search bar.
<img width="283" alt="image" src="https://github.com/arkime/arkime/assets/427321/c6eb025b-a5b6-4ad4-8094-c951d4150aec">

**Comment by HOPEAMOR** [comment]
Thank you very much. I found the export location. When I am using it, when I turn on the capture on a network card, there will be a problem exporting PCAP. PCAP files larger than 3M will fail to be exported. This problem occurs when I turn off the capture. In mode, you can export 300M PCAP files

**Comment by awick** [comment]
Are there errors in viewer.log? Are you running out of memory?

**Comment by HOPEAMOR** [comment]
Thu, 28 Dec 2023 03:00:16 GMT - [1mGET[0m [33m/api/eshealth[0m 200 456 bytes 5.851 ms
Thu, 28 Dec 2023 03:00:18 GMT - [1mGET[0m [33m/api/eshealth[0m 200 456 bytes 0.645 ms
Thu, 28 Dec 2023 03:00:24 GMT - [1mGET[0m [33m/api/eshealth[0m 200 456 bytes 1.453 ms
ERROR - Couldn't open file  Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
    at Zlib.writeSync (<anonymous>)
    at processChunkSync (node:zlib:457:12)
    at zlibBufferSync (node:zlib:178:12)
    at Object.syncBufferWrapper [as gunzipSync] (node:zlib:792:14)
    at Pcap.readHeader (/opt/arkime/viewer/pcap.js:217:30)
    at Pcap.open (/opt/arkime/viewer/pcap.js:133:10)
    at /opt/arkime/viewer/apiSessions.js:684:19
    at Immediate._onImmediate (/opt/arkime/viewer/db.js:1541:35)
    at processImmediate (node:internal/timers:466:21) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}
ERROR - processSessionIdDisk - 231228-fxvsQNgO5Z9MCZGVK9lEiPW0 in file /opt/arkime/raw/*****-231228-00000113.pcap.gz couldn't read packet at 825306254 packet # 0 of 12
Trace: writePcap 231228-fxvsQNgO5Z9MCZGVK9lEiPW0 in file /opt/arkime/raw/*****-231228-00000113.pcap.gz couldn't read packet at 825306254 packet # 0 of 12
    at /opt/arkime/viewer/apiSessions.js:939:19
    at /opt/arkime/viewer/apiSessions.js:1201:20
    at /opt/arkime/viewer/apiSessions.js:641:11
    at /opt/arkime/viewer/pcap.js:312:16
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
/opt/arkime/node_modules/async/dist/async.js:324
            if (fn === null) throw new Error("Callback was already called.");
                             ^

Error: Callback was already called.
    at /opt/arkime/node_modules/async/dist/async.js:324:36
    at /opt/arkime/viewer/apiSessions.js:941:16
    at /opt/arkime/viewer/apiSessions.js:1201:20
    at /opt/arkime/viewer/apiSessions.js:641:11
    at /opt/arkime/viewer/pcap.js:312:16
    at FSReqCallback.wrapper [as oncomplete] (node:fs:671:5)
Express server listening on port 8005 in development mode
Thu, 28 Dec 2023 03:00:26 GMT - [1mGET[0m [33m/api/eshealth[0m 200 456 bytes 3.476 ms
This node will process Periodic Queries (CRON) & Hunts, delayed by 85 seconds
Thu, 28 Dec 2023 03:00:28 GMT - [1mGET[0m [33m/api/eshealth[0m 200 456 bytes 0.776 ms
Thu, 28 Dec 2023 03:00:36 GMT - [1mGET[0m [33m/api/eshealth[0m 200 456 bytes 5.938 ms

**Comment by awick** [comment]
* https://arkime.com/faq#zero-byte-pcap-files
* There are also issues with gzip and older versions of Arkime, you should upgrade to 4.6

**Comment by HOPEAMOR** [comment]
Okay, in fact, I need to import, analyze, and export TB-level PCAPs. The real-time traffic function is currently not available. I want to know which parameters to modify to improve the import, analysis (fast retrieval of different IPs), and export of PCAPs. Ability, here I will use 32 cores, 32GB memory.

**Comment by awick** [comment]
* 5.0 will have improved import, I'm working on this now
* looks like this issue is fixed, so i'm going to close, please come to slack if you have questions https://arkime.com/questions
