### ISSUE TITLE
Cont3xt - bug in integration card table display not using local field value for pivot

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#2569]
Not sure when this feature regressed, but in any table rendered by context where a value has a drop down to either copy or pivot. The pivot does not use the local field value, and instead queries the top level indicator that has focus once more. The copy function works as expected. Maybe this happened in 5.0 with bulk query support.

You can reproduce with:
https://YOUR_CONTEXT_INSTANCE/?b=cHVycGxlLm9yZw%3D%3D&submit=y
Then review the PT DNS section, look for any value with a drop down to pivot [that isn't the same as the indicator having been queried], and try the pivot.

The behavior is the same across any other cont3xt integration result that uses tables that have copy/pivot drop downs.

**Comment by 31453** [comment]
fixed in #2570
