### ISSUE TITLE
I want to provide an ipk installation package for the openwrt platform

### ISSUE THREAD

**Issue by nulldx** [arkime/arkime#2572]
**Is your feature request related to a problem? Please describe.**
I want to use arkime on my openwrt router, but I can't build the program on my router, and there is no official installation package available on openwrt

**Describe the solution you'd like**
I hope that the official can provide an ipk program, directly using the opkg package management tool to install in the openwrt system

**Comment by awick** [comment]
I'm not sure Arkime makes sense to run directly on a openwrt router

Which device are you targeting, how much RAM does it have, and how much disk space?
I assume you would still run elasticsearch on a different device?

**Comment by awick** [comment]
feel free to reopen with answers
