### ISSUE TITLE
Allow intercepting TCP headers for the JA4Plus plugin

### ISSUE THREAD

**Issue by noeltimothy** [arkime/arkime#2594]
**Is your feature request related to a problem? Please describe.**
This feature request has been submitted to allow Arkime to send TCP packets that do not have any payload to TCP callbacks.
The current code does not send TCP packets without a payload to callbacks registered by plugins.
In case of the new Ja4Plus plugin, we want to be able to access TCP packets to record and create fingerprints based on the below criteria and fields.

- SYN packet timestamp
- SYN-ACK packet timestamps along with re-trasmitted SYN-ACKs
- ACK pacet timestamp
- TCP options
- TCP window size
- IP time to live
 
**Describe the solution you'd like**
Instead of adding the above fields to the Arkime session, we thought it would be cleaner to just send the entire ArkimePacket to plugins that have registered for TCP. The length of the packet will be zero in this case. It is upto the plugin to peek into the packet to decipher the TCP headers, IP headers or any other data that it requires.

**Describe alternatives you've considered**
Add timestamps into the TCP packet code and record different timestamps in the Arkime session.

**Additional context**
Details of JA4L and JA4T are @ https://github.com/FoxIO-LLC/ja4.

**Comment by noeltimothy** [comment]
Submitted a PR for this at https://github.com/arkime/arkime/pull/2595

**Comment by awick** [comment]
Used a named func instead #2605
