### ISSUE TITLE
The command "./easybutton build. sh -- install" failed to execute

### ISSUE THREAD

**Issue by mengpeiyao** [arkime/arkime#2596]
**Describe the bug**
Unable to install successfully
**Elasticsearch version**:
7.10
**Arkime/Moloch version**:
5.0.0
**OS name and version**:
centos7
**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
./easybutton build. sh -- install
**Provide logs, stack traces and steps to reproduce**:
`Making install in .
make[1]: 进入目录“/root/mpypoj/arkime”
make[2]: 进入目录“/root/mpypoj/arkime”
npm ci
npm WARN deprecated vuex-persistedstate@4.1.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm ERR! code 1
npm ERR! path /root/mpypoj/arkime/node_modules/iptrie
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! make[3]: 进入目录“/root/mpypoj/arkime/node_modules/iptrie/build”
npm ERR!   CXX(target) Release/obj.target/iptrie/src/iptrie.o
npm ERR! make[3]: 离开目录“/root/mpypoj/arkime/node_modules/iptrie/build”
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.3.0
npm ERR! gyp info using node@18.19.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.8.0 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/root/mpypoj/arkime/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/mpypoj/arkime/node_modules/iptrie/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/mpypoj/arkime/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.19.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.19.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/mpypoj/arkime/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.19.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/root/mpypoj/arkime/node_modules/iptrie',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! g++: 错误：unrecognized command line option ‘-std=gnu++17’
npm ERR! make[3]: *** [Release/obj.target/iptrie/src/iptrie.o] 错误 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/root/mpypoj/arkime/node_modules/node-gyp/lib/build.js:203:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
npm ERR! gyp ERR! System Linux 3.10.0-1160.102.1.el7.x86_64
npm ERR! gyp ERR! command "/opt/arkime/node-v18.19.0-linux-x64-glibc-217/bin/node" "/root/mpypoj/arkime/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /root/mpypoj/arkime/node_modules/iptrie
npm ERR! gyp ERR! node -v v18.19.0
npm ERR! gyp ERR! node-gyp -v v9.3.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-01-15T08_42_23_218Z-debug-0.log
make[2]: *** [install-exec-local] 错误 1
make[2]: 离开目录“/root/mpypoj/arkime”
make[1]: *** [install-am] 错误 2
make[1]: 离开目录“/root/mpypoj/arkime”
make: *** [install-recursive] 错误 1
ARKIME: Installed, now type sudo make config'
`

**Comment by awick** [comment]
Please just use the prebuilt for centos 7
