### ISSUE TITLE
 capture - readTruncatedPackets config option doesn't work

### ISSUE THREAD

**Issue by NicoN37** [arkime/arkime#2636]
Hello, 

I need to store truncated packets on arkime, I desactivated all parsers, I don't need it so I don't need to go in the payload.
I add readTruncatedPackets=true in the configuration file (config.ini) but all truncated packets are tagged corrupt in arkime.
Is it possible to store truncated packets with the session?

Thanks
Regards
Nico

**Comment by awick** [comment]
https://arkime.com/questions
