### ISSUE TITLE
[proposal] New generic field type with support for more complex structs

### ISSUE THREAD

**Issue by mcgillowen** [arkime/arkime#2664]
**Is your feature request related to a problem? Please describe.**
Creating fields that are more complex than a unitary/array value requires large changes to core Arkime source files like `arkime.h`, `db.c`, `fields.c`, etc, this makes it near impossible to write more complex parser outputs that need to store for example JSON objects.

An example of such a field is the `ARKIME_FIELD_TYPE_CERTSINFO` field type.

**Describe the solution you'd like**

There should be a generic field type that can work with the more complex/nested fields, the suggestion would be an `ARKIME_FIELD_TYPE_OBJECT` that supports generic objects as fields.

## ARKIME_FIELD_TYPE_OBJECT proposal

⚠️ This is still a WIP and some or most of the parts below may change while trying to implement such a field ⚠️ 

### Functions that would need to be implemented by a `ARKIME_FIELD_TYPE_OBJECT` field

* save: creates the object in JSON in a BSB, takes in a pointer to a BSB as argument as well as the object and session in question
* free: takes a pointer to the object
* hash: calculates a hash (uint32) for the object
* cmp: compares 2 objects

### Functions that are needed to manipulate ARKIME_FIELD_TYPE_OBJECT objects

* register: takes pointers for the functions save, alloc, free, hash and cmp along with the name of the object and returns the field position
* add: adds the specific struct containing the data/information, takes the field position, pointer to the session in question and a pointer to the object and the JSON length/size of it

#### ARKIME_FIELD_TYPE_OBJECT implementations

```
void certinfo_save(BSB *jbsb, ArkimeFieldObject_t *object, ArkimeSession_t *session);
void certinfo_free(ArkimeFieldObject_t *object);
uint32_t certinfo_hash(const void *key);
int certinfo_cmp(const void *keyv, const void *elementv);
```

#### ARKIME_FIELD_TYPE_OBJECT functions

```
int arkime_field_object_register(const char *name, ArkimeFieldObjectSaveFunc save, ArkimeFieldObjectFreeFunc free, ArkimeFieldObjectHashFunc hash, ArkimeFieldObjectCmpFunc cmp);
gboolean arkime_field_object_add(int pos, ArkimeSession_t *session, ArkimeFieldObject_t *object, int len);
```

#### ARKIME_FIELDS_TYPE_OBJECT struct

```
typedef struct arkime_field_object {
    struct arkime_field_object      *o_next, *o_prev;
    uint32_t                         o_hash;
    short                            o_bucket;
    void                            *object;
} ArkimeFieldObject_t;

typedef struct {
    struct arkime_field_object      *o_next, *o_prev;
    short                            o_count;
} ArkimeFieldObjectHead_t;

typedef HASH_VAR(o_, ArkimeFieldObjectHash_t, ArkimeFieldObjectHead_t, 1);
typedef HASH_VAR(o_, ArkimeFieldObjectHashStd_t, ArkimeFieldObjectHead_t, 13);

typedef void (* ArkimeFieldObjectSaveFunc) (BSB *jbsb, ArkimeFieldObject_t *object, ArkimeSession_t *session);
typedef void (* ArkimeFieldObjectFreeFunc) (ArkimeFieldObject_t *object);
typedef uint32_t (* ArkimeFieldObjectHashFunc) (const void *key);
typedef int (* ArkimeFieldObjectCmpFunc) (const void *keyv, const void *elementv);
```

**Describe alternatives you've considered**

I haven't thought of any alternatives.

**Additional context**

This would be used in a new DNS parser that would solve some of the issues of the current implementation like #2560 and some others

**Comment by awick** [comment]
Looks great! A few minor questions/comments. Excited to see this done!!!

- [ ] Just confirming that the overall design is that the field layer handles any array aspect, so if a single session had N of an object type it would could arkime_field_object_add N times, the save callback N time, and then the free callback would be called N times.
- [ ] the description of free says no args, but code shows one, I think one is needed
- [ ] not sure alloc cb is needed, should'nt the parser call ARKIME_TYPE_ALLOC and then arkime_field_object_add, I might be missing something.
- [ ] ArkimeFieldObjectSaveFunc will need to get a * to the BSB i think

**Comment by mcgillowen** [comment]
> Just confirming that the overall design is that the field layer handles any array aspect, so if a single session had N of an object type it would call arkime_field_object_add N times, the save callback N time, and then the free callback would be called N times.
Yes, that is how I see it, it's similar to how the TLS certs work ATM

>  the description of free says no args, but code shows one, I think one is needed
You are correct, I've updated the description of free, it should take a pointer to the object

> not sure alloc cb is needed, should'nt the parser call ARKIME_TYPE_ALLOC and then arkime_field_object_add, I might be missing something.
You are correct, since the only place that the object should be allocated is where its being added from so it would know how to allocate it, I've removed the alloc cb from the proposal.

> ArkimeFieldObjectSaveFunc will need to get a * to the BSB i think
Yes, I've updated the proposal

I've started writing an implementation and have found some issues with the original design, so I've updated the proposal to take into account the issues I discovered. The main change is `ArkimeFieldObject_t` is no longer a struct that can be used with `hash.h` or `dll.h` rather it wraps a hash of objects that only contains a void pointer, this removes the need to copy the pointers to the CBs and `object_name` to each new object of the same type/name.

**Comment by awick** [comment]
> I've started writing an implementation and have found some issues with the original design, so I've updated the proposal to take into account the issues I discovered. The main change is `ArkimeFieldObject_t` is no longer a struct that can be used with `hash.h` or `dll.h` rather it wraps a hash of objects that only contains a void pointer, this removes the need to copy the pointers to the CBs and `object_name` to each new object of the same type/name.

Ok, I wonder then if those should just either be inside of ArkimeFieldInfo_t or pointed to by that?

**Comment by mcgillowen** [comment]
That's actually a good idea, it would remove the need for the arkime_field_object_register function and I could reuse the arkime_field_define function.

I'll take a look in the morning

**Comment by mcgillowen** [comment]
I'm closing this issue since the functionality has been merged into main and the TLS certs have been migrated to the new ARKIME_FIELD_TYPE_OBJECT.
