### ISSUE TITLE
Importing PCAP Files from S3 times out after 120 seconds

### ISSUE THREAD

**Issue by Honkmueller** [arkime/arkime#2698]
**Describe the bug**
When I capture a big PCAP file directly from S3 using `-f s3https://s3server/s3bucket/path/to/file.pcap` it wil load everything fine for exactly 2 minutes (120 seconds). After that it shuts down as if it was finished. No warning, error or anythings.

`--debug` only reveals a `http.c:701 arkime_http_curl_close_callback()` shortly before is closes. I expect that there is some sort of timeout working.

This is really unfortunate since I cannot influence the size of the pcaps I am working with.

**Opensearch version**:  2.12.0

**Arkime/Moloch version**: 5.0.1

**OS name and version**: Alpine 3.19.0

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...) makefile

**Provide logs, stack traces and steps to reproduce**:
` http.c:701 arkime_http_curl_close_callback(): Close 1/0 - https://[REDACTED].com   59424->[IP REDACTED]:443 fd:12 removed: true`

**Comment by awick** [comment]
yes, looks like curl has a 120s timeout, i'll add a fix

**Comment by Honkmueller** [comment]
Impressive answering and fixing speed, @awick 
Works perfectly. Even with the wildest PCAP sizes. Thank you so much!
