### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by deanfourie1** [arkime/arkime#2708]
**Describe the bug**
Cannot start, says that OpenSearch is not running

**Elasticsearch version**:
latest to date

**Arkime/Moloch version**:
latest to date

**OS name and version**:
Ubuntu Server 2204

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb

**Provide logs, stack traces and steps to reproduce**:

`dean@test:~$ sudo /opt/arkime/db/db.pl http://127.0.0.1:9200 init                               Couldn't GET http://127.0.0.1:9200/_cluster/health  the http status code is 500 are you sure OpenSearch/Elasticsearch is running/reachable? at /opt/arkime/db/db.pl line 308.`

**Comment by awick** [comment]
https://arkime.com/questions
