### ISSUE TITLE
Failure to classify SMB encrypted session packet protocol as SMB

### ISSUE THREAD

**Issue by ksh98** [arkime/arkime#2728]
**Describe the bug**

The encrypted SMB session protocol is classified as only TCP.

When analyzing the "smb3-aes-128-ccm.pcap" and "smb311-aes-128-ccm-filt.pcap" files of the https://wiki.wireshark.org/SampleCaptures#smb3-encryption URL, they are classified as only TCP.

This Pcap file is also classified as only TCP.
smb300-aes-128-ccm.pcap.gz, smb311-aes-128-ccm.pcap.gz, smb311-aes-128-gcm.pcap.gz, smb311-aes-256-ccm.pcap.gz, smb311- aes-256-gcm.pcap.gz file of the https://github.com/wireshark/wireshark/tree/master/test/captures URL

“SMB” exists from the 5th character of the payload, but it is not classified as SMB.
arkime_parsers_classifier_register_tcp("smb", NULL, 5, (uint8_t *)"SMB", 3, smb_classify);

**Elasticsearch version**:
https://demo.arkime.com/

**Arkime/Moloch version**:
https://demo.arkime.com/

**OS name and version**:
https://demo.arkime.com/

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
https://demo.arkime.com/

**Provide logs, stack traces and steps to reproduce**:
...

**Comment by awick** [comment]
The ones on the wireshark page don't seem to have the TCP handshake. Did you upload some to demo that do? If so what tag did you use.

**Comment by ksh98** [comment]
> The ones on the wireshark page don't seem to have the TCP handshake. Did you upload some to demo that do? If so what tag did you use.

The "smb240401" tag was used in the "smb3-aes-128-ccm.pcap" and "smb311-aes-128-ccm-filt.pcap" files.

**Comment by awick** [comment]
Ya neither of those have SYN or SYN-ACK, we require at least one of those to classify.

**Comment by ksh98** [comment]
> Ya neither of those have SYN or SYN-ACK, we require at least one of those to classify.

Thank you for answer.
have a good day.

**Comment by awick** [comment]
Ok, if you find another one let me know
