### ISSUE TITLE
Spooling of SPI Data To Disk On Capture Host

### ISSUE THREAD

**Issue by eoinmiller** [arkime/arkime#276]
Please modify the capture process to spool the generated SPI data to disk in the event of being unable to communicate with the ES cluster. This would allow network/ES outages to not impact the indexing of SPI data which otherwise would lead to the traffic not being indexed.

**Comment by awick** [comment]
Want to make it use a message q like kafta and such, not sure we will do direct to disk.

**Comment by awick** [comment]
Might do kafta someday, but not this :)
