### ISSUE TITLE
是否能增加汉化版本 或者在哪里进行汉化

### ISSUE THREAD

**Issue by linxinxiaotuanzi** [arkime/arkime#2774]
是否能增加汉化版本 或者在哪里进行汉化

**Comment by linxinxiaotuanzi** [comment]
我要如何修改前端显示的英文字符串。如何修改为中文  如果通过修改文件的方式可以实现。我要修改那个文件 或者有什么别的办法

**Comment by awick** [comment]
duplicate of #2563

**Comment by linxinxiaotuanzi** [comment]
https://github.com/arkime/arkime/issues/2563只提到了不支持  如果我想汉化  我要修改那个文件 或者有什么别的办法

**Comment by linxinxiaotuanzi** [comment]
![81026eda41be1ff59969306dae2e6bc](https://github.com/arkime/arkime/assets/135091284/f855bc3c-59a0-4c3b-96ce-24082629691d)
不好意思 没看到6.0准备支持  感谢接受汉化的意见
