### ISSUE TITLE
Add config variable for max sesssions

### ISSUE THREAD

**Issue by buptxdt** [arkime/arkime#2805]
**Describe the bug**
after select time period,then chose export csv and use matching items  option,I cannot get all sessions in this period when it was downloaded, I check the file and found the number of sessions is 2000001,the filesize is 202MB
**Elasticsearch version**:
7.10.2
**Arkime/Moloch version**:
v5.0.1
**OS name and version**:
CentOS 7 x86_64 
**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
rpm

**Comment by awick** [comment]
We currently hardcode the max number of sessions to 2000000, add a new config variable
