### ISSUE TITLE
Improved time format string support for link groups

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#2826]
I've found myself needing to specify custom time ranges in crafting downstream link group query links

A common one is needing to be able to specify separate query string values for individual groups like YYYYmm, dd and HH

The bare minimum support would be to add static support for the following format strings:
${startYear}
${startMonth}
${startDay}
${startHour}
${startMinute}
${startSecond}

${endYear}
${endMonth}
${endDay}
${endHour}
${endMinute}
${endSecond}

However, in order to future proof for ultimate flexibility [and better handle discrepancies during time zone conversion and especially around discrepancies in local versus stored TZ log formats], additional support for increment / decrement operators on the calculated time values. It sounds a lot more difficult to implement but ideally cont3xt/Arkime would have a generic ${start(optional_time_modifier)[format_string]} and ${end(optional_time_modifier)[format_string]} handler that would support natural time format spec, like:
```
* where calculated values are governed by cont3xt time selectors

${start(optional_time_modifier)['%Y']}       ;# returns YYYY from startTime
${start(optional_time_modifier)['%Y%m']} ;# returns YYYYmm from startTime
${end(optional_time_modifier)['%Y/%m/%d:%H:%M:%S']}  ;# returns YYYY/mm/dd:HH:MM:SS from endTime

* for the following examples if the cont3xt startTime were 2024-05-31T12:53:20Z, and endTime were 2024-06-07T12:53:20Z
${start('1 day ago')['%Y%m%d']} ;# the calculated value used in a link group would be '20240530'.
${end('20 minutes from now')['%H%M']} ;# the calculated value used in a link group would be '1323'.
${end('43 seconds from now')['%M%s']} ;# the calculated value used in a link group would be '5403'.
```

I'm drawing this concept from regular use of gnu `date` command line support. 
https://www.man7.org/linux/man-pages/man1/date.1.html. ;# refer to `-d` Format modifiers section

I haven't looked, but I hope there is an equivalent js/node library to handle this.

I'm not locked into requiring natural language support for the optional_time_modifier, just something that provides the flexibility of gnu `date`

**Comment by awick** [comment]
lol, still refusing to separate requirements from implementation. :) 

1) totally agree we should just support a date format instead of a million variables, we currently use moment although folks are moving away from moment, but supporting something like ${startDateFormat:theformat} makes sense

2) date math, could you give some requirements/examples around that? potentially could just use the splunk ish modifiers we support already.

**Comment by WilliamSalusky** [comment]
Darn it. I see what you're saying about separating req's from implementation. I couldn't help offering how I thought the result might look/work. I did after all say `support blah blah blah, LIKE:`  ;)

If the end result works, I'd use it. 

re: 1. I would be happy with the result being a `${startDateFormat:theformat}`

re: 2. For time modifiers I can get along just fine using Splunk style modifiers to increment / decrement the resulting time values that would be passed into link groups.
