### ISSUE TITLE
libyara8 not installable on Ubuntu Server 24.04 LTS

### ISSUE THREAD

**Issue by r2omega** [arkime/arkime#2830]
**Describe the bug**
Attempting to install arkime_5.2.0-1.ubuntu2204_amd64.deb results in error Depends: libyara8 but it is not installable.
Installing Yara results in libyara10.

**Elasticsearch version**:
elasticsearch-8.14.0-amd64

**Arkime/Moloch version**:
Arkime 5.2.0-1

**OS name and version**:
Ubuntu Server 24.04 LTS

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
deb

**Provide logs, stack traces and steps to reproduce**:
$ wget https://github.com/arkime/arkime/releases/download/v5.2.0/arkime_5.2.0-1.ubuntu2204_amd64.deb
$ sudo apt install -y ./arkime_5.2.0-1.ubuntu2204_amd64.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'arkime' instead of './arkime_5.2.0-1.ubuntu2204_amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
                                                                                                                     The following packages have unmet dependencies:                                                                       arkime : Depends: libyara8 but it is not installable                                                                E: Unable to correct problems, you have held broken packages.

**Comment by awick** [comment]
You need to use the ubuntu 24 arkime download.
