### ISSUE TITLE
Multiviewer getClinet() BUG on version 5.2.1

### ISSUE THREAD

**Issue by DavidCHIA-Rub** [arkime/arkime#2852]
**Describe the bug**
When I run as follows
```shell
cd /opt/arkime/viewer
/opt/arkime/bin/node multies.js -n multi-viewer
```
It reports a bug as follows
```
[
  'http://127.0.0.1:9200,name:ubuntu,prefix:arkime',
  'http://192.168.255.130:9200,name:centos'
]
Express server listening on host 127.0.0.1 port 8200 in development mode
/opt/arkime/common/user.js:125
    if (User.#implementation.getClient()) {
                             ^

TypeError: Cannot read properties of undefined (reading 'getClient')
    at User.getClient (/opt/arkime/common/user.js:125:30)
    at Timeout._onTimeout (/opt/arkime/common/auth.js:1041:30)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.20.3
```
**Elasticsearch version**:
8.6.2
**Arkime/Moloch version**:
5.2.1
**OS name and version**:
5.15.153.1-microsoft-standard-WSL2
**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
from source code
**Provide logs, stack traces and steps to reproduce**:
as metioned up

**Comment by awick** [comment]
Weird, multies shouldn't be using user or auth. I'll need your config file, at least the [default] and [multi-viewer] sections.

**Comment by DavidCHIA-Rub** [comment]
> Weird, multies shouldn't be using user or auth. I'll need your config file, at least the [default] and [multi-viewer] sections.

[config.txt](https://github.com/user-attachments/files/15945793/config.txt)
Here is the file, THANK YOU!

**Comment by DavidCHIA-Rub** [comment]
That fix it, thank you!!! I deleted the lines
1.authMode=basic+form
2.authCookieSecure=false
3.authTrustProxy=true

But how can I use the form method to log in Multiviewer?



摩登热血男儿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arkime/arkime"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月24日(星期一) 凌晨4:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arkime/arkime] Multiviewer getClinet() BUG on version 5.2.1 (Issue #2852)





 
Closed #2852 as completed via 7bbc6f6.

**Comment by awick** [comment]
You don't need to delete those lines if you update

**Comment by DavidCHIA-Rub** [comment]
> You don't need to delete those lines if you update

I'll update it!

**Comment by DavidCHIA-Rub** [comment]
After I upgrade to 5.3.0, the multiviewer occurs a new problem as follow. And I can't get into the multiviewer page. Here's the logs
```
/opt/arkime/common/auth.js:1130
      if (new Date().getTime() - _source._timestamp > ESStore.#ttl) {
                                         ^

TypeError: Cannot read properties of undefined (reading '_timestamp')
    at /opt/arkime/common/auth.js:1130:42
    at onBody (/opt/arkime/node_modules/@elastic/elasticsearch/lib/Transport.js:320:9)
    at IncomingMessage.onEnd (/opt/arkime/node_modules/@elastic/elasticsearch/lib/Transport.js:240:11)
    at IncomingMessage.emit (node:events:529:35)
    at endReadableNT (node:internal/streams/readable:1400:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```
And here's my [config.ini](https://github.com/user-attachments/files/16042143/config.ini.txt). I added 3 lines to make the form auth work.
```
authMode=basic+form
authCookieSecure=false
authTrustProxy=true
```
However, after I login into the normal viewer with form auth in the same browser, the multiviewer gets to work randomly.

**Comment by awick** [comment]
add
usersElasticsearch=http://127.0.0.1:9200
usersPrefix=arkime

I'll make a change to log an error

**Comment by DavidCHIA-Rub** [comment]
Roger that, thanks!

**Comment by DavidCHIA-Rub** [comment]
> add
> usersElasticsearch=http://127.0.0.1:9200
> usersPrefix=arkime
> 
> I'll make a change to log an error

It works, Wow!
