### ISSUE TITLE
Cold Storage

### ISSUE THREAD

**Issue by stevesecurityoverview** [arkime/arkime#2882]
There is no availability to configure a ILM policy beyond hot/warm.
Cold node ILM policies will have to be added ad-hoc to elasticsearch.

**Describe the solution you'd like**
An option to use a jsonfile as the ILM policy instead might prove to be very valuable

**Describe alternatives you've considered**
A command line solution using db.pl may be difficult to maintain given the high probability that ILM policies may be very unique (perhaps not and only an adjustment for cold storage is needed).

**Additional context**
Cold storage seems to be a license feature for elasticsearch atm.  It may be open for opensearch.

**Comment by awick** [comment]
Can you share what a full ILM policy looks for you?

If you just want to not even use the Arkime ILM policy that is already pretty easy to do, as long as you use the same name. Maybe the docs should do a better job calling that out.

**Comment by awick** [comment]
Feel free to reopen issue with more details
