### ISSUE TITLE
Malcolm Arkime has configured freeSpaceG=98%, but when there is insufficient space, Arkime does not delete the pcap file

### ISSUE THREAD

**Issue by alleniverson33** [arkime/arkime#2908]
If still having PCAP delete issues:

Verify [freeSpaceG](https://arkime.com/settings#freespaceg) is set correctly for the node in the config file
Restart viewer after turning on debugging by adding debug=2 in the [default] section of your config.ini file. After restarting viewer, check the viewer.log for messages or use grep -i expire /opt/arkime/logs/viewer.log to see the relevant messages
Make sure there is free space where viewer is writing its logs if you don't see any messages in viewer.log
Verify that [dropUser](https://arkime.com/settings#dropuser) or [dropGroup](https://arkime.com/settings#dropgroup) can actually delete files in the PCAP directory and has read/execute permissions in all parent directories. So for example you need to check the /opt and the /opt/arkime and the /opt/arkime/raw directory permissions. The PCAP files will have read/write permissions which is normal.
Make sure the PCAP directory is on a filesystem with at least [maxFileSizeG * 10](https://arkime.com/settings#maxfilesizeg) space available.
If there is a mismatch between the files in the directory and the files on the Files tab run the db.pl http://localhost:9200 sync-files command
Make sure the files in the file tab don't have locked set, viewer won't deleted locked files
Try restarting viewer
If using seilnux (sestatus) temporarily disable it (setenforce 0) and see if that fixes the problem.

I have tried all of the above 1, 2, 4, 5, and 8

**Comment by awick** [comment]
Hi, when filling out a bug report for folks please fill in the template instead of deleting it since that will save having to ask the questions again.
* what version?
* what OS?
* How did you install?

If not running a recent version please upgrade.

Please set the debug level to 2 and provide the output of `grep -i expire /opt/arkime/logs/viewer.log`

**Comment by alleniverson33** [comment]
> Hi, when filling out a bug report for folks please fill in the template instead of deleting it since that will save having to ask the questions again.
> 
> * what version?
> * what OS?
> * How did you install?
> 
> If not running a recent version please upgrade.
> 
> Please set the debug level to 2 and provide the output of `grep -i expire /opt/arkime/logs/viewer.log`

Does the use of mounted volumes in the pcap folder affect regular deletion？

**Comment by awick** [comment]
I think Malcolm does things differently. @mmguero can hopefully help. If there are no EXPIRE after increasing debug to 2 there is something definitely wrong.

**Comment by mmguero** [comment]
@alleniverson33 I already replied to your issue at idaholab/Malcolm#538. I don't think we need to open an Arkime issue, as (at least to start with) we need to debug it in the context of Malcolm. Why don't we continue our conversation there?

**Comment by awick** [comment]
Feel free to reopen if this turns out to be an Arkime issue.
