### ISSUE TITLE
`db.pl sync-files` uses node-name parsed from pcap filename, not from supplied node-name(s), when checking for missing files

### ISSUE THREAD

**Issue by dennisse** [arkime/arkime#2944]
**Describe the bug**

The synopsis for [`db.pl sync-files`](https://github.com/arkime/arkime/blob/583d8b2546529ca8e53e46f073f028119a7a1d29/db/db.pl#L239) is:
> sync-files  \<nodes\> \<dirs\> - Add/Remove in db any MISSING files on THIS machine for **named node(s)** and directory(s), both comma separated. [emphasis added]

And yet, when you run it, `db.pl` uses the [node-name it finds](https://github.com/arkime/arkime/blob/583d8b2546529ca8e53e46f073f028119a7a1d29/db/db.pl#L7234) in the name of the [pcap-files it parses](https://github.com/arkime/arkime/blob/583d8b2546529ca8e53e46f073f028119a7a1d29/db/db.pl#L7230).

Normally, this isn't really an issue. But, if you're renaming a node, and don't want to delete the old pcaps (*and* want them to be findable until they're rotated out, so no renaming), you would want to add/remove missing files only for the nodes you specify. Not the nodenames that are in the pcap-files.

Right now, you have to use `add-missing`/`rm-missing` to add/remove pcaps on "THIS machine for named node" (you could probably also use a node-alias).

Not a huge problem, but it did surprise me. `sync-files` is not working as [described](https://github.com/arkime/arkime/blob/583d8b2546529ca8e53e46f073f028119a7a1d29/db/db.pl#L239).

I'm not sure how this should be solved. Maybe the regex on [L7230](https://github.com/arkime/arkime/blob/583d8b2546529ca8e53e46f073f028119a7a1d29/db/db.pl#L7230) should match agains the provided node name(s) or something. Updating the doc to explain the current behaviour might also be a solution.

**Elasticsearch version**:
N/A

**Arkime/Moloch version**:
5.4.0

**OS name and version**:
N/A

**How was Arkime/Moloch built/installed:** (rpm, deb, easybutton, ...)
N/A

**Provide logs, stack traces and steps to reproduce**:
Problem is clearly visible in code. But you could also create a bunch of new pcap-files, give them different node-names, and run the sync.
```
$ dd if=/dev/random of=/tmp/fakepcap bs=1M count=10
$ for host in "test-host" "$(hostname -s)-dashtest" "alsotest"; do \
  for i in {01..10}; do \
    cp /tmp/fakepcap /pcapdir/testhost-$(date '+%y%m%d)-010000$i.pcap; done; done
$ /path/to/db.pl http://ES-host:port sync-files "$(hostname -s)" /pcapdir/
```
After running this, you should now have nodes named "test-host", "`$(hostname -s)`-dashtest", and "alsotest", with files, in your database. Even though you clearly only specified `$(hostname -s)`

**Comment by awick** [comment]
So sync-files takes a LIST of nodes, since you can have multiple nodes on a single machine. When it inserts the missing item it uses the node from the filename since it is added for a SINGLE node. As you've seen, sync-file is not for renaming nodes. It is hard to get what it is doing down to a single sentence if you have suggestions for help improvements let me know.

There probably should just be a feature request for a rename-node

**Comment by awick** [comment]
nodename is there incase you have multiple nodes writing to the same node but using different ES clusters or prefixes, or you just don't want to sync all the nodes files.

sync-files really is just a more optimized version of add-missing and rm-missing, allowing multiple nodes and dirs.

**Comment by awick** [comment]
Maybe an extra "given" will make it more clear?
"Add/Remove in db any MISSING files on THIS machine for all **given** nodes with existing files in given directory(s)"

**Comment by awick** [comment]
So I feel we are talking in circles. The way it is describe is the way I want it to function. If it isn't working that way, we should fix that. If you want something else we should add another command.

If it doesn't just do for the nodes listed that is a bug, and I think its line 7208 `my @files = grep { m/^$ARGV[2]-/ && -f "$dir/$_" } readdir($dh);` that should probably be $node instead of ARGV[2], although that means it should actually fail with multiple nodes right now and work with a single nodes, and you say that doesn't work.

**Comment by awick** [comment]
Ya I can't reproduce what you are saying how it add all files, here is how I tested
```
touch /tmp/test/foo-131203-00000001.pcap /tmp/test/bar-131203-00000001.pcap /tmp/test/foobar-131203-00000001.pcap
# tries to add /tmp/test/foo
db.pl http://localhost:9200  sync-files foo /tmp/test
# doesn't try to add anything
db.pl http://localhost:9200  sync-files foo,bar /tmp/test
```

Changing to $node and adding a rewinddir fixes the issue where it will add the foo,bar files. It either case it doesn't try and add a foobar file.

Can you provide the command line you are using where it adds files for nodes not listed or maybe I'm not understanding.

**Comment by awick** [comment]
ah, the old dash in the node name problem, ya we should handle that better! :)

**Comment by awick** [comment]
See if that looks good to you
