### ISSUE TITLE
Where is the complete list of all fields of rules?

### ISSUE THREAD

**Issue by zzwzds** [arkime/arkime#2968]
- name: "Tag Specific URL Traffic"
    when: "fieldSet"
    fields:
      host.http:
        - example.com
        - www.example.org
    ops:
      _maxPacketsToSave: 0
      _dontSaveSPI: 0
      
      this is the rule for http,but i want to get the fields for dns's rules ，such as host.dns（send error :can not find the fields : host.dns）
so , Where is the complete list of all fields?

**Comment by zzwzds** [comment]
> That's a bug from a dns rewrite we did, for now you can use dns.host

Thank you very much for your answer. I tried it and it worked, but I still want to ask if there is a complete list of rule fields, because I also want to know whether fields such as http.url support filtering.

**Comment by awick** [comment]
There is no doc, but most fields unless they are a combo of multiple fields should work. I don't think there is a http.url field, but there is http.uri which should work.

**Comment by zzwzds** [comment]
> There is no doc, but most fields unless they are a combo of multiple fields should work. I don't think there is a http.url field, but there is http.uri which should work.
Thank you very much for your reply. I'll bother you again. I also want to ask, I can set ip.src and ip.dst in the rules. If I want to match the source or destination IP of 10.0.0.1, how to set the rules (I found that ip:10.0.0.1 did not report an error, but it seemed to be ineffective). Also, how to issue the BPF rules of Arkime and whether the BPF rules can match the byte stream (regular expressions, etc.), there is too little information about Arkime on the Internet.

**Comment by awick** [comment]
So I'll answer these, but please come to Slack for questions https://arkime.com/questions

>  If I want to match the source or destination IP of 10.0.0.1, how to set the rules (I found that ip:10.0.0.1 did not report an error, but it seemed to be ineffective).

I would need to see the full rule, I would guess something else isn't matching

> Also, how to issue the BPF rules of Arkime

bpf: the bpf

> whether the BPF rules can match the byte stream (regular expressions, etc.)

BPF is just like the BPF with tcpdump, so it can do what that does. It mainly matches against packet headers. You can do some byte stream stuff with yara files.

> there is too little information about Arkime on the Internet.

Please contribute to the docs https://github.com/arkime/arkimeweb
