### ISSUE TITLE
changing some settings causes custom theme to be lost

### ISSUE THREAD

**Issue by mmguero** [arkime/arkime#3053]
1. Go to Settings > Themes
2. Enter a custom theme (I'm using `#222222,#E2E2E2,#FFFFFF,#00789E,#004A79,#017D73,#092B40,#42b7c5,#2A7580,#ecb30a,#333333,#89ADCC,#6D6D6D,#FFE7E7,#ECFEFF` but it probably doesn't matter)
3. click `Apply`
4. Navigate to sessions
5. Navigate back to settings
6. enter something in **Hide Tags From Sessions**
7. tab out of the text input there
8. the theme is reset

See video:

https://github.com/user-attachments/assets/c5b8b1af-8311-4216-806c-08267f398826

**Comment by awick** [comment]
This happens with almost any setting change, just sometimes you need to do a reload to see it. Looks like setTheme has this.settings.theme = 'custom-theme'; which replaces the theme on next save so on next reload the theme is lost.
