### ISSUE TITLE
smb backslash issue

### ISSUE THREAD

**Issue by awick** [arkime/arkime#375]
Clicking on a smb with \ in it causes the expression to match, but not treated as a backslash during the search.

example:
click on \spoolss causes expression smb.fn=="\spoolss" which will then match just "spoolss" without the backslash

**Comment by 31453** [comment]
@awick Just removing backslashes won't work because of values like "\tmp\foo". However searching for "\\tmp\\foo" works. Should we escape all backslashes in all searches (not just smb.x)?

**Comment by 31453** [comment]
This is an example of a query that doesn't work and should: https://demo.arkime.com/sessions?expression=smb.share%20%3D%3D%20%22%5C%5C10.10.0.2%5CADMIN%24%22&date=-1

**Comment by lesagi** [comment]
Hi, is this open? I see @31453  is assigned to it? @

**Comment by philhagen** [comment]
bumping this with additional context:

The filter from right-clicking an SPI field: `smb.fn == "shieldbase.lan\Policies\{3AED11CF-0291-4915-AA85-E95C65F7EA88}\gpt.ini"` does not return sessions
However, escaping the backslashes with `smb.fn == "shieldbase.lan\\Policies\\{3AED11CF-0291-4915-AA85-E95C65F7EA88}\\gpt.ini"` matches sessions as expected
