### ISSUE TITLE
MailMerge style reporting on sessions

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#429]
Generate a report per session within the current query scope that outputs user specified formatting with all meta including session payload/encoding options being accessible by the report operation.

**Comment by awick** [comment]
Example?  This can already be done with the viewer decoders I think

**Comment by awick** [comment]
Thoughts:
* Operators will be able to upload jade fragment into settings
 * should everyone, or controlled by a setting?
 * would be nice to have a global set also (this goes for views too while we are at it) that are shared that admins can set.  (Maybe have a global user that all users inherit from)
* Would be nice if at least 2 different fragment types are supported
 * Session - Simple kind where the fragment is per session, can't have headers or anything (unless some kind of hack ...)
 * Document - Advanced kind where the fragment is the whole document so you can do headers and stuff and maybe the session forloop is inside the fragment
* New sub menu in viewer that shows the possible mail merges
* New URI that takes the mail merges, expression, ... and processes
* Need to think about if jade fragments can be used to hack the planet
 * Obviously XSS bad javascript is possible, but not sure we care about that
 * Can jade template do stuff to file system, such as read /etc/passwd or write flies, if so how do we protect
* Need a better name then mail merge

**Comment by WilliamSalusky** [comment]
@awick 
Heh. Never meant to have it called mail merge. This is what you called it during lunch, and reused the term to refresh your memory. I think of it as 'session reporting' / 'SPI report'

**Comment by awick** [comment]
Still would like to do this but, ...

**Comment by 31453** [comment]
@awick but what? 🦋How does this differ from the summary (https://github.com/aol/moloch/issues/12) or narrative features (https://github.com/aol/moloch/issues/842)? Just that a user can provide a template/format?
