### ISSUE TITLE
Moloch UI - add PassiveTotal drop down for all primary datatypes

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#662]
Examples:

https://passivetotal.org/search/${DOMAIN/HOST}

https://passivetotal.org/search/${IP}

https://passivetotal.org/search/${EMAIL}

**Comment by awick** [comment]
This would be adding actionclicks to the wise source.passivetotal.js file

**Comment by awick** [comment]
@WilliamSalusky - these urls don't seem to work any more, do you happen to know the new ones?
