### ISSUE TITLE
arkime.com - Add SHA256 hashes

### ISSUE THREAD

**Issue by fsacer** [arkime/arkime#678]
Add HTTPS to the downloads page and provide SHA 256 checksums to verify downloads.

**Comment by kkirsche** [comment]
Which download site is this referencing? I assumed http://molo.ch from the title but this page doesn't load anything for me. 

Downloading via github is via HTTPS (from the https://github.com/aol/moloch/releases page)

<img width="1440" alt="screen-shot-2017-08-07-at-3 27 13-pm" src="https://user-images.githubusercontent.com/947110/29042456-efdf4fb6-7b84-11e7-96d9-ea3cdf34d212.png">

**Comment by awick** [comment]
yes, molo.ch, which is currently down

**Comment by 31453** [comment]
@awick we have https, how hard is it to add checksums to each download?

**Comment by wols** [comment]
Help requested: Where can the checksums be found?

**Comment by awick** [comment]
We currently don't publish checksums, and since we don't use s3 anymore its not automatic. The rpm and I think the deb files do have checksum built in. i guess we could maybe provide a .checksum file for each release, but it doesn't provide any security. How do you plan to use it?
