### ISSUE TITLE
PCAP Compressions

### ISSUE THREAD

**Issue by awick** [arkime/arkime#728]
- [ ] Design file format (probably 64k blocks that are compressed)
- [ ] Figure out how to encode? we have file, block position in file, packet position in uncompress/unencrypted block
- [ ] Change viewer support reader plugins
- [ ] Code writer
- [ ] Code reader

**Comment by paulpc** [comment]
i remember somebody laughing at me when i suggested this

**Comment by awick** [comment]
It used to be part of #484 but I moved out since I finished encryption.

We can probably save 10-20%, although a better way to save space is just to drop tls traffic after so many packets.  https://github.com/aol/moloch/wiki/RulesFormat

**Comment by DrKewp** [comment]
I'm doing this via btrfs.  Just mount the volume with forced compression, eg: compress-force=lzo.

**Comment by awick** [comment]
Curious if you've figured out what kind of compression ratio you are getting?  Part of the reason to add it to moloch someday is that it knows the data and can remove data BEFORE running the compression algorithm on the data.

**Comment by pjsg** [comment]
My thoughts on this were as follows:

* A compressed pcap file contains:
 * A gzip header
 * A number of individually compressed deflate blocks not exceeding 64k bytes in size (or 1MB of uncompressed PCAP data -- whichever comes first

A packetPos is then (offsetOfBlockStart << 20) + (offsetOfPacketStartInUncompressedData)

If this value is kept to the range  0 .. 2^53 - 1, then it can be exactly represented in Javascript. This gives a max compressed file size of around 8GB (2^33 bytes). 

The raw compressed file can be decompressed by `gzip` for other tools to analyze and can also be read by seeking to a block start and then inflating 64k of data.
