### ISSUE TITLE
viewer hangs indefinitely if multies cannot connect to a remote  node. 

### ISSUE THREAD

**Issue by ejclark1** [arkime/arkime#745]
If a host in multies cannot be reached, then viewer hangs indefinitely. Please note the timeout in the sessions.js in the viewer.log entry. The first log is from multies.log.

---
Request error with node 1.2.3.4:9200 { [Error: connect ECONNREFUSED 1.2.3.4:9200]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '1.2.3.4,
  port: 9200 }
---
Mon, 16 Oct 2017 12:46:42 GMT clarkej1 GET /moloch/sessions.json?bounding=last&facets=1&fields=pr,tipv61-term,tipv62-term&flatten=1&length=50&order=fp:asc&startTime=1508153854&stopTime=1508157454 - - bytes - ms
sessions.json error { [Error: Request Timeout after 300000ms]
  status: 408,
  displayName: 'RequestTimeout',
  message: 'Request Timeout after 300000ms' } null

**Elasticsearch version**: ES5

**Moloch version**: 19.1

**OS name and version**: RHEL 7.4

**How was Moloch built/installed:** (rpm, deb, singlehost built, ...) rpm

**Provide logs, stack traces and steps to reproduce**: Stand up multies. Disable a remote node. Multiviewer will no longer be accessible.

**Comment by awick** [comment]
This was fixed
