### ISSUE TITLE
Feature request : track http request and response header counts

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#804]
Count and log the number of unique GET/POST/etc requests and response headers in an HTTP pipeline.

I want to be able to query on field values for example when an http/1.1 session has: 

( http.reqhdr.cnt > 3 )

or 

( http.resphdr.cnt >2 )

If you build it in, name the field whatever makes sense to you.

**Comment by awick** [comment]
http.hasheader.src.cnt and http.hasheader.dst.cnt I think will do what you want

**Comment by WilliamSalusky** [comment]
http.hasheader.src.cnt and http.hasheader.dst.cnt track the number of request headers, but I'm looking for the number of method based requests.  i.e. How many GET's POST's, etc.. are in the pipeline, likewise the number of server responses.

**Comment by awick** [comment]
still confused, do want unique counts of GETS vs POST vs ... in a single session.  Or are you saying you just want the totally number of requests/responses in a session?

**Comment by awick** [comment]
@WilliamSalusky need more info

**Comment by kmcgerald** [comment]
I think I speak W enough to translate.  
TCP session starts.
Client makes GET
Server makes response
Client makes GET
Server makes response
Client makes POST
Server makes response
TCP session ends

http.req.cnt = 3 (2 GET + 1 POST)
http.res.cnt = 3

**Comment by WilliamSalusky** [comment]
maybe even generate:
http.${METHOD}.cnt
