### ISSUE TITLE
UI feature : Narrative support

### ISSUE THREAD

**Issue by WilliamSalusky** [arkime/arkime#842]
Mostly a placeholder for real world discussion. I'd like to have the function to create a Narrative/[cool story bro] based on sessions within the query scope, or individually selected sessions to be thrown into a Narrative timeline. This is intended to support forensic analyst reporting and knowledge share.

**Comment by 31453** [comment]
@WilliamSalusky Can you provide more information on what would be included in this narrative? The use case behind it? A workflow of how you imagine it would work? This could be a cool feature, but we need more information about how it would work.

**Comment by 31453** [comment]
Also, how does this differ from https://github.com/aol/moloch/issues/12
